targets:
  $default:
    builders:
      isar_generator:
        generate_for:
          include:
            - lib/services/cache/models/**
            - lib/models/**
          exclude:
            - lib/src/rust/**
