// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api/bangumi/types.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<BangumiCharacterSearchResult>> searchBangumiCharacters({
  required String keyword,
  required int page,
}) => RustLib.instance.api.crateFrbApiBangumiSearchBangumiCharacters(
  keyword: keyword,
  page: page,
);

Future<List<BangumiPersonSearchResult>> searchBangumiPersons({
  required String keyword,
  required int page,
}) => RustLib.instance.api.crateFrbApiBangumiSearchBangumiPersons(
  keyword: keyword,
  page: page,
);

Future<List<BangumiEpisode>> fetchBangumiEpisodes({
  required PlatformInt64 subjectId,
}) => RustLib.instance.api.crateFrbApiBangumiFetchBangumiEpisodes(
  subjectId: subjectId,
);

Future<List<BangumiCharacter>> fetchBangumiCharacters({
  required PlatformInt64 subjectId,
}) => RustLib.instance.api.crateFrbApiBangumiFetchBangumiCharacters(
  subjectId: subjectId,
);

Future<List<BangumiRelatedSubject>> fetchBangumiRelations({
  required PlatformInt64 subjectId,
}) => RustLib.instance.api.crateFrbApiBangumiFetchBangumiRelations(
  subjectId: subjectId,
);

Future<BangumiCommentsPage> fetchBangumiComments({
  required PlatformInt64 subjectId,
  required int page,
}) => RustLib.instance.api.crateFrbApiBangumiFetchBangumiComments(
  subjectId: subjectId,
  page: page,
);

Future<List<BangumiPerson>> fetchBangumiPersons({
  required PlatformInt64 subjectId,
}) => RustLib.instance.api.crateFrbApiBangumiFetchBangumiPersons(
  subjectId: subjectId,
);

Future<List<BangumiEpisodeComment>> fetchBangumiEpisodeComments({
  required PlatformInt64 episodeId,
}) => RustLib.instance.api.crateFrbApiBangumiFetchBangumiEpisodeComments(
  episodeId: episodeId,
);

Future<BangumiReviewsPage> fetchBangumiSubjectReviews({
  required PlatformInt64 subjectId,
  required int page,
}) => RustLib.instance.api.crateFrbApiBangumiFetchBangumiSubjectReviews(
  subjectId: subjectId,
  page: page,
);

Future<BangumiBlogDetail> fetchBangumiBlogDetail({
  required PlatformInt64 entryId,
}) => RustLib.instance.api.crateFrbApiBangumiFetchBangumiBlogDetail(
  entryId: entryId,
);

Future<List<BangumiEpisodeComment>> fetchBangumiBlogComments({
  required PlatformInt64 entryId,
}) => RustLib.instance.api.crateFrbApiBangumiFetchBangumiBlogComments(
  entryId: entryId,
);

Future<BangumiTopicsPage> fetchBangumiSubjectTopics({
  required PlatformInt64 subjectId,
  required int page,
}) => RustLib.instance.api.crateFrbApiBangumiFetchBangumiSubjectTopics(
  subjectId: subjectId,
  page: page,
);

Future<BangumiTopicDetail> fetchBangumiTopicDetail({
  required PlatformInt64 topicId,
}) => RustLib.instance.api.crateFrbApiBangumiFetchBangumiTopicDetail(
  topicId: topicId,
);

Future<CharacterDetails> fetchCharacterDetails({
  required PlatformInt64 characterId,
}) => RustLib.instance.api.crateFrbApiBangumiFetchCharacterDetails(
  characterId: characterId,
);

Future<PersonDetails> fetchPersonDetails({required PlatformInt64 personId}) =>
    RustLib.instance.api.crateFrbApiBangumiFetchPersonDetails(
      personId: personId,
    );

Future<List<PersonSubject>> fetchPersonSubjects({
  required PlatformInt64 personId,
}) => RustLib.instance.api.crateFrbApiBangumiFetchPersonSubjects(
  personId: personId,
);

Future<List<PersonCharacter>> fetchPersonCharacters({
  required PlatformInt64 personId,
}) => RustLib.instance.api.crateFrbApiBangumiFetchPersonCharacters(
  personId: personId,
);

Future<List<CharacterSubject>> fetchCharacterSubjects({
  required PlatformInt64 characterId,
}) => RustLib.instance.api.crateFrbApiBangumiFetchCharacterSubjects(
  characterId: characterId,
);

Future<List<BangumiEpisodeComment>> fetchBangumiCharacterComments({
  required PlatformInt64 characterId,
}) => RustLib.instance.api.crateFrbApiBangumiFetchBangumiCharacterComments(
  characterId: characterId,
);

Future<List<BangumiEpisodeComment>> fetchBangumiPersonComments({
  required PlatformInt64 personId,
}) => RustLib.instance.api.crateFrbApiBangumiFetchBangumiPersonComments(
  personId: personId,
);

Future<BangumiUserInfo> fetchBangumiUserInfo({required String username}) =>
    RustLib.instance.api.crateFrbApiBangumiFetchBangumiUserInfo(
      username: username,
    );

Future<List<BangumiUserCollectionEntry>> fetchBangumiUserCollections({
  required String username,
  required int subjectType,
  required int limit,
  required int offset,
}) => RustLib.instance.api.crateFrbApiBangumiFetchBangumiUserCollections(
  username: username,
  subjectType: subjectType,
  limit: limit,
  offset: offset,
);

Future<Uint8List> fetchBangumiSubjectImage({
  required PlatformInt64 subjectId,
  required String imageType,
}) => RustLib.instance.api.crateFrbApiBangumiFetchBangumiSubjectImage(
  subjectId: subjectId,
  imageType: imageType,
);

Future<Uint8List> fetchBangumiImageUrl({required String url}) =>
    RustLib.instance.api.crateFrbApiBangumiFetchBangumiImageUrl(url: url);

/// The OAuth `client_id` for building the authorization URL that the login
/// WebView opens. Not a secret — it appears in that URL in plaintext.
Future<String> bangumiOauthClientId() =>
    RustLib.instance.api.crateFrbApiBangumiBangumiOauthClientId();

/// The OAuth authorization page URL the login WebView opens. Pins `bgm.tv`
/// (never an alias or the optional content reverse proxy). `redirect_uri` must
/// match the value later passed to [`exchange_bangumi_oauth_code`]
/// byte-for-byte.
Future<String> bangumiOauthAuthorizeUrl({required String redirectUri}) =>
    RustLib.instance.api.crateFrbApiBangumiBangumiOauthAuthorizeUrl(
      redirectUri: redirectUri,
    );

/// Exchange an OAuth authorization `code` for an access/refresh token pair.
/// The `client_secret` stays on the Rust side of the bridge, but remains
/// extractable from a distributed client binary.
Future<BangumiOAuthToken> exchangeBangumiOauthCode({
  required String code,
  required String redirectUri,
}) => RustLib.instance.api.crateFrbApiBangumiExchangeBangumiOauthCode(
  code: code,
  redirectUri: redirectUri,
);

/// Refresh an access token using the stored `refresh_token`.
Future<BangumiOAuthToken> refreshBangumiOauthToken({
  required String refreshToken,
  required String redirectUri,
}) => RustLib.instance.api.crateFrbApiBangumiRefreshBangumiOauthToken(
  refreshToken: refreshToken,
  redirectUri: redirectUri,
);

/// `GET /v0/me` — the authenticated user's profile. Requires a stored token.
Future<BangumiUserInfo> fetchBangumiMe() =>
    RustLib.instance.api.crateFrbApiBangumiFetchBangumiMe();

/// `GET /v0/users/{username}/collections` — the authenticated user's own
/// collections. `collection_type` of `0` means "all types" (no filter).
///
/// Requires the real `username` (from `/v0/me`): the list endpoint returns 404
/// for the literal `-` alias, unlike the write endpoint. The bearer token is
/// still sent so private collections are included.
Future<List<BangumiUserCollectionEntry>> fetchMyBangumiCollections({
  required String username,
  required int subjectType,
  required int collectionType,
  required int limit,
  required int offset,
}) => RustLib.instance.api.crateFrbApiBangumiFetchMyBangumiCollections(
  username: username,
  subjectType: subjectType,
  collectionType: collectionType,
  limit: limit,
  offset: offset,
);

/// `POST /v0/users/-/collections/{subject_id}` — upsert the authenticated
/// user's collection for a subject. Optional fields left `None` are omitted
/// from the request so an existing rating/comment is not clobbered.
Future<void> updateBangumiCollection({
  required PlatformInt64 subjectId,
  required int collectionType,
  int? rate,
  String? comment,
  List<String>? tags,
  bool? private,
}) => RustLib.instance.api.crateFrbApiBangumiUpdateBangumiCollection(
  subjectId: subjectId,
  collectionType: collectionType,
  rate: rate,
  comment: comment,
  tags: tags,
  private: private,
);

/// Set or change only the collection status using the idempotent POST path.
Future<void> setBangumiCollectionStatus({
  required PlatformInt64 subjectId,
  required int collectionType,
}) => RustLib.instance.api.crateFrbApiBangumiSetBangumiCollectionStatus(
  subjectId: subjectId,
  collectionType: collectionType,
);

/// Read one authenticated collection. Returns `None` when uncollected.
Future<BangumiUserCollectionEntry?> fetchMyBangumiCollection({
  required String username,
  required PlatformInt64 subjectId,
}) => RustLib.instance.api.crateFrbApiBangumiFetchMyBangumiCollection(
  username: username,
  subjectId: subjectId,
);

/// Read only the collection type for compatibility with existing callers.
Future<int?> fetchMyBangumiCollectionType({
  required String username,
  required PlatformInt64 subjectId,
}) => RustLib.instance.api.crateFrbApiBangumiFetchMyBangumiCollectionType(
  username: username,
  subjectId: subjectId,
);

/// Patch only collection metadata. `None` omits a field; an empty tag list
/// clears all tags. `type` is intentionally not part of this request.
Future<void> patchBangumiCollectionMetadata({
  required PlatformInt64 subjectId,
  int? rate,
  String? comment,
  List<String>? tags,
  bool? private,
}) => RustLib.instance.api.crateFrbApiBangumiPatchBangumiCollectionMetadata(
  subjectId: subjectId,
  rate: rate,
  comment: comment,
  tags: tags,
  private: private,
);

/// `DELETE /v0/users/-/collections/{subject_id}` — remove the authenticated
/// user's collection entry for a subject.
Future<void> deleteBangumiCollection({required PlatformInt64 subjectId}) =>
    RustLib.instance.api.crateFrbApiBangumiDeleteBangumiCollection(
      subjectId: subjectId,
    );
