// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api/bangumi/types.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<BangumiEpisode>> fetchBangumiEpisodes({
  required PlatformInt64 subjectId,
}) => RustLib.instance.api.crateFrbApiBangumiFetchBangumiEpisodes(
  subjectId: subjectId,
);

Future<List<BangumiCharacter>> fetchBangumiCharacters({
  required PlatformInt64 subjectId,
}) => RustLib.instance.api.crateFrbApiBangumiFetchBangumiCharacters(
  subjectId: subjectId,
);

Future<List<BangumiRelatedSubject>> fetchBangumiRelations({
  required PlatformInt64 subjectId,
}) => RustLib.instance.api.crateFrbApiBangumiFetchBangumiRelations(
  subjectId: subjectId,
);

Future<List<BangumiComment>> fetchBangumiComments({
  required PlatformInt64 subjectId,
  required int page,
}) => RustLib.instance.api.crateFrbApiBangumiFetchBangumiComments(
  subjectId: subjectId,
  page: page,
);

Future<List<BangumiPerson>> fetchBangumiPersons({
  required PlatformInt64 subjectId,
}) => RustLib.instance.api.crateFrbApiBangumiFetchBangumiPersons(
  subjectId: subjectId,
);

Future<List<BangumiEpisodeComment>> fetchBangumiEpisodeComments({
  required PlatformInt64 episodeId,
}) => RustLib.instance.api.crateFrbApiBangumiFetchBangumiEpisodeComments(
  episodeId: episodeId,
);

Future<CharacterDetails> fetchCharacterDetails({
  required PlatformInt64 characterId,
}) => RustLib.instance.api.crateFrbApiBangumiFetchCharacterDetails(
  characterId: characterId,
);

Future<PersonDetails> fetchPersonDetails({required PlatformInt64 personId}) =>
    RustLib.instance.api.crateFrbApiBangumiFetchPersonDetails(
      personId: personId,
    );

Future<List<PersonSubject>> fetchPersonSubjects({
  required PlatformInt64 personId,
}) => RustLib.instance.api.crateFrbApiBangumiFetchPersonSubjects(
  personId: personId,
);

Future<List<PersonCharacter>> fetchPersonCharacters({
  required PlatformInt64 personId,
}) => RustLib.instance.api.crateFrbApiBangumiFetchPersonCharacters(
  personId: personId,
);

Future<List<CharacterSubject>> fetchCharacterSubjects({
  required PlatformInt64 characterId,
}) => RustLib.instance.api.crateFrbApiBangumiFetchCharacterSubjects(
  characterId: characterId,
);

Future<BangumiUserInfo> fetchBangumiUserInfo({required String username}) =>
    RustLib.instance.api.crateFrbApiBangumiFetchBangumiUserInfo(
      username: username,
    );

Future<List<BangumiUserCollectionEntry>> fetchBangumiUserCollections({
  required String username,
  required int subjectType,
  required int limit,
  required int offset,
}) => RustLib.instance.api.crateFrbApiBangumiFetchBangumiUserCollections(
  username: username,
  subjectType: subjectType,
  limit: limit,
  offset: offset,
);

Future<Uint8List> fetchBangumiSubjectImage({
  required PlatformInt64 subjectId,
  required String imageType,
}) => RustLib.instance.api.crateFrbApiBangumiFetchBangumiSubjectImage(
  subjectId: subjectId,
  imageType: imageType,
);

Future<Uint8List> fetchBangumiImageUrl({required String url}) =>
    RustLib.instance.api.crateFrbApiBangumiFetchBangumiImageUrl(url: url);
