// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api/crawler/types.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<ArchiveQuarter>> fetchArchiveList() =>
    RustLib.instance.api.crateFrbApiCrawlerFetchArchiveList();

Future<List<AnimeInfo>> fetchScheduleBasic({required String yearQuarter}) =>
    RustLib.instance.api.crateFrbApiCrawlerFetchScheduleBasic(
      yearQuarter: yearQuarter,
    );

Future<List<AnimeInfo>> fetchScheduleBasicApiOnly({
  required String yearQuarter,
}) => RustLib.instance.api.crateFrbApiCrawlerFetchScheduleBasicApiOnly(
  yearQuarter: yearQuarter,
);

Future<List<AnimeInfo>> fetchScheduleBasicFromLocalJson({
  required String yearQuarter,
}) => RustLib.instance.api.crateFrbApiCrawlerFetchScheduleBasicFromLocalJson(
  yearQuarter: yearQuarter,
);

Future<List<AnimeInfo>> fetchScheduleBasicFromLocalJsonNodl({
  required String yearQuarter,
}) =>
    RustLib.instance.api.crateFrbApiCrawlerFetchScheduleBasicFromLocalJsonNodl(
      yearQuarter: yearQuarter,
    );

Future<void> spawnSitesIndexBackground() =>
    RustLib.instance.api.crateFrbApiCrawlerSpawnSitesIndexBackground();

Future<BigInt> buildSitesIndex() =>
    RustLib.instance.api.crateFrbApiCrawlerBuildSitesIndex();

Future<void> invalidateSitesIndex() =>
    RustLib.instance.api.crateFrbApiCrawlerInvalidateSitesIndex();

Future<List<BangumiDataSiteEntry>> fetchBangumiDataSites({
  required PlatformInt64 bangumiId,
}) => RustLib.instance.api.crateFrbApiCrawlerFetchBangumiDataSites(
  bangumiId: bangumiId,
);

Future<List<BangumiDataSiteEntry>> fetchBangumiDataSitesByMikan({
  required PlatformInt64 mikanId,
}) => RustLib.instance.api.crateFrbApiCrawlerFetchBangumiDataSitesByMikan(
  mikanId: mikanId,
);

Future<PlatformInt64?> lookupMikanId({required PlatformInt64 bangumiId}) =>
    RustLib.instance.api.crateFrbApiCrawlerLookupMikanId(bangumiId: bangumiId);

Future<List<AnimeInfo>> fillAnimeDetails({required List<AnimeInfo> animes}) =>
    RustLib.instance.api.crateFrbApiCrawlerFillAnimeDetails(animes: animes);

Future<AnimeInfo> fetchLightSubjectDetails({
  required PlatformInt64 subjectId,
}) => RustLib.instance.api.crateFrbApiCrawlerFetchLightSubjectDetails(
  subjectId: subjectId,
);

Future<List<AnimeInfo>> fetchExtraSubjects({
  required String yearQuarter,
  required List<String> existingIds,
}) => RustLib.instance.api.crateFrbApiCrawlerFetchExtraSubjects(
  yearQuarter: yearQuarter,
  existingIds: existingIds,
);

Future<BangumiDataCacheStatus> getBangumiDataCacheStatus() =>
    RustLib.instance.api.crateFrbApiCrawlerGetBangumiDataCacheStatus();

Future<bool> refreshBangumiDataCache() =>
    RustLib.instance.api.crateFrbApiCrawlerRefreshBangumiDataCache();

Future<bool> ensureBangumiDataCache({required BigInt maxAgeSecs}) => RustLib
    .instance
    .api
    .crateFrbApiCrawlerEnsureBangumiDataCache(maxAgeSecs: maxAgeSecs);
