// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api/generic_scraper/types.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `validate_runtime_overrides`, `validate_source_update`

Future<void> invalidateSourceConfigCache() =>
    RustLib.instance.api.crateFrbApiGenericScraperInvalidateSourceConfigCache();

Future<String> refreshPlaybackSourceConfig() =>
    RustLib.instance.api.crateFrbApiGenericScraperRefreshPlaybackSourceConfig();

Future<void> preloadPlaybackSources() =>
    RustLib.instance.api.crateFrbApiGenericScraperPreloadPlaybackSources();

Future<List<SourceState>> getPlaybackSources() =>
    RustLib.instance.api.crateFrbApiGenericScraperGetPlaybackSources();

Future<void> updateSingleSourceConfig({required SourceConfigUpdate update}) =>
    RustLib.instance.api.crateFrbApiGenericScraperUpdateSingleSourceConfig(
      update: update,
    );

Future<void> addSourceConfig({required SourceConfigUpdate newConfig}) => RustLib
    .instance
    .api
    .crateFrbApiGenericScraperAddSourceConfig(newConfig: newConfig);

Future<List<SearchPlayResult>> genericSearchPlayPages({
  required String animeName,
  int? absoluteEpisode,
  int? relativeEpisode,
}) => RustLib.instance.api.crateFrbApiGenericScraperGenericSearchPlayPages(
  animeName: animeName,
  absoluteEpisode: absoluteEpisode,
  relativeEpisode: relativeEpisode,
);

Stream<SearchPlayResult> genericSearchPlayPagesStream({
  required String animeName,
  int? absoluteEpisode,
  int? relativeEpisode,
}) =>
    RustLib.instance.api.crateFrbApiGenericScraperGenericSearchPlayPagesStream(
      animeName: animeName,
      absoluteEpisode: absoluteEpisode,
      relativeEpisode: relativeEpisode,
    );

Future<List<String>> getEnabledSourceNames() =>
    RustLib.instance.api.crateFrbApiGenericScraperGetEnabledSourceNames();

Stream<SourceSearchProgress> genericSearchWithProgress({
  required String animeName,
  int? absoluteEpisode,
  int? relativeEpisode,
}) => RustLib.instance.api.crateFrbApiGenericScraperGenericSearchWithProgress(
  animeName: animeName,
  absoluteEpisode: absoluteEpisode,
  relativeEpisode: relativeEpisode,
);

Stream<SourceSearchProgress> genericSearchWithProgressRuntime({
  required String animeName,
  int? absoluteEpisode,
  int? relativeEpisode,
  List<String>? targetSourceNames,
  required List<SourceRuntimeOverride> runtimeOverrides,
}) => RustLib.instance.api
    .crateFrbApiGenericScraperGenericSearchWithProgressRuntime(
      animeName: animeName,
      absoluteEpisode: absoluteEpisode,
      relativeEpisode: relativeEpisode,
      targetSourceNames: targetSourceNames,
      runtimeOverrides: runtimeOverrides,
    );

Stream<SourceSearchProgress> debugSearchWithLocalJson({
  required String jsonPath,
  required String animeName,
  int? absoluteEpisode,
  int? relativeEpisode,
  String? sourceNameFilter,
}) => RustLib.instance.api.crateFrbApiGenericScraperDebugSearchWithLocalJson(
  jsonPath: jsonPath,
  animeName: animeName,
  absoluteEpisode: absoluteEpisode,
  relativeEpisode: relativeEpisode,
  sourceNameFilter: sourceNameFilter,
);

Stream<SourceSearchProgress> debugSearchWithLocalJsonRuntime({
  required String jsonPath,
  required String animeName,
  int? absoluteEpisode,
  int? relativeEpisode,
  String? sourceNameFilter,
  required List<SourceRuntimeOverride> runtimeOverrides,
}) => RustLib.instance.api
    .crateFrbApiGenericScraperDebugSearchWithLocalJsonRuntime(
      jsonPath: jsonPath,
      animeName: animeName,
      absoluteEpisode: absoluteEpisode,
      relativeEpisode: relativeEpisode,
      sourceNameFilter: sourceNameFilter,
      runtimeOverrides: runtimeOverrides,
    );

Future<String> genericSearchAndPlayWithEpisode({
  required String animeName,
  int? absoluteEpisode,
  int? relativeEpisode,
}) => RustLib.instance.api
    .crateFrbApiGenericScraperGenericSearchAndPlayWithEpisode(
      animeName: animeName,
      absoluteEpisode: absoluteEpisode,
      relativeEpisode: relativeEpisode,
    );

Future<String> genericSearchAndPlay({required String animeName}) => RustLib
    .instance
    .api
    .crateFrbApiGenericScraperGenericSearchAndPlay(animeName: animeName);

Future<List<SearchResultWithChannels>> genericSearchWithChannels({
  required String animeName,
}) => RustLib.instance.api.crateFrbApiGenericScraperGenericSearchWithChannels(
  animeName: animeName,
);

Stream<SearchResultWithChannels> genericSearchWithChannelsStream({
  required String animeName,
}) => RustLib.instance.api
    .crateFrbApiGenericScraperGenericSearchWithChannelsStream(
      animeName: animeName,
    );

Future<SearchPlayResult> getEpisodePlayUrl({
  required String sourceName,
  required String animeName,
  required BigInt channelIndex,
  int? episodeNumber,
  SourceRuntimeOverride? runtimeOverride,
}) => RustLib.instance.api.crateFrbApiGenericScraperGetEpisodePlayUrl(
  sourceName: sourceName,
  animeName: animeName,
  channelIndex: channelIndex,
  episodeNumber: episodeNumber,
  runtimeOverride: runtimeOverride,
);
