// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/bangumi.dart';
import 'api/bangumi_graphql.dart';
import 'api/captcha.dart';
import 'api/config.dart';
import 'api/crawler.dart';
import 'api/danmaku.dart';
import 'api/dmhy.dart';
import 'api/ech.dart';
import 'api/generic_scraper.dart';
import 'api/mikan.dart';
import 'api/network.dart';
import 'api/ranking.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ValuePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Value
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    dynamic raw,
  );

  @protected
  Value
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    dynamic raw,
  );

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  Map<PlatformInt64, Value>
  dco_decode_Map_i_64_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue_None(
    dynamic raw,
  );

  @protected
  Value
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    dynamic raw,
  );

  @protected
  RustStreamSink<SearchPlayResult> dco_decode_StreamSink_search_play_result_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<SearchResultWithChannels>
  dco_decode_StreamSink_search_result_with_channels_Sse(dynamic raw);

  @protected
  RustStreamSink<SourceSearchProgress>
  dco_decode_StreamSink_source_search_progress_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AnimeInfo dco_decode_anime_info(dynamic raw);

  @protected
  ArchiveQuarter dco_decode_archive_quarter(dynamic raw);

  @protected
  BangumiActor dco_decode_bangumi_actor(dynamic raw);

  @protected
  BangumiCharacter dco_decode_bangumi_character(dynamic raw);

  @protected
  BangumiComment dco_decode_bangumi_comment(dynamic raw);

  @protected
  BangumiDataCacheStatus dco_decode_bangumi_data_cache_status(dynamic raw);

  @protected
  BangumiDataSiteEntry dco_decode_bangumi_data_site_entry(dynamic raw);

  @protected
  BangumiEpisode dco_decode_bangumi_episode(dynamic raw);

  @protected
  BangumiEpisodeComment dco_decode_bangumi_episode_comment(dynamic raw);

  @protected
  BangumiImages dco_decode_bangumi_images(dynamic raw);

  @protected
  BangumiPerson dco_decode_bangumi_person(dynamic raw);

  @protected
  BangumiRelatedSubject dco_decode_bangumi_related_subject(dynamic raw);

  @protected
  BangumiTvEpisode dco_decode_bangumi_tv_episode(dynamic raw);

  @protected
  BangumiUserCollectionEntry dco_decode_bangumi_user_collection_entry(
    dynamic raw,
  );

  @protected
  BangumiUserInfo dco_decode_bangumi_user_info(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BangumiImages dco_decode_box_autoadd_bangumi_images(dynamic raw);

  @protected
  CaptchaConstraintOptions dco_decode_box_autoadd_captcha_constraint_options(
    dynamic raw,
  );

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  MikanSearchResult dco_decode_box_autoadd_mikan_search_result(dynamic raw);

  @protected
  SourceConfigUpdate dco_decode_box_autoadd_source_config_update(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw);

  @protected
  CaptchaConstraintOptions dco_decode_captcha_constraint_options(dynamic raw);

  @protected
  ChannelInfo dco_decode_channel_info(dynamic raw);

  @protected
  CharacterDetails dco_decode_character_details(dynamic raw);

  @protected
  CharacterStat dco_decode_character_stat(dynamic raw);

  @protected
  CharacterSubject dco_decode_character_subject(dynamic raw);

  @protected
  CharacterSubjectPerson dco_decode_character_subject_person(dynamic raw);

  @protected
  Danmaku dco_decode_danmaku(dynamic raw);

  @protected
  DanmakuAnime dco_decode_danmaku_anime(dynamic raw);

  @protected
  DanmakuEpisode dco_decode_danmaku_episode(dynamic raw);

  @protected
  DanmakuMatch dco_decode_danmaku_match(dynamic raw);

  @protected
  DmhyResource dco_decode_dmhy_resource(dynamic raw);

  @protected
  EpisodeInfo dco_decode_episode_info(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  InfoboxItem dco_decode_infobox_item(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AnimeInfo> dco_decode_list_anime_info(dynamic raw);

  @protected
  List<ArchiveQuarter> dco_decode_list_archive_quarter(dynamic raw);

  @protected
  List<BangumiActor> dco_decode_list_bangumi_actor(dynamic raw);

  @protected
  List<BangumiCharacter> dco_decode_list_bangumi_character(dynamic raw);

  @protected
  List<BangumiComment> dco_decode_list_bangumi_comment(dynamic raw);

  @protected
  List<BangumiDataSiteEntry> dco_decode_list_bangumi_data_site_entry(
    dynamic raw,
  );

  @protected
  List<BangumiEpisode> dco_decode_list_bangumi_episode(dynamic raw);

  @protected
  List<BangumiEpisodeComment> dco_decode_list_bangumi_episode_comment(
    dynamic raw,
  );

  @protected
  List<BangumiPerson> dco_decode_list_bangumi_person(dynamic raw);

  @protected
  List<BangumiRelatedSubject> dco_decode_list_bangumi_related_subject(
    dynamic raw,
  );

  @protected
  List<BangumiTvEpisode> dco_decode_list_bangumi_tv_episode(dynamic raw);

  @protected
  List<BangumiUserCollectionEntry>
  dco_decode_list_bangumi_user_collection_entry(dynamic raw);

  @protected
  List<ChannelInfo> dco_decode_list_channel_info(dynamic raw);

  @protected
  List<CharacterSubject> dco_decode_list_character_subject(dynamic raw);

  @protected
  List<CharacterSubjectPerson> dco_decode_list_character_subject_person(
    dynamic raw,
  );

  @protected
  List<Danmaku> dco_decode_list_danmaku(dynamic raw);

  @protected
  List<DanmakuAnime> dco_decode_list_danmaku_anime(dynamic raw);

  @protected
  List<DanmakuEpisode> dco_decode_list_danmaku_episode(dynamic raw);

  @protected
  List<DanmakuMatch> dco_decode_list_danmaku_match(dynamic raw);

  @protected
  List<DmhyResource> dco_decode_list_dmhy_resource(dynamic raw);

  @protected
  List<EpisodeInfo> dco_decode_list_episode_info(dynamic raw);

  @protected
  List<InfoboxItem> dco_decode_list_infobox_item(dynamic raw);

  @protected
  List<MikanEpisodeResource> dco_decode_list_mikan_episode_resource(
    dynamic raw,
  );

  @protected
  List<PersonCharacter> dco_decode_list_person_character(dynamic raw);

  @protected
  List<PersonSubject> dco_decode_list_person_subject(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RankingAnime> dco_decode_list_ranking_anime(dynamic raw);

  @protected
  List<(PlatformInt64, Value)>
  dco_decode_list_record_i_64_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value(
    dynamic raw,
  );

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<SearchPlayResult> dco_decode_list_search_play_result(dynamic raw);

  @protected
  List<SearchResultWithChannels> dco_decode_list_search_result_with_channels(
    dynamic raw,
  );

  @protected
  List<SourceRuntimeOverride> dco_decode_list_source_runtime_override(
    dynamic raw,
  );

  @protected
  List<SourceState> dco_decode_list_source_state(dynamic raw);

  @protected
  List<TorrentStats> dco_decode_list_torrent_stats(dynamic raw);

  @protected
  List<TrackerInfo> dco_decode_list_tracker_info(dynamic raw);

  @protected
  MikanEpisodeResource dco_decode_mikan_episode_resource(dynamic raw);

  @protected
  MikanSearchResult dco_decode_mikan_search_result(dynamic raw);

  @protected
  Map<String, String>? dco_decode_opt_Map_String_String_None(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BangumiImages? dco_decode_opt_box_autoadd_bangumi_images(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  MikanSearchResult? dco_decode_opt_box_autoadd_mikan_search_result(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw);

  @protected
  List<ChannelInfo>? dco_decode_opt_list_channel_info(dynamic raw);

  @protected
  PersonCharacter dco_decode_person_character(dynamic raw);

  @protected
  PersonDetails dco_decode_person_details(dynamic raw);

  @protected
  PersonSubject dco_decode_person_subject(dynamic raw);

  @protected
  RankingAnime dco_decode_ranking_anime(dynamic raw);

  @protected
  (PlatformInt64, Value)
  dco_decode_record_i_64_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value(
    dynamic raw,
  );

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  SearchPlayResult dco_decode_search_play_result(dynamic raw);

  @protected
  SearchResultWithChannels dco_decode_search_result_with_channels(dynamic raw);

  @protected
  SearchStep dco_decode_search_step(dynamic raw);

  @protected
  SourceConfigUpdate dco_decode_source_config_update(dynamic raw);

  @protected
  SourceRuntimeOverride dco_decode_source_runtime_override(dynamic raw);

  @protected
  SourceSearchProgress dco_decode_source_search_progress(dynamic raw);

  @protected
  SourceState dco_decode_source_state(dynamic raw);

  @protected
  TorrentStats dco_decode_torrent_stats(dynamic raw);

  @protected
  TrackerInfo dco_decode_tracker_info(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Value
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    SseDeserializer deserializer,
  );

  @protected
  Value
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<PlatformInt64, Value>
  sse_decode_Map_i_64_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue_None(
    SseDeserializer deserializer,
  );

  @protected
  Value
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SearchPlayResult> sse_decode_StreamSink_search_play_result_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SearchResultWithChannels>
  sse_decode_StreamSink_search_result_with_channels_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SourceSearchProgress>
  sse_decode_StreamSink_source_search_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AnimeInfo sse_decode_anime_info(SseDeserializer deserializer);

  @protected
  ArchiveQuarter sse_decode_archive_quarter(SseDeserializer deserializer);

  @protected
  BangumiActor sse_decode_bangumi_actor(SseDeserializer deserializer);

  @protected
  BangumiCharacter sse_decode_bangumi_character(SseDeserializer deserializer);

  @protected
  BangumiComment sse_decode_bangumi_comment(SseDeserializer deserializer);

  @protected
  BangumiDataCacheStatus sse_decode_bangumi_data_cache_status(
    SseDeserializer deserializer,
  );

  @protected
  BangumiDataSiteEntry sse_decode_bangumi_data_site_entry(
    SseDeserializer deserializer,
  );

  @protected
  BangumiEpisode sse_decode_bangumi_episode(SseDeserializer deserializer);

  @protected
  BangumiEpisodeComment sse_decode_bangumi_episode_comment(
    SseDeserializer deserializer,
  );

  @protected
  BangumiImages sse_decode_bangumi_images(SseDeserializer deserializer);

  @protected
  BangumiPerson sse_decode_bangumi_person(SseDeserializer deserializer);

  @protected
  BangumiRelatedSubject sse_decode_bangumi_related_subject(
    SseDeserializer deserializer,
  );

  @protected
  BangumiTvEpisode sse_decode_bangumi_tv_episode(SseDeserializer deserializer);

  @protected
  BangumiUserCollectionEntry sse_decode_bangumi_user_collection_entry(
    SseDeserializer deserializer,
  );

  @protected
  BangumiUserInfo sse_decode_bangumi_user_info(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BangumiImages sse_decode_box_autoadd_bangumi_images(
    SseDeserializer deserializer,
  );

  @protected
  CaptchaConstraintOptions sse_decode_box_autoadd_captcha_constraint_options(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  MikanSearchResult sse_decode_box_autoadd_mikan_search_result(
    SseDeserializer deserializer,
  );

  @protected
  SourceConfigUpdate sse_decode_box_autoadd_source_config_update(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  CaptchaConstraintOptions sse_decode_captcha_constraint_options(
    SseDeserializer deserializer,
  );

  @protected
  ChannelInfo sse_decode_channel_info(SseDeserializer deserializer);

  @protected
  CharacterDetails sse_decode_character_details(SseDeserializer deserializer);

  @protected
  CharacterStat sse_decode_character_stat(SseDeserializer deserializer);

  @protected
  CharacterSubject sse_decode_character_subject(SseDeserializer deserializer);

  @protected
  CharacterSubjectPerson sse_decode_character_subject_person(
    SseDeserializer deserializer,
  );

  @protected
  Danmaku sse_decode_danmaku(SseDeserializer deserializer);

  @protected
  DanmakuAnime sse_decode_danmaku_anime(SseDeserializer deserializer);

  @protected
  DanmakuEpisode sse_decode_danmaku_episode(SseDeserializer deserializer);

  @protected
  DanmakuMatch sse_decode_danmaku_match(SseDeserializer deserializer);

  @protected
  DmhyResource sse_decode_dmhy_resource(SseDeserializer deserializer);

  @protected
  EpisodeInfo sse_decode_episode_info(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  InfoboxItem sse_decode_infobox_item(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AnimeInfo> sse_decode_list_anime_info(SseDeserializer deserializer);

  @protected
  List<ArchiveQuarter> sse_decode_list_archive_quarter(
    SseDeserializer deserializer,
  );

  @protected
  List<BangumiActor> sse_decode_list_bangumi_actor(
    SseDeserializer deserializer,
  );

  @protected
  List<BangumiCharacter> sse_decode_list_bangumi_character(
    SseDeserializer deserializer,
  );

  @protected
  List<BangumiComment> sse_decode_list_bangumi_comment(
    SseDeserializer deserializer,
  );

  @protected
  List<BangumiDataSiteEntry> sse_decode_list_bangumi_data_site_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<BangumiEpisode> sse_decode_list_bangumi_episode(
    SseDeserializer deserializer,
  );

  @protected
  List<BangumiEpisodeComment> sse_decode_list_bangumi_episode_comment(
    SseDeserializer deserializer,
  );

  @protected
  List<BangumiPerson> sse_decode_list_bangumi_person(
    SseDeserializer deserializer,
  );

  @protected
  List<BangumiRelatedSubject> sse_decode_list_bangumi_related_subject(
    SseDeserializer deserializer,
  );

  @protected
  List<BangumiTvEpisode> sse_decode_list_bangumi_tv_episode(
    SseDeserializer deserializer,
  );

  @protected
  List<BangumiUserCollectionEntry>
  sse_decode_list_bangumi_user_collection_entry(SseDeserializer deserializer);

  @protected
  List<ChannelInfo> sse_decode_list_channel_info(SseDeserializer deserializer);

  @protected
  List<CharacterSubject> sse_decode_list_character_subject(
    SseDeserializer deserializer,
  );

  @protected
  List<CharacterSubjectPerson> sse_decode_list_character_subject_person(
    SseDeserializer deserializer,
  );

  @protected
  List<Danmaku> sse_decode_list_danmaku(SseDeserializer deserializer);

  @protected
  List<DanmakuAnime> sse_decode_list_danmaku_anime(
    SseDeserializer deserializer,
  );

  @protected
  List<DanmakuEpisode> sse_decode_list_danmaku_episode(
    SseDeserializer deserializer,
  );

  @protected
  List<DanmakuMatch> sse_decode_list_danmaku_match(
    SseDeserializer deserializer,
  );

  @protected
  List<DmhyResource> sse_decode_list_dmhy_resource(
    SseDeserializer deserializer,
  );

  @protected
  List<EpisodeInfo> sse_decode_list_episode_info(SseDeserializer deserializer);

  @protected
  List<InfoboxItem> sse_decode_list_infobox_item(SseDeserializer deserializer);

  @protected
  List<MikanEpisodeResource> sse_decode_list_mikan_episode_resource(
    SseDeserializer deserializer,
  );

  @protected
  List<PersonCharacter> sse_decode_list_person_character(
    SseDeserializer deserializer,
  );

  @protected
  List<PersonSubject> sse_decode_list_person_subject(
    SseDeserializer deserializer,
  );

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RankingAnime> sse_decode_list_ranking_anime(
    SseDeserializer deserializer,
  );

  @protected
  List<(PlatformInt64, Value)>
  sse_decode_list_record_i_64_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<SearchPlayResult> sse_decode_list_search_play_result(
    SseDeserializer deserializer,
  );

  @protected
  List<SearchResultWithChannels> sse_decode_list_search_result_with_channels(
    SseDeserializer deserializer,
  );

  @protected
  List<SourceRuntimeOverride> sse_decode_list_source_runtime_override(
    SseDeserializer deserializer,
  );

  @protected
  List<SourceState> sse_decode_list_source_state(SseDeserializer deserializer);

  @protected
  List<TorrentStats> sse_decode_list_torrent_stats(
    SseDeserializer deserializer,
  );

  @protected
  List<TrackerInfo> sse_decode_list_tracker_info(SseDeserializer deserializer);

  @protected
  MikanEpisodeResource sse_decode_mikan_episode_resource(
    SseDeserializer deserializer,
  );

  @protected
  MikanSearchResult sse_decode_mikan_search_result(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, String>? sse_decode_opt_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BangumiImages? sse_decode_opt_box_autoadd_bangumi_images(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  MikanSearchResult? sse_decode_opt_box_autoadd_mikan_search_result(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  List<ChannelInfo>? sse_decode_opt_list_channel_info(
    SseDeserializer deserializer,
  );

  @protected
  PersonCharacter sse_decode_person_character(SseDeserializer deserializer);

  @protected
  PersonDetails sse_decode_person_details(SseDeserializer deserializer);

  @protected
  PersonSubject sse_decode_person_subject(SseDeserializer deserializer);

  @protected
  RankingAnime sse_decode_ranking_anime(SseDeserializer deserializer);

  @protected
  (PlatformInt64, Value)
  sse_decode_record_i_64_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  SearchPlayResult sse_decode_search_play_result(SseDeserializer deserializer);

  @protected
  SearchResultWithChannels sse_decode_search_result_with_channels(
    SseDeserializer deserializer,
  );

  @protected
  SearchStep sse_decode_search_step(SseDeserializer deserializer);

  @protected
  SourceConfigUpdate sse_decode_source_config_update(
    SseDeserializer deserializer,
  );

  @protected
  SourceRuntimeOverride sse_decode_source_runtime_override(
    SseDeserializer deserializer,
  );

  @protected
  SourceSearchProgress sse_decode_source_search_progress(
    SseDeserializer deserializer,
  );

  @protected
  SourceState sse_decode_source_state(SseDeserializer deserializer);

  @protected
  TorrentStats sse_decode_torrent_stats(SseDeserializer deserializer);

  @protected
  TrackerInfo sse_decode_tracker_info(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    Value self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    Value self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Map_i_64_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue_None(
    Map<PlatformInt64, Value> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    Value self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_search_play_result_Sse(
    RustStreamSink<SearchPlayResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_search_result_with_channels_Sse(
    RustStreamSink<SearchResultWithChannels> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_source_search_progress_Sse(
    RustStreamSink<SourceSearchProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_anime_info(AnimeInfo self, SseSerializer serializer);

  @protected
  void sse_encode_archive_quarter(
    ArchiveQuarter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bangumi_actor(BangumiActor self, SseSerializer serializer);

  @protected
  void sse_encode_bangumi_character(
    BangumiCharacter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bangumi_comment(
    BangumiComment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bangumi_data_cache_status(
    BangumiDataCacheStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bangumi_data_site_entry(
    BangumiDataSiteEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bangumi_episode(
    BangumiEpisode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bangumi_episode_comment(
    BangumiEpisodeComment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bangumi_images(BangumiImages self, SseSerializer serializer);

  @protected
  void sse_encode_bangumi_person(BangumiPerson self, SseSerializer serializer);

  @protected
  void sse_encode_bangumi_related_subject(
    BangumiRelatedSubject self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bangumi_tv_episode(
    BangumiTvEpisode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bangumi_user_collection_entry(
    BangumiUserCollectionEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bangumi_user_info(
    BangumiUserInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bangumi_images(
    BangumiImages self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_captcha_constraint_options(
    CaptchaConstraintOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_mikan_search_result(
    MikanSearchResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_source_config_update(
    SourceConfigUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_captcha_constraint_options(
    CaptchaConstraintOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_channel_info(ChannelInfo self, SseSerializer serializer);

  @protected
  void sse_encode_character_details(
    CharacterDetails self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_character_stat(CharacterStat self, SseSerializer serializer);

  @protected
  void sse_encode_character_subject(
    CharacterSubject self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_character_subject_person(
    CharacterSubjectPerson self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_danmaku(Danmaku self, SseSerializer serializer);

  @protected
  void sse_encode_danmaku_anime(DanmakuAnime self, SseSerializer serializer);

  @protected
  void sse_encode_danmaku_episode(
    DanmakuEpisode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_danmaku_match(DanmakuMatch self, SseSerializer serializer);

  @protected
  void sse_encode_dmhy_resource(DmhyResource self, SseSerializer serializer);

  @protected
  void sse_encode_episode_info(EpisodeInfo self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_infobox_item(InfoboxItem self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_anime_info(
    List<AnimeInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_archive_quarter(
    List<ArchiveQuarter> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bangumi_actor(
    List<BangumiActor> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bangumi_character(
    List<BangumiCharacter> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bangumi_comment(
    List<BangumiComment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bangumi_data_site_entry(
    List<BangumiDataSiteEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bangumi_episode(
    List<BangumiEpisode> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bangumi_episode_comment(
    List<BangumiEpisodeComment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bangumi_person(
    List<BangumiPerson> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bangumi_related_subject(
    List<BangumiRelatedSubject> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bangumi_tv_episode(
    List<BangumiTvEpisode> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bangumi_user_collection_entry(
    List<BangumiUserCollectionEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_channel_info(
    List<ChannelInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_character_subject(
    List<CharacterSubject> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_character_subject_person(
    List<CharacterSubjectPerson> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_danmaku(List<Danmaku> self, SseSerializer serializer);

  @protected
  void sse_encode_list_danmaku_anime(
    List<DanmakuAnime> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_danmaku_episode(
    List<DanmakuEpisode> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_danmaku_match(
    List<DanmakuMatch> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_dmhy_resource(
    List<DmhyResource> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_episode_info(
    List<EpisodeInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_infobox_item(
    List<InfoboxItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_mikan_episode_resource(
    List<MikanEpisodeResource> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_person_character(
    List<PersonCharacter> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_person_subject(
    List<PersonSubject> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ranking_anime(
    List<RankingAnime> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_list_record_i_64_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value(
    List<(PlatformInt64, Value)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_search_play_result(
    List<SearchPlayResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_search_result_with_channels(
    List<SearchResultWithChannels> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_source_runtime_override(
    List<SourceRuntimeOverride> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_source_state(
    List<SourceState> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_torrent_stats(
    List<TorrentStats> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tracker_info(
    List<TrackerInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mikan_episode_resource(
    MikanEpisodeResource self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mikan_search_result(
    MikanSearchResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_Map_String_String_None(
    Map<String, String>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bangumi_images(
    BangumiImages? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_mikan_search_result(
    MikanSearchResult? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_usize(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_channel_info(
    List<ChannelInfo>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_person_character(
    PersonCharacter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_person_details(PersonDetails self, SseSerializer serializer);

  @protected
  void sse_encode_person_subject(PersonSubject self, SseSerializer serializer);

  @protected
  void sse_encode_ranking_anime(RankingAnime self, SseSerializer serializer);

  @protected
  void
  sse_encode_record_i_64_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_value(
    (PlatformInt64, Value) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_search_play_result(
    SearchPlayResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_search_result_with_channels(
    SearchResultWithChannels self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_search_step(SearchStep self, SseSerializer serializer);

  @protected
  void sse_encode_source_config_update(
    SourceConfigUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_source_runtime_override(
    SourceRuntimeOverride self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_source_search_progress(
    SourceSearchProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_source_state(SourceState self, SseSerializer serializer);

  @protected
  void sse_encode_torrent_stats(TorrentStats self, SseSerializer serializer);

  @protected
  void sse_encode_tracker_info(TrackerInfo self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerValue(
    int ptr,
  );
}
