// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/bangumi.dart';
import 'api/crawler.dart';
import 'api/ranking.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 508172803;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<List<ArchiveQuarter>> crateApiCrawlerFetchArchiveList();

  Future<List<RankingAnime>> crateApiRankingFetchBangumiBrowser({
    required String sortType,
    required String year,
    required List<String> tags,
    required int page,
  });

  Future<List<BangumiCharacter>> crateApiBangumiFetchBangumiCharacters({
    required PlatformInt64 subjectId,
  });

  Future<List<BangumiComment>> crateApiBangumiFetchBangumiComments({
    required PlatformInt64 subjectId,
    required int page,
  });

  Future<List<BangumiEpisode>> crateApiBangumiFetchBangumiEpisodes({
    required PlatformInt64 subjectId,
  });

  Future<List<RankingAnime>> crateApiRankingFetchBangumiRanking({
    required String sortType,
    required int page,
  });

  Future<List<BangumiRelatedSubject>> crateApiBangumiFetchBangumiRelations({
    required PlatformInt64 subjectId,
  });

  Future<List<AnimeInfo>> crateApiCrawlerFetchExtraSubjects({
    required String yearQuarter,
    required List<String> existingIds,
  });

  Future<List<AnimeInfo>> crateApiCrawlerFetchScheduleBasic({
    required String yearQuarter,
  });

  Future<List<AnimeInfo>> crateApiCrawlerFillAnimeDetails({
    required List<AnimeInfo> animes,
  });

  Future<String> crateApiSimpleGetAllTorrentsInfo();

  Future<String> crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<String> crateApiSimpleStartTorrent({required String magnet});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<List<ArchiveQuarter>> crateApiCrawlerFetchArchiveList() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_archive_quarter,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCrawlerFetchArchiveListConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrawlerFetchArchiveListConstMeta =>
      const TaskConstMeta(debugName: "fetch_archive_list", argNames: []);

  @override
  Future<List<RankingAnime>> crateApiRankingFetchBangumiBrowser({
    required String sortType,
    required String year,
    required List<String> tags,
    required int page,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sortType, serializer);
          sse_encode_String(year, serializer);
          sse_encode_list_String(tags, serializer);
          sse_encode_i_32(page, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_ranking_anime,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRankingFetchBangumiBrowserConstMeta,
        argValues: [sortType, year, tags, page],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRankingFetchBangumiBrowserConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_bangumi_browser",
        argNames: ["sortType", "year", "tags", "page"],
      );

  @override
  Future<List<BangumiCharacter>> crateApiBangumiFetchBangumiCharacters({
    required PlatformInt64 subjectId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(subjectId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bangumi_character,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBangumiFetchBangumiCharactersConstMeta,
        argValues: [subjectId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBangumiFetchBangumiCharactersConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_bangumi_characters",
        argNames: ["subjectId"],
      );

  @override
  Future<List<BangumiComment>> crateApiBangumiFetchBangumiComments({
    required PlatformInt64 subjectId,
    required int page,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(subjectId, serializer);
          sse_encode_i_32(page, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bangumi_comment,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBangumiFetchBangumiCommentsConstMeta,
        argValues: [subjectId, page],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBangumiFetchBangumiCommentsConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_bangumi_comments",
        argNames: ["subjectId", "page"],
      );

  @override
  Future<List<BangumiEpisode>> crateApiBangumiFetchBangumiEpisodes({
    required PlatformInt64 subjectId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(subjectId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bangumi_episode,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBangumiFetchBangumiEpisodesConstMeta,
        argValues: [subjectId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBangumiFetchBangumiEpisodesConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_bangumi_episodes",
        argNames: ["subjectId"],
      );

  @override
  Future<List<RankingAnime>> crateApiRankingFetchBangumiRanking({
    required String sortType,
    required int page,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sortType, serializer);
          sse_encode_i_32(page, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_ranking_anime,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRankingFetchBangumiRankingConstMeta,
        argValues: [sortType, page],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRankingFetchBangumiRankingConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_bangumi_ranking",
        argNames: ["sortType", "page"],
      );

  @override
  Future<List<BangumiRelatedSubject>> crateApiBangumiFetchBangumiRelations({
    required PlatformInt64 subjectId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(subjectId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bangumi_related_subject,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBangumiFetchBangumiRelationsConstMeta,
        argValues: [subjectId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBangumiFetchBangumiRelationsConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_bangumi_relations",
        argNames: ["subjectId"],
      );

  @override
  Future<List<AnimeInfo>> crateApiCrawlerFetchExtraSubjects({
    required String yearQuarter,
    required List<String> existingIds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(yearQuarter, serializer);
          sse_encode_list_String(existingIds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_anime_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCrawlerFetchExtraSubjectsConstMeta,
        argValues: [yearQuarter, existingIds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrawlerFetchExtraSubjectsConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_extra_subjects",
        argNames: ["yearQuarter", "existingIds"],
      );

  @override
  Future<List<AnimeInfo>> crateApiCrawlerFetchScheduleBasic({
    required String yearQuarter,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(yearQuarter, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_anime_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCrawlerFetchScheduleBasicConstMeta,
        argValues: [yearQuarter],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrawlerFetchScheduleBasicConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_schedule_basic",
        argNames: ["yearQuarter"],
      );

  @override
  Future<List<AnimeInfo>> crateApiCrawlerFillAnimeDetails({
    required List<AnimeInfo> animes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_anime_info(animes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_anime_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCrawlerFillAnimeDetailsConstMeta,
        argValues: [animes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrawlerFillAnimeDetailsConstMeta =>
      const TaskConstMeta(
        debugName: "fill_anime_details",
        argNames: ["animes"],
      );

  @override
  Future<String> crateApiSimpleGetAllTorrentsInfo() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGetAllTorrentsInfoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetAllTorrentsInfoConstMeta =>
      const TaskConstMeta(debugName: "get_all_torrents_info", argNames: []);

  @override
  Future<String> crateApiSimpleGreet({required String name}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<String> crateApiSimpleStartTorrent({required String magnet}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(magnet, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleStartTorrentConstMeta,
        argValues: [magnet],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStartTorrentConstMeta =>
      const TaskConstMeta(debugName: "start_torrent", argNames: ["magnet"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AnimeInfo dco_decode_anime_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return AnimeInfo(
      title: dco_decode_String(arr[0]),
      subTitle: dco_decode_opt_String(arr[1]),
      bangumiId: dco_decode_opt_String(arr[2]),
      mikanId: dco_decode_opt_String(arr[3]),
      coverUrl: dco_decode_opt_String(arr[4]),
      siteUrl: dco_decode_opt_String(arr[5]),
      broadcastDay: dco_decode_opt_String(arr[6]),
      broadcastTime: dco_decode_opt_String(arr[7]),
      score: dco_decode_opt_box_autoadd_f_64(arr[8]),
      rank: dco_decode_opt_box_autoadd_i_32(arr[9]),
      tags: dco_decode_list_String(arr[10]),
      fullJson: dco_decode_opt_String(arr[11]),
    );
  }

  @protected
  ArchiveQuarter dco_decode_archive_quarter(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ArchiveQuarter(
      year: dco_decode_String(arr[0]),
      quarter: dco_decode_String(arr[1]),
      title: dco_decode_String(arr[2]),
    );
  }

  @protected
  BangumiActor dco_decode_bangumi_actor(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BangumiActor(
      id: dco_decode_i_64(arr[0]),
      name: dco_decode_String(arr[1]),
    );
  }

  @protected
  BangumiCharacter dco_decode_bangumi_character(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return BangumiCharacter(
      id: dco_decode_i_64(arr[0]),
      name: dco_decode_String(arr[1]),
      roleName: dco_decode_String(arr[2]),
      images: dco_decode_opt_box_autoadd_bangumi_images(arr[3]),
      actors: dco_decode_list_bangumi_actor(arr[4]),
    );
  }

  @protected
  BangumiComment dco_decode_bangumi_comment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return BangumiComment(
      userName: dco_decode_String(arr[0]),
      rate: dco_decode_opt_box_autoadd_i_32(arr[1]),
      content: dco_decode_String(arr[2]),
      time: dco_decode_String(arr[3]),
      avatar: dco_decode_String(arr[4]),
    );
  }

  @protected
  BangumiEpisode dco_decode_bangumi_episode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return BangumiEpisode(
      id: dco_decode_i_64(arr[0]),
      name: dco_decode_String(arr[1]),
      nameCn: dco_decode_String(arr[2]),
      description: dco_decode_String(arr[3]),
      airdate: dco_decode_String(arr[4]),
      duration: dco_decode_String(arr[5]),
      sort: dco_decode_f_64(arr[6]),
    );
  }

  @protected
  BangumiImages dco_decode_bangumi_images(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return BangumiImages(
      small: dco_decode_String(arr[0]),
      grid: dco_decode_String(arr[1]),
      large: dco_decode_String(arr[2]),
      medium: dco_decode_String(arr[3]),
      common: dco_decode_String(arr[4]),
    );
  }

  @protected
  BangumiRelatedSubject dco_decode_bangumi_related_subject(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return BangumiRelatedSubject(
      id: dco_decode_i_64(arr[0]),
      name: dco_decode_String(arr[1]),
      nameCn: dco_decode_String(arr[2]),
      relation: dco_decode_String(arr[3]),
      image: dco_decode_String(arr[4]),
    );
  }

  @protected
  BangumiImages dco_decode_box_autoadd_bangumi_images(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_bangumi_images(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AnimeInfo> dco_decode_list_anime_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_anime_info).toList();
  }

  @protected
  List<ArchiveQuarter> dco_decode_list_archive_quarter(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_archive_quarter).toList();
  }

  @protected
  List<BangumiActor> dco_decode_list_bangumi_actor(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bangumi_actor).toList();
  }

  @protected
  List<BangumiCharacter> dco_decode_list_bangumi_character(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bangumi_character).toList();
  }

  @protected
  List<BangumiComment> dco_decode_list_bangumi_comment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bangumi_comment).toList();
  }

  @protected
  List<BangumiEpisode> dco_decode_list_bangumi_episode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bangumi_episode).toList();
  }

  @protected
  List<BangumiRelatedSubject> dco_decode_list_bangumi_related_subject(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_bangumi_related_subject)
        .toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RankingAnime> dco_decode_list_ranking_anime(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ranking_anime).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BangumiImages? dco_decode_opt_box_autoadd_bangumi_images(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bangumi_images(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  RankingAnime dco_decode_ranking_anime(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return RankingAnime(
      title: dco_decode_String(arr[0]),
      bangumiId: dco_decode_String(arr[1]),
      coverUrl: dco_decode_String(arr[2]),
      score: dco_decode_opt_box_autoadd_f_64(arr[3]),
      rank: dco_decode_opt_box_autoadd_i_32(arr[4]),
      info: dco_decode_String(arr[5]),
      originalTitle: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AnimeInfo sse_decode_anime_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_subTitle = sse_decode_opt_String(deserializer);
    var var_bangumiId = sse_decode_opt_String(deserializer);
    var var_mikanId = sse_decode_opt_String(deserializer);
    var var_coverUrl = sse_decode_opt_String(deserializer);
    var var_siteUrl = sse_decode_opt_String(deserializer);
    var var_broadcastDay = sse_decode_opt_String(deserializer);
    var var_broadcastTime = sse_decode_opt_String(deserializer);
    var var_score = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_rank = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_fullJson = sse_decode_opt_String(deserializer);
    return AnimeInfo(
      title: var_title,
      subTitle: var_subTitle,
      bangumiId: var_bangumiId,
      mikanId: var_mikanId,
      coverUrl: var_coverUrl,
      siteUrl: var_siteUrl,
      broadcastDay: var_broadcastDay,
      broadcastTime: var_broadcastTime,
      score: var_score,
      rank: var_rank,
      tags: var_tags,
      fullJson: var_fullJson,
    );
  }

  @protected
  ArchiveQuarter sse_decode_archive_quarter(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_year = sse_decode_String(deserializer);
    var var_quarter = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    return ArchiveQuarter(
      year: var_year,
      quarter: var_quarter,
      title: var_title,
    );
  }

  @protected
  BangumiActor sse_decode_bangumi_actor(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    return BangumiActor(id: var_id, name: var_name);
  }

  @protected
  BangumiCharacter sse_decode_bangumi_character(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_roleName = sse_decode_String(deserializer);
    var var_images = sse_decode_opt_box_autoadd_bangumi_images(deserializer);
    var var_actors = sse_decode_list_bangumi_actor(deserializer);
    return BangumiCharacter(
      id: var_id,
      name: var_name,
      roleName: var_roleName,
      images: var_images,
      actors: var_actors,
    );
  }

  @protected
  BangumiComment sse_decode_bangumi_comment(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_userName = sse_decode_String(deserializer);
    var var_rate = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_time = sse_decode_String(deserializer);
    var var_avatar = sse_decode_String(deserializer);
    return BangumiComment(
      userName: var_userName,
      rate: var_rate,
      content: var_content,
      time: var_time,
      avatar: var_avatar,
    );
  }

  @protected
  BangumiEpisode sse_decode_bangumi_episode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_nameCn = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_airdate = sse_decode_String(deserializer);
    var var_duration = sse_decode_String(deserializer);
    var var_sort = sse_decode_f_64(deserializer);
    return BangumiEpisode(
      id: var_id,
      name: var_name,
      nameCn: var_nameCn,
      description: var_description,
      airdate: var_airdate,
      duration: var_duration,
      sort: var_sort,
    );
  }

  @protected
  BangumiImages sse_decode_bangumi_images(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_small = sse_decode_String(deserializer);
    var var_grid = sse_decode_String(deserializer);
    var var_large = sse_decode_String(deserializer);
    var var_medium = sse_decode_String(deserializer);
    var var_common = sse_decode_String(deserializer);
    return BangumiImages(
      small: var_small,
      grid: var_grid,
      large: var_large,
      medium: var_medium,
      common: var_common,
    );
  }

  @protected
  BangumiRelatedSubject sse_decode_bangumi_related_subject(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_nameCn = sse_decode_String(deserializer);
    var var_relation = sse_decode_String(deserializer);
    var var_image = sse_decode_String(deserializer);
    return BangumiRelatedSubject(
      id: var_id,
      name: var_name,
      nameCn: var_nameCn,
      relation: var_relation,
      image: var_image,
    );
  }

  @protected
  BangumiImages sse_decode_box_autoadd_bangumi_images(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bangumi_images(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AnimeInfo> sse_decode_list_anime_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AnimeInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_anime_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<ArchiveQuarter> sse_decode_list_archive_quarter(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ArchiveQuarter>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_archive_quarter(deserializer));
    }
    return ans_;
  }

  @protected
  List<BangumiActor> sse_decode_list_bangumi_actor(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BangumiActor>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bangumi_actor(deserializer));
    }
    return ans_;
  }

  @protected
  List<BangumiCharacter> sse_decode_list_bangumi_character(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BangumiCharacter>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bangumi_character(deserializer));
    }
    return ans_;
  }

  @protected
  List<BangumiComment> sse_decode_list_bangumi_comment(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BangumiComment>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bangumi_comment(deserializer));
    }
    return ans_;
  }

  @protected
  List<BangumiEpisode> sse_decode_list_bangumi_episode(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BangumiEpisode>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bangumi_episode(deserializer));
    }
    return ans_;
  }

  @protected
  List<BangumiRelatedSubject> sse_decode_list_bangumi_related_subject(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BangumiRelatedSubject>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bangumi_related_subject(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RankingAnime> sse_decode_list_ranking_anime(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RankingAnime>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ranking_anime(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BangumiImages? sse_decode_opt_box_autoadd_bangumi_images(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bangumi_images(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RankingAnime sse_decode_ranking_anime(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_bangumiId = sse_decode_String(deserializer);
    var var_coverUrl = sse_decode_String(deserializer);
    var var_score = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_rank = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_info = sse_decode_String(deserializer);
    var var_originalTitle = sse_decode_opt_String(deserializer);
    return RankingAnime(
      title: var_title,
      bangumiId: var_bangumiId,
      coverUrl: var_coverUrl,
      score: var_score,
      rank: var_rank,
      info: var_info,
      originalTitle: var_originalTitle,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_anime_info(AnimeInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.subTitle, serializer);
    sse_encode_opt_String(self.bangumiId, serializer);
    sse_encode_opt_String(self.mikanId, serializer);
    sse_encode_opt_String(self.coverUrl, serializer);
    sse_encode_opt_String(self.siteUrl, serializer);
    sse_encode_opt_String(self.broadcastDay, serializer);
    sse_encode_opt_String(self.broadcastTime, serializer);
    sse_encode_opt_box_autoadd_f_64(self.score, serializer);
    sse_encode_opt_box_autoadd_i_32(self.rank, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_opt_String(self.fullJson, serializer);
  }

  @protected
  void sse_encode_archive_quarter(
    ArchiveQuarter self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.year, serializer);
    sse_encode_String(self.quarter, serializer);
    sse_encode_String(self.title, serializer);
  }

  @protected
  void sse_encode_bangumi_actor(BangumiActor self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.name, serializer);
  }

  @protected
  void sse_encode_bangumi_character(
    BangumiCharacter self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.roleName, serializer);
    sse_encode_opt_box_autoadd_bangumi_images(self.images, serializer);
    sse_encode_list_bangumi_actor(self.actors, serializer);
  }

  @protected
  void sse_encode_bangumi_comment(
    BangumiComment self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.userName, serializer);
    sse_encode_opt_box_autoadd_i_32(self.rate, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_String(self.time, serializer);
    sse_encode_String(self.avatar, serializer);
  }

  @protected
  void sse_encode_bangumi_episode(
    BangumiEpisode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.nameCn, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_String(self.airdate, serializer);
    sse_encode_String(self.duration, serializer);
    sse_encode_f_64(self.sort, serializer);
  }

  @protected
  void sse_encode_bangumi_images(BangumiImages self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.small, serializer);
    sse_encode_String(self.grid, serializer);
    sse_encode_String(self.large, serializer);
    sse_encode_String(self.medium, serializer);
    sse_encode_String(self.common, serializer);
  }

  @protected
  void sse_encode_bangumi_related_subject(
    BangumiRelatedSubject self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.nameCn, serializer);
    sse_encode_String(self.relation, serializer);
    sse_encode_String(self.image, serializer);
  }

  @protected
  void sse_encode_box_autoadd_bangumi_images(
    BangumiImages self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bangumi_images(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_anime_info(
    List<AnimeInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_anime_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_archive_quarter(
    List<ArchiveQuarter> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_archive_quarter(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bangumi_actor(
    List<BangumiActor> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bangumi_actor(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bangumi_character(
    List<BangumiCharacter> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bangumi_character(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bangumi_comment(
    List<BangumiComment> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bangumi_comment(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bangumi_episode(
    List<BangumiEpisode> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bangumi_episode(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bangumi_related_subject(
    List<BangumiRelatedSubject> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bangumi_related_subject(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_ranking_anime(
    List<RankingAnime> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ranking_anime(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bangumi_images(
    BangumiImages? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bangumi_images(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_ranking_anime(RankingAnime self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.bangumiId, serializer);
    sse_encode_String(self.coverUrl, serializer);
    sse_encode_opt_box_autoadd_f_64(self.score, serializer);
    sse_encode_opt_box_autoadd_i_32(self.rank, serializer);
    sse_encode_String(self.info, serializer);
    sse_encode_opt_String(self.originalTitle, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
