// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/bangumi.dart';
import 'api/config.dart';
import 'api/crawler.dart';
import 'api/dmhy.dart';
import 'api/generic_scraper.dart';
import 'api/mikan.dart';
import 'api/network.dart';
import 'api/ranking.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<SearchPlayResult> dco_decode_StreamSink_search_play_result_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<SourceSearchProgress>
  dco_decode_StreamSink_source_search_progress_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AnimeInfo dco_decode_anime_info(dynamic raw);

  @protected
  ArchiveQuarter dco_decode_archive_quarter(dynamic raw);

  @protected
  BangumiActor dco_decode_bangumi_actor(dynamic raw);

  @protected
  BangumiCharacter dco_decode_bangumi_character(dynamic raw);

  @protected
  BangumiComment dco_decode_bangumi_comment(dynamic raw);

  @protected
  BangumiEpisode dco_decode_bangumi_episode(dynamic raw);

  @protected
  BangumiEpisodeComment dco_decode_bangumi_episode_comment(dynamic raw);

  @protected
  BangumiImages dco_decode_bangumi_images(dynamic raw);

  @protected
  BangumiRelatedSubject dco_decode_bangumi_related_subject(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BangumiImages dco_decode_box_autoadd_bangumi_images(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  MikanSearchResult dco_decode_box_autoadd_mikan_search_result(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  DmhyResource dco_decode_dmhy_resource(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AnimeInfo> dco_decode_list_anime_info(dynamic raw);

  @protected
  List<ArchiveQuarter> dco_decode_list_archive_quarter(dynamic raw);

  @protected
  List<BangumiActor> dco_decode_list_bangumi_actor(dynamic raw);

  @protected
  List<BangumiCharacter> dco_decode_list_bangumi_character(dynamic raw);

  @protected
  List<BangumiComment> dco_decode_list_bangumi_comment(dynamic raw);

  @protected
  List<BangumiEpisode> dco_decode_list_bangumi_episode(dynamic raw);

  @protected
  List<BangumiEpisodeComment> dco_decode_list_bangumi_episode_comment(
    dynamic raw,
  );

  @protected
  List<BangumiRelatedSubject> dco_decode_list_bangumi_related_subject(
    dynamic raw,
  );

  @protected
  List<DmhyResource> dco_decode_list_dmhy_resource(dynamic raw);

  @protected
  List<MikanEpisodeResource> dco_decode_list_mikan_episode_resource(
    dynamic raw,
  );

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RankingAnime> dco_decode_list_ranking_anime(dynamic raw);

  @protected
  List<SearchPlayResult> dco_decode_list_search_play_result(dynamic raw);

  @protected
  List<SourceState> dco_decode_list_source_state(dynamic raw);

  @protected
  List<TorrentStats> dco_decode_list_torrent_stats(dynamic raw);

  @protected
  List<TrackerInfo> dco_decode_list_tracker_info(dynamic raw);

  @protected
  MikanEpisodeResource dco_decode_mikan_episode_resource(dynamic raw);

  @protected
  MikanSearchResult dco_decode_mikan_search_result(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BangumiImages? dco_decode_opt_box_autoadd_bangumi_images(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  MikanSearchResult? dco_decode_opt_box_autoadd_mikan_search_result(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  RankingAnime dco_decode_ranking_anime(dynamic raw);

  @protected
  SearchPlayResult dco_decode_search_play_result(dynamic raw);

  @protected
  SearchStep dco_decode_search_step(dynamic raw);

  @protected
  SourceSearchProgress dco_decode_source_search_progress(dynamic raw);

  @protected
  SourceState dco_decode_source_state(dynamic raw);

  @protected
  TorrentStats dco_decode_torrent_stats(dynamic raw);

  @protected
  TrackerInfo dco_decode_tracker_info(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<SearchPlayResult> sse_decode_StreamSink_search_play_result_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SourceSearchProgress>
  sse_decode_StreamSink_source_search_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AnimeInfo sse_decode_anime_info(SseDeserializer deserializer);

  @protected
  ArchiveQuarter sse_decode_archive_quarter(SseDeserializer deserializer);

  @protected
  BangumiActor sse_decode_bangumi_actor(SseDeserializer deserializer);

  @protected
  BangumiCharacter sse_decode_bangumi_character(SseDeserializer deserializer);

  @protected
  BangumiComment sse_decode_bangumi_comment(SseDeserializer deserializer);

  @protected
  BangumiEpisode sse_decode_bangumi_episode(SseDeserializer deserializer);

  @protected
  BangumiEpisodeComment sse_decode_bangumi_episode_comment(
    SseDeserializer deserializer,
  );

  @protected
  BangumiImages sse_decode_bangumi_images(SseDeserializer deserializer);

  @protected
  BangumiRelatedSubject sse_decode_bangumi_related_subject(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BangumiImages sse_decode_box_autoadd_bangumi_images(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  MikanSearchResult sse_decode_box_autoadd_mikan_search_result(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  DmhyResource sse_decode_dmhy_resource(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AnimeInfo> sse_decode_list_anime_info(SseDeserializer deserializer);

  @protected
  List<ArchiveQuarter> sse_decode_list_archive_quarter(
    SseDeserializer deserializer,
  );

  @protected
  List<BangumiActor> sse_decode_list_bangumi_actor(
    SseDeserializer deserializer,
  );

  @protected
  List<BangumiCharacter> sse_decode_list_bangumi_character(
    SseDeserializer deserializer,
  );

  @protected
  List<BangumiComment> sse_decode_list_bangumi_comment(
    SseDeserializer deserializer,
  );

  @protected
  List<BangumiEpisode> sse_decode_list_bangumi_episode(
    SseDeserializer deserializer,
  );

  @protected
  List<BangumiEpisodeComment> sse_decode_list_bangumi_episode_comment(
    SseDeserializer deserializer,
  );

  @protected
  List<BangumiRelatedSubject> sse_decode_list_bangumi_related_subject(
    SseDeserializer deserializer,
  );

  @protected
  List<DmhyResource> sse_decode_list_dmhy_resource(
    SseDeserializer deserializer,
  );

  @protected
  List<MikanEpisodeResource> sse_decode_list_mikan_episode_resource(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RankingAnime> sse_decode_list_ranking_anime(
    SseDeserializer deserializer,
  );

  @protected
  List<SearchPlayResult> sse_decode_list_search_play_result(
    SseDeserializer deserializer,
  );

  @protected
  List<SourceState> sse_decode_list_source_state(SseDeserializer deserializer);

  @protected
  List<TorrentStats> sse_decode_list_torrent_stats(
    SseDeserializer deserializer,
  );

  @protected
  List<TrackerInfo> sse_decode_list_tracker_info(SseDeserializer deserializer);

  @protected
  MikanEpisodeResource sse_decode_mikan_episode_resource(
    SseDeserializer deserializer,
  );

  @protected
  MikanSearchResult sse_decode_mikan_search_result(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BangumiImages? sse_decode_opt_box_autoadd_bangumi_images(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  MikanSearchResult? sse_decode_opt_box_autoadd_mikan_search_result(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  RankingAnime sse_decode_ranking_anime(SseDeserializer deserializer);

  @protected
  SearchPlayResult sse_decode_search_play_result(SseDeserializer deserializer);

  @protected
  SearchStep sse_decode_search_step(SseDeserializer deserializer);

  @protected
  SourceSearchProgress sse_decode_source_search_progress(
    SseDeserializer deserializer,
  );

  @protected
  SourceState sse_decode_source_state(SseDeserializer deserializer);

  @protected
  TorrentStats sse_decode_torrent_stats(SseDeserializer deserializer);

  @protected
  TrackerInfo sse_decode_tracker_info(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_search_play_result_Sse(
    RustStreamSink<SearchPlayResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_source_search_progress_Sse(
    RustStreamSink<SourceSearchProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_anime_info(AnimeInfo self, SseSerializer serializer);

  @protected
  void sse_encode_archive_quarter(
    ArchiveQuarter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bangumi_actor(BangumiActor self, SseSerializer serializer);

  @protected
  void sse_encode_bangumi_character(
    BangumiCharacter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bangumi_comment(
    BangumiComment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bangumi_episode(
    BangumiEpisode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bangumi_episode_comment(
    BangumiEpisodeComment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bangumi_images(BangumiImages self, SseSerializer serializer);

  @protected
  void sse_encode_bangumi_related_subject(
    BangumiRelatedSubject self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bangumi_images(
    BangumiImages self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_mikan_search_result(
    MikanSearchResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_dmhy_resource(DmhyResource self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_anime_info(
    List<AnimeInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_archive_quarter(
    List<ArchiveQuarter> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bangumi_actor(
    List<BangumiActor> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bangumi_character(
    List<BangumiCharacter> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bangumi_comment(
    List<BangumiComment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bangumi_episode(
    List<BangumiEpisode> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bangumi_episode_comment(
    List<BangumiEpisodeComment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bangumi_related_subject(
    List<BangumiRelatedSubject> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_dmhy_resource(
    List<DmhyResource> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_mikan_episode_resource(
    List<MikanEpisodeResource> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ranking_anime(
    List<RankingAnime> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_search_play_result(
    List<SearchPlayResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_source_state(
    List<SourceState> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_torrent_stats(
    List<TorrentStats> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tracker_info(
    List<TrackerInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mikan_episode_resource(
    MikanEpisodeResource self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mikan_search_result(
    MikanSearchResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bangumi_images(
    BangumiImages? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_mikan_search_result(
    MikanSearchResult? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_ranking_anime(RankingAnime self, SseSerializer serializer);

  @protected
  void sse_encode_search_play_result(
    SearchPlayResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_search_step(SearchStep self, SseSerializer serializer);

  @protected
  void sse_encode_source_search_progress(
    SourceSearchProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_source_state(SourceState self, SseSerializer serializer);

  @protected
  void sse_encode_torrent_stats(TorrentStats self, SseSerializer serializer);

  @protected
  void sse_encode_tracker_info(TrackerInfo self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
