// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/bangumi.dart';
import 'api/config.dart';
import 'api/crawler.dart';
import 'api/dmhy.dart';
import 'api/generic_scraper.dart';
import 'api/mikan.dart';
import 'api/network.dart';
import 'api/ranking.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1425254932;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<List<ArchiveQuarter>> crateApiCrawlerFetchArchiveList();

  Future<List<RankingAnime>> crateApiRankingFetchBangumiBrowser({
    required String sortType,
    required String year,
    required List<String> tags,
    required int page,
  });

  Future<List<BangumiCharacter>> crateApiBangumiFetchBangumiCharacters({
    required PlatformInt64 subjectId,
  });

  Future<List<BangumiComment>> crateApiBangumiFetchBangumiComments({
    required PlatformInt64 subjectId,
    required int page,
  });

  Future<List<BangumiEpisodeComment>>
  crateApiBangumiFetchBangumiEpisodeComments({
    required PlatformInt64 episodeId,
  });

  Future<List<BangumiEpisode>> crateApiBangumiFetchBangumiEpisodes({
    required PlatformInt64 subjectId,
  });

  Future<List<RankingAnime>> crateApiRankingFetchBangumiRanking({
    required String sortType,
    required int page,
  });

  Future<List<BangumiRelatedSubject>> crateApiBangumiFetchBangumiRelations({
    required PlatformInt64 subjectId,
  });

  Future<List<DmhyResource>> crateApiDmhyFetchDmhyResources({
    required String subjectId,
    required int targetEpisode,
  });

  Future<List<AnimeInfo>> crateApiCrawlerFetchExtraSubjects({
    required String yearQuarter,
    required List<String> existingIds,
  });

  Future<List<AnimeInfo>> crateApiCrawlerFetchScheduleBasic({
    required String yearQuarter,
  });

  Future<List<AnimeInfo>> crateApiCrawlerFillAnimeDetails({
    required List<AnimeInfo> animes,
  });

  Future<String> crateApiGenericScraperGenericSearchAndPlay({
    required String animeName,
  });

  Future<List<SearchPlayResult>> crateApiGenericScraperGenericSearchPlayPages({
    required String animeName,
  });

  Stream<SearchPlayResult> crateApiGenericScraperGenericSearchPlayPagesStream({
    required String animeName,
  });

  Future<String> crateApiSimpleGetAllTorrentsInfo();

  Future<String> crateApiConfigGetBangumiApiUrl();

  Future<String> crateApiConfigGetBangumiUrl();

  Future<String> crateApiConfigGetBgmlistUrl();

  Future<List<MikanEpisodeResource>> crateApiMikanGetMikanResources({
    required String mikanId,
    required int currentEpisodeSort,
  });

  Future<String> crateApiConfigGetMikanUrl();

  Future<String> crateApiConfigGetPlaybackSubUrl();

  Future<String?> crateApiNetworkGetSystemProxy();

  Future<List<TorrentStats>> crateApiSimpleGetTorrentStats();

  Future<List<TrackerInfo>> crateApiSimpleGetTrackerInfo({
    required String infoHash,
  });

  Future<String> crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<String> crateApiSimplePreloadPlaybackSourceConfig();

  Future<void> crateApiGenericScraperPreloadPlaybackSources();

  Future<MikanSearchResult?> crateApiMikanSearchMikanAnime({
    required String nameCn,
  });

  Future<String> crateApiSimpleStartTorrent({required String magnet});

  Future<bool> crateApiSimpleStopTorrent({
    required String infoHash,
    required bool deleteFiles,
  });

  Future<void> crateApiConfigUpdateConfig({
    required String bgm,
    required String bangumi,
    required String mikan,
    required String playbackSub,
  });

  Future<void> crateApiSimpleUpdateConfig({
    required String bgm,
    required String bangumi,
    required String mikan,
    required String playbackSub,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<List<ArchiveQuarter>> crateApiCrawlerFetchArchiveList() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_archive_quarter,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCrawlerFetchArchiveListConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrawlerFetchArchiveListConstMeta =>
      const TaskConstMeta(debugName: "fetch_archive_list", argNames: []);

  @override
  Future<List<RankingAnime>> crateApiRankingFetchBangumiBrowser({
    required String sortType,
    required String year,
    required List<String> tags,
    required int page,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sortType, serializer);
          sse_encode_String(year, serializer);
          sse_encode_list_String(tags, serializer);
          sse_encode_i_32(page, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_ranking_anime,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRankingFetchBangumiBrowserConstMeta,
        argValues: [sortType, year, tags, page],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRankingFetchBangumiBrowserConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_bangumi_browser",
        argNames: ["sortType", "year", "tags", "page"],
      );

  @override
  Future<List<BangumiCharacter>> crateApiBangumiFetchBangumiCharacters({
    required PlatformInt64 subjectId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(subjectId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bangumi_character,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBangumiFetchBangumiCharactersConstMeta,
        argValues: [subjectId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBangumiFetchBangumiCharactersConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_bangumi_characters",
        argNames: ["subjectId"],
      );

  @override
  Future<List<BangumiComment>> crateApiBangumiFetchBangumiComments({
    required PlatformInt64 subjectId,
    required int page,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(subjectId, serializer);
          sse_encode_i_32(page, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bangumi_comment,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBangumiFetchBangumiCommentsConstMeta,
        argValues: [subjectId, page],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBangumiFetchBangumiCommentsConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_bangumi_comments",
        argNames: ["subjectId", "page"],
      );

  @override
  Future<List<BangumiEpisodeComment>>
  crateApiBangumiFetchBangumiEpisodeComments({
    required PlatformInt64 episodeId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(episodeId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bangumi_episode_comment,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBangumiFetchBangumiEpisodeCommentsConstMeta,
        argValues: [episodeId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBangumiFetchBangumiEpisodeCommentsConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_bangumi_episode_comments",
        argNames: ["episodeId"],
      );

  @override
  Future<List<BangumiEpisode>> crateApiBangumiFetchBangumiEpisodes({
    required PlatformInt64 subjectId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(subjectId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bangumi_episode,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBangumiFetchBangumiEpisodesConstMeta,
        argValues: [subjectId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBangumiFetchBangumiEpisodesConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_bangumi_episodes",
        argNames: ["subjectId"],
      );

  @override
  Future<List<RankingAnime>> crateApiRankingFetchBangumiRanking({
    required String sortType,
    required int page,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sortType, serializer);
          sse_encode_i_32(page, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_ranking_anime,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRankingFetchBangumiRankingConstMeta,
        argValues: [sortType, page],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRankingFetchBangumiRankingConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_bangumi_ranking",
        argNames: ["sortType", "page"],
      );

  @override
  Future<List<BangumiRelatedSubject>> crateApiBangumiFetchBangumiRelations({
    required PlatformInt64 subjectId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(subjectId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bangumi_related_subject,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBangumiFetchBangumiRelationsConstMeta,
        argValues: [subjectId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBangumiFetchBangumiRelationsConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_bangumi_relations",
        argNames: ["subjectId"],
      );

  @override
  Future<List<DmhyResource>> crateApiDmhyFetchDmhyResources({
    required String subjectId,
    required int targetEpisode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(subjectId, serializer);
          sse_encode_i_32(targetEpisode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_dmhy_resource,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDmhyFetchDmhyResourcesConstMeta,
        argValues: [subjectId, targetEpisode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDmhyFetchDmhyResourcesConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_dmhy_resources",
        argNames: ["subjectId", "targetEpisode"],
      );

  @override
  Future<List<AnimeInfo>> crateApiCrawlerFetchExtraSubjects({
    required String yearQuarter,
    required List<String> existingIds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(yearQuarter, serializer);
          sse_encode_list_String(existingIds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_anime_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCrawlerFetchExtraSubjectsConstMeta,
        argValues: [yearQuarter, existingIds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrawlerFetchExtraSubjectsConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_extra_subjects",
        argNames: ["yearQuarter", "existingIds"],
      );

  @override
  Future<List<AnimeInfo>> crateApiCrawlerFetchScheduleBasic({
    required String yearQuarter,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(yearQuarter, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_anime_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCrawlerFetchScheduleBasicConstMeta,
        argValues: [yearQuarter],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrawlerFetchScheduleBasicConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_schedule_basic",
        argNames: ["yearQuarter"],
      );

  @override
  Future<List<AnimeInfo>> crateApiCrawlerFillAnimeDetails({
    required List<AnimeInfo> animes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_anime_info(animes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_anime_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCrawlerFillAnimeDetailsConstMeta,
        argValues: [animes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCrawlerFillAnimeDetailsConstMeta =>
      const TaskConstMeta(
        debugName: "fill_anime_details",
        argNames: ["animes"],
      );

  @override
  Future<String> crateApiGenericScraperGenericSearchAndPlay({
    required String animeName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(animeName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGenericScraperGenericSearchAndPlayConstMeta,
        argValues: [animeName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenericScraperGenericSearchAndPlayConstMeta =>
      const TaskConstMeta(
        debugName: "generic_search_and_play",
        argNames: ["animeName"],
      );

  @override
  Future<List<SearchPlayResult>> crateApiGenericScraperGenericSearchPlayPages({
    required String animeName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(animeName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_search_play_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGenericScraperGenericSearchPlayPagesConstMeta,
        argValues: [animeName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenericScraperGenericSearchPlayPagesConstMeta =>
      const TaskConstMeta(
        debugName: "generic_search_play_pages",
        argNames: ["animeName"],
      );

  @override
  Stream<SearchPlayResult> crateApiGenericScraperGenericSearchPlayPagesStream({
    required String animeName,
  }) {
    final sink = RustStreamSink<SearchPlayResult>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(animeName, serializer);
            sse_encode_StreamSink_search_play_result_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 15,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta:
              kCrateApiGenericScraperGenericSearchPlayPagesStreamConstMeta,
          argValues: [animeName, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta
  get kCrateApiGenericScraperGenericSearchPlayPagesStreamConstMeta =>
      const TaskConstMeta(
        debugName: "generic_search_play_pages_stream",
        argNames: ["animeName", "sink"],
      );

  @override
  Future<String> crateApiSimpleGetAllTorrentsInfo() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGetAllTorrentsInfoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetAllTorrentsInfoConstMeta =>
      const TaskConstMeta(debugName: "get_all_torrents_info", argNames: []);

  @override
  Future<String> crateApiConfigGetBangumiApiUrl() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConfigGetBangumiApiUrlConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigGetBangumiApiUrlConstMeta =>
      const TaskConstMeta(debugName: "get_bangumi_api_url", argNames: []);

  @override
  Future<String> crateApiConfigGetBangumiUrl() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConfigGetBangumiUrlConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigGetBangumiUrlConstMeta =>
      const TaskConstMeta(debugName: "get_bangumi_url", argNames: []);

  @override
  Future<String> crateApiConfigGetBgmlistUrl() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConfigGetBgmlistUrlConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigGetBgmlistUrlConstMeta =>
      const TaskConstMeta(debugName: "get_bgmlist_url", argNames: []);

  @override
  Future<List<MikanEpisodeResource>> crateApiMikanGetMikanResources({
    required String mikanId,
    required int currentEpisodeSort,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mikanId, serializer);
          sse_encode_i_32(currentEpisodeSort, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_mikan_episode_resource,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMikanGetMikanResourcesConstMeta,
        argValues: [mikanId, currentEpisodeSort],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMikanGetMikanResourcesConstMeta =>
      const TaskConstMeta(
        debugName: "get_mikan_resources",
        argNames: ["mikanId", "currentEpisodeSort"],
      );

  @override
  Future<String> crateApiConfigGetMikanUrl() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConfigGetMikanUrlConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigGetMikanUrlConstMeta =>
      const TaskConstMeta(debugName: "get_mikan_url", argNames: []);

  @override
  Future<String> crateApiConfigGetPlaybackSubUrl() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConfigGetPlaybackSubUrlConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigGetPlaybackSubUrlConstMeta =>
      const TaskConstMeta(debugName: "get_playback_sub_url", argNames: []);

  @override
  Future<String?> crateApiNetworkGetSystemProxy() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkGetSystemProxyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkGetSystemProxyConstMeta =>
      const TaskConstMeta(debugName: "get_system_proxy", argNames: []);

  @override
  Future<List<TorrentStats>> crateApiSimpleGetTorrentStats() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_torrent_stats,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGetTorrentStatsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetTorrentStatsConstMeta =>
      const TaskConstMeta(debugName: "get_torrent_stats", argNames: []);

  @override
  Future<List<TrackerInfo>> crateApiSimpleGetTrackerInfo({
    required String infoHash,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(infoHash, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_tracker_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGetTrackerInfoConstMeta,
        argValues: [infoHash],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetTrackerInfoConstMeta =>
      const TaskConstMeta(
        debugName: "get_tracker_info",
        argNames: ["infoHash"],
      );

  @override
  Future<String> crateApiSimpleGreet({required String name}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<String> crateApiSimplePreloadPlaybackSourceConfig() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimplePreloadPlaybackSourceConfigConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimplePreloadPlaybackSourceConfigConstMeta =>
      const TaskConstMeta(
        debugName: "preload_playback_source_config",
        argNames: [],
      );

  @override
  Future<void> crateApiGenericScraperPreloadPlaybackSources() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGenericScraperPreloadPlaybackSourcesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenericScraperPreloadPlaybackSourcesConstMeta =>
      const TaskConstMeta(debugName: "preload_playback_sources", argNames: []);

  @override
  Future<MikanSearchResult?> crateApiMikanSearchMikanAnime({
    required String nameCn,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nameCn, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_mikan_search_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMikanSearchMikanAnimeConstMeta,
        argValues: [nameCn],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMikanSearchMikanAnimeConstMeta =>
      const TaskConstMeta(
        debugName: "search_mikan_anime",
        argNames: ["nameCn"],
      );

  @override
  Future<String> crateApiSimpleStartTorrent({required String magnet}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(magnet, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleStartTorrentConstMeta,
        argValues: [magnet],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStartTorrentConstMeta =>
      const TaskConstMeta(debugName: "start_torrent", argNames: ["magnet"]);

  @override
  Future<bool> crateApiSimpleStopTorrent({
    required String infoHash,
    required bool deleteFiles,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(infoHash, serializer);
          sse_encode_bool(deleteFiles, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleStopTorrentConstMeta,
        argValues: [infoHash, deleteFiles],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStopTorrentConstMeta => const TaskConstMeta(
    debugName: "stop_torrent",
    argNames: ["infoHash", "deleteFiles"],
  );

  @override
  Future<void> crateApiConfigUpdateConfig({
    required String bgm,
    required String bangumi,
    required String mikan,
    required String playbackSub,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(bgm, serializer);
          sse_encode_String(bangumi, serializer);
          sse_encode_String(mikan, serializer);
          sse_encode_String(playbackSub, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConfigUpdateConfigConstMeta,
        argValues: [bgm, bangumi, mikan, playbackSub],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigUpdateConfigConstMeta => const TaskConstMeta(
    debugName: "update_config",
    argNames: ["bgm", "bangumi", "mikan", "playbackSub"],
  );

  @override
  Future<void> crateApiSimpleUpdateConfig({
    required String bgm,
    required String bangumi,
    required String mikan,
    required String playbackSub,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(bgm, serializer);
          sse_encode_String(bangumi, serializer);
          sse_encode_String(mikan, serializer);
          sse_encode_String(playbackSub, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleUpdateConfigConstMeta,
        argValues: [bgm, bangumi, mikan, playbackSub],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleUpdateConfigConstMeta => const TaskConstMeta(
    debugName: "update_config",
    argNames: ["bgm", "bangumi", "mikan", "playbackSub"],
  );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<SearchPlayResult> dco_decode_StreamSink_search_play_result_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AnimeInfo dco_decode_anime_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return AnimeInfo(
      title: dco_decode_String(arr[0]),
      subTitle: dco_decode_opt_String(arr[1]),
      bangumiId: dco_decode_opt_String(arr[2]),
      mikanId: dco_decode_opt_String(arr[3]),
      coverUrl: dco_decode_opt_String(arr[4]),
      siteUrl: dco_decode_opt_String(arr[5]),
      broadcastDay: dco_decode_opt_String(arr[6]),
      broadcastTime: dco_decode_opt_String(arr[7]),
      score: dco_decode_opt_box_autoadd_f_64(arr[8]),
      rank: dco_decode_opt_box_autoadd_i_32(arr[9]),
      tags: dco_decode_list_String(arr[10]),
      fullJson: dco_decode_opt_String(arr[11]),
    );
  }

  @protected
  ArchiveQuarter dco_decode_archive_quarter(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ArchiveQuarter(
      year: dco_decode_String(arr[0]),
      quarter: dco_decode_String(arr[1]),
      title: dco_decode_String(arr[2]),
    );
  }

  @protected
  BangumiActor dco_decode_bangumi_actor(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BangumiActor(
      id: dco_decode_i_64(arr[0]),
      name: dco_decode_String(arr[1]),
    );
  }

  @protected
  BangumiCharacter dco_decode_bangumi_character(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return BangumiCharacter(
      id: dco_decode_i_64(arr[0]),
      name: dco_decode_String(arr[1]),
      roleName: dco_decode_String(arr[2]),
      images: dco_decode_opt_box_autoadd_bangumi_images(arr[3]),
      actors: dco_decode_list_bangumi_actor(arr[4]),
    );
  }

  @protected
  BangumiComment dco_decode_bangumi_comment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return BangumiComment(
      userName: dco_decode_String(arr[0]),
      rate: dco_decode_opt_box_autoadd_i_32(arr[1]),
      content: dco_decode_String(arr[2]),
      time: dco_decode_String(arr[3]),
      avatar: dco_decode_String(arr[4]),
    );
  }

  @protected
  BangumiEpisode dco_decode_bangumi_episode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return BangumiEpisode(
      id: dco_decode_i_64(arr[0]),
      name: dco_decode_String(arr[1]),
      nameCn: dco_decode_String(arr[2]),
      description: dco_decode_String(arr[3]),
      airdate: dco_decode_String(arr[4]),
      duration: dco_decode_String(arr[5]),
      sort: dco_decode_f_64(arr[6]),
    );
  }

  @protected
  BangumiEpisodeComment dco_decode_bangumi_episode_comment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return BangumiEpisodeComment(
      id: dco_decode_i_64(arr[0]),
      userName: dco_decode_String(arr[1]),
      userId: dco_decode_String(arr[2]),
      avatar: dco_decode_String(arr[3]),
      time: dco_decode_String(arr[4]),
      contentHtml: dco_decode_String(arr[5]),
      replies: dco_decode_list_bangumi_episode_comment(arr[6]),
    );
  }

  @protected
  BangumiImages dco_decode_bangumi_images(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return BangumiImages(
      small: dco_decode_String(arr[0]),
      grid: dco_decode_String(arr[1]),
      large: dco_decode_String(arr[2]),
      medium: dco_decode_String(arr[3]),
      common: dco_decode_String(arr[4]),
    );
  }

  @protected
  BangumiRelatedSubject dco_decode_bangumi_related_subject(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return BangumiRelatedSubject(
      id: dco_decode_i_64(arr[0]),
      name: dco_decode_String(arr[1]),
      nameCn: dco_decode_String(arr[2]),
      relation: dco_decode_String(arr[3]),
      image: dco_decode_String(arr[4]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BangumiImages dco_decode_box_autoadd_bangumi_images(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_bangumi_images(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  MikanSearchResult dco_decode_box_autoadd_mikan_search_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_mikan_search_result(raw);
  }

  @protected
  DmhyResource dco_decode_dmhy_resource(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return DmhyResource(
      title: dco_decode_String(arr[0]),
      magnet: dco_decode_String(arr[1]),
      size: dco_decode_String(arr[2]),
      publishDate: dco_decode_String(arr[3]),
      episode: dco_decode_opt_box_autoadd_i_32(arr[4]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AnimeInfo> dco_decode_list_anime_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_anime_info).toList();
  }

  @protected
  List<ArchiveQuarter> dco_decode_list_archive_quarter(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_archive_quarter).toList();
  }

  @protected
  List<BangumiActor> dco_decode_list_bangumi_actor(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bangumi_actor).toList();
  }

  @protected
  List<BangumiCharacter> dco_decode_list_bangumi_character(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bangumi_character).toList();
  }

  @protected
  List<BangumiComment> dco_decode_list_bangumi_comment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bangumi_comment).toList();
  }

  @protected
  List<BangumiEpisode> dco_decode_list_bangumi_episode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bangumi_episode).toList();
  }

  @protected
  List<BangumiEpisodeComment> dco_decode_list_bangumi_episode_comment(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_bangumi_episode_comment)
        .toList();
  }

  @protected
  List<BangumiRelatedSubject> dco_decode_list_bangumi_related_subject(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_bangumi_related_subject)
        .toList();
  }

  @protected
  List<DmhyResource> dco_decode_list_dmhy_resource(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_dmhy_resource).toList();
  }

  @protected
  List<MikanEpisodeResource> dco_decode_list_mikan_episode_resource(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_mikan_episode_resource)
        .toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RankingAnime> dco_decode_list_ranking_anime(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ranking_anime).toList();
  }

  @protected
  List<SearchPlayResult> dco_decode_list_search_play_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_search_play_result).toList();
  }

  @protected
  List<TorrentStats> dco_decode_list_torrent_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_torrent_stats).toList();
  }

  @protected
  List<TrackerInfo> dco_decode_list_tracker_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_tracker_info).toList();
  }

  @protected
  MikanEpisodeResource dco_decode_mikan_episode_resource(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return MikanEpisodeResource(
      title: dco_decode_String(arr[0]),
      magnet: dco_decode_String(arr[1]),
      size: dco_decode_String(arr[2]),
      updateTime: dco_decode_String(arr[3]),
      episode: dco_decode_opt_box_autoadd_i_32(arr[4]),
    );
  }

  @protected
  MikanSearchResult dco_decode_mikan_search_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return MikanSearchResult(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      imageUrl: dco_decode_String(arr[2]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BangumiImages? dco_decode_opt_box_autoadd_bangumi_images(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bangumi_images(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  MikanSearchResult? dco_decode_opt_box_autoadd_mikan_search_result(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_mikan_search_result(raw);
  }

  @protected
  RankingAnime dco_decode_ranking_anime(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return RankingAnime(
      title: dco_decode_String(arr[0]),
      bangumiId: dco_decode_String(arr[1]),
      coverUrl: dco_decode_String(arr[2]),
      score: dco_decode_opt_box_autoadd_f_64(arr[3]),
      rank: dco_decode_opt_box_autoadd_i_32(arr[4]),
      info: dco_decode_String(arr[5]),
      originalTitle: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  SearchPlayResult dco_decode_search_play_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SearchPlayResult(
      sourceName: dco_decode_String(arr[0]),
      playPageUrl: dco_decode_String(arr[1]),
      videoRegex: dco_decode_String(arr[2]),
      directVideoUrl: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  TorrentStats dco_decode_torrent_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return TorrentStats(
      infoHash: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      state: dco_decode_String(arr[2]),
      progress: dco_decode_f_64(arr[3]),
      downloadSpeed: dco_decode_f_64(arr[4]),
      uploadSpeed: dco_decode_f_64(arr[5]),
      downloaded: dco_decode_u_64(arr[6]),
      totalSize: dco_decode_u_64(arr[7]),
      peers: dco_decode_u_32(arr[8]),
      seeders: dco_decode_u_32(arr[9]),
    );
  }

  @protected
  TrackerInfo dco_decode_tracker_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TrackerInfo(
      url: dco_decode_String(arr[0]),
      status: dco_decode_String(arr[1]),
      peers: dco_decode_u_32(arr[2]),
      lastAnnounce: dco_decode_String(arr[3]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<SearchPlayResult> sse_decode_StreamSink_search_play_result_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AnimeInfo sse_decode_anime_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_subTitle = sse_decode_opt_String(deserializer);
    var var_bangumiId = sse_decode_opt_String(deserializer);
    var var_mikanId = sse_decode_opt_String(deserializer);
    var var_coverUrl = sse_decode_opt_String(deserializer);
    var var_siteUrl = sse_decode_opt_String(deserializer);
    var var_broadcastDay = sse_decode_opt_String(deserializer);
    var var_broadcastTime = sse_decode_opt_String(deserializer);
    var var_score = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_rank = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_fullJson = sse_decode_opt_String(deserializer);
    return AnimeInfo(
      title: var_title,
      subTitle: var_subTitle,
      bangumiId: var_bangumiId,
      mikanId: var_mikanId,
      coverUrl: var_coverUrl,
      siteUrl: var_siteUrl,
      broadcastDay: var_broadcastDay,
      broadcastTime: var_broadcastTime,
      score: var_score,
      rank: var_rank,
      tags: var_tags,
      fullJson: var_fullJson,
    );
  }

  @protected
  ArchiveQuarter sse_decode_archive_quarter(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_year = sse_decode_String(deserializer);
    var var_quarter = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    return ArchiveQuarter(
      year: var_year,
      quarter: var_quarter,
      title: var_title,
    );
  }

  @protected
  BangumiActor sse_decode_bangumi_actor(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    return BangumiActor(id: var_id, name: var_name);
  }

  @protected
  BangumiCharacter sse_decode_bangumi_character(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_roleName = sse_decode_String(deserializer);
    var var_images = sse_decode_opt_box_autoadd_bangumi_images(deserializer);
    var var_actors = sse_decode_list_bangumi_actor(deserializer);
    return BangumiCharacter(
      id: var_id,
      name: var_name,
      roleName: var_roleName,
      images: var_images,
      actors: var_actors,
    );
  }

  @protected
  BangumiComment sse_decode_bangumi_comment(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_userName = sse_decode_String(deserializer);
    var var_rate = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_time = sse_decode_String(deserializer);
    var var_avatar = sse_decode_String(deserializer);
    return BangumiComment(
      userName: var_userName,
      rate: var_rate,
      content: var_content,
      time: var_time,
      avatar: var_avatar,
    );
  }

  @protected
  BangumiEpisode sse_decode_bangumi_episode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_nameCn = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_airdate = sse_decode_String(deserializer);
    var var_duration = sse_decode_String(deserializer);
    var var_sort = sse_decode_f_64(deserializer);
    return BangumiEpisode(
      id: var_id,
      name: var_name,
      nameCn: var_nameCn,
      description: var_description,
      airdate: var_airdate,
      duration: var_duration,
      sort: var_sort,
    );
  }

  @protected
  BangumiEpisodeComment sse_decode_bangumi_episode_comment(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_userName = sse_decode_String(deserializer);
    var var_userId = sse_decode_String(deserializer);
    var var_avatar = sse_decode_String(deserializer);
    var var_time = sse_decode_String(deserializer);
    var var_contentHtml = sse_decode_String(deserializer);
    var var_replies = sse_decode_list_bangumi_episode_comment(deserializer);
    return BangumiEpisodeComment(
      id: var_id,
      userName: var_userName,
      userId: var_userId,
      avatar: var_avatar,
      time: var_time,
      contentHtml: var_contentHtml,
      replies: var_replies,
    );
  }

  @protected
  BangumiImages sse_decode_bangumi_images(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_small = sse_decode_String(deserializer);
    var var_grid = sse_decode_String(deserializer);
    var var_large = sse_decode_String(deserializer);
    var var_medium = sse_decode_String(deserializer);
    var var_common = sse_decode_String(deserializer);
    return BangumiImages(
      small: var_small,
      grid: var_grid,
      large: var_large,
      medium: var_medium,
      common: var_common,
    );
  }

  @protected
  BangumiRelatedSubject sse_decode_bangumi_related_subject(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_nameCn = sse_decode_String(deserializer);
    var var_relation = sse_decode_String(deserializer);
    var var_image = sse_decode_String(deserializer);
    return BangumiRelatedSubject(
      id: var_id,
      name: var_name,
      nameCn: var_nameCn,
      relation: var_relation,
      image: var_image,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BangumiImages sse_decode_box_autoadd_bangumi_images(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bangumi_images(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  MikanSearchResult sse_decode_box_autoadd_mikan_search_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_mikan_search_result(deserializer));
  }

  @protected
  DmhyResource sse_decode_dmhy_resource(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_magnet = sse_decode_String(deserializer);
    var var_size = sse_decode_String(deserializer);
    var var_publishDate = sse_decode_String(deserializer);
    var var_episode = sse_decode_opt_box_autoadd_i_32(deserializer);
    return DmhyResource(
      title: var_title,
      magnet: var_magnet,
      size: var_size,
      publishDate: var_publishDate,
      episode: var_episode,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AnimeInfo> sse_decode_list_anime_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AnimeInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_anime_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<ArchiveQuarter> sse_decode_list_archive_quarter(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ArchiveQuarter>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_archive_quarter(deserializer));
    }
    return ans_;
  }

  @protected
  List<BangumiActor> sse_decode_list_bangumi_actor(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BangumiActor>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bangumi_actor(deserializer));
    }
    return ans_;
  }

  @protected
  List<BangumiCharacter> sse_decode_list_bangumi_character(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BangumiCharacter>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bangumi_character(deserializer));
    }
    return ans_;
  }

  @protected
  List<BangumiComment> sse_decode_list_bangumi_comment(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BangumiComment>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bangumi_comment(deserializer));
    }
    return ans_;
  }

  @protected
  List<BangumiEpisode> sse_decode_list_bangumi_episode(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BangumiEpisode>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bangumi_episode(deserializer));
    }
    return ans_;
  }

  @protected
  List<BangumiEpisodeComment> sse_decode_list_bangumi_episode_comment(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BangumiEpisodeComment>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bangumi_episode_comment(deserializer));
    }
    return ans_;
  }

  @protected
  List<BangumiRelatedSubject> sse_decode_list_bangumi_related_subject(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BangumiRelatedSubject>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bangumi_related_subject(deserializer));
    }
    return ans_;
  }

  @protected
  List<DmhyResource> sse_decode_list_dmhy_resource(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DmhyResource>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_dmhy_resource(deserializer));
    }
    return ans_;
  }

  @protected
  List<MikanEpisodeResource> sse_decode_list_mikan_episode_resource(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MikanEpisodeResource>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_mikan_episode_resource(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RankingAnime> sse_decode_list_ranking_anime(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RankingAnime>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ranking_anime(deserializer));
    }
    return ans_;
  }

  @protected
  List<SearchPlayResult> sse_decode_list_search_play_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SearchPlayResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_search_play_result(deserializer));
    }
    return ans_;
  }

  @protected
  List<TorrentStats> sse_decode_list_torrent_stats(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TorrentStats>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_torrent_stats(deserializer));
    }
    return ans_;
  }

  @protected
  List<TrackerInfo> sse_decode_list_tracker_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TrackerInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_tracker_info(deserializer));
    }
    return ans_;
  }

  @protected
  MikanEpisodeResource sse_decode_mikan_episode_resource(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_magnet = sse_decode_String(deserializer);
    var var_size = sse_decode_String(deserializer);
    var var_updateTime = sse_decode_String(deserializer);
    var var_episode = sse_decode_opt_box_autoadd_i_32(deserializer);
    return MikanEpisodeResource(
      title: var_title,
      magnet: var_magnet,
      size: var_size,
      updateTime: var_updateTime,
      episode: var_episode,
    );
  }

  @protected
  MikanSearchResult sse_decode_mikan_search_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_imageUrl = sse_decode_String(deserializer);
    return MikanSearchResult(
      id: var_id,
      name: var_name,
      imageUrl: var_imageUrl,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BangumiImages? sse_decode_opt_box_autoadd_bangumi_images(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bangumi_images(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  MikanSearchResult? sse_decode_opt_box_autoadd_mikan_search_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_mikan_search_result(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RankingAnime sse_decode_ranking_anime(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_bangumiId = sse_decode_String(deserializer);
    var var_coverUrl = sse_decode_String(deserializer);
    var var_score = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_rank = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_info = sse_decode_String(deserializer);
    var var_originalTitle = sse_decode_opt_String(deserializer);
    return RankingAnime(
      title: var_title,
      bangumiId: var_bangumiId,
      coverUrl: var_coverUrl,
      score: var_score,
      rank: var_rank,
      info: var_info,
      originalTitle: var_originalTitle,
    );
  }

  @protected
  SearchPlayResult sse_decode_search_play_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sourceName = sse_decode_String(deserializer);
    var var_playPageUrl = sse_decode_String(deserializer);
    var var_videoRegex = sse_decode_String(deserializer);
    var var_directVideoUrl = sse_decode_opt_String(deserializer);
    return SearchPlayResult(
      sourceName: var_sourceName,
      playPageUrl: var_playPageUrl,
      videoRegex: var_videoRegex,
      directVideoUrl: var_directVideoUrl,
    );
  }

  @protected
  TorrentStats sse_decode_torrent_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_infoHash = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_state = sse_decode_String(deserializer);
    var var_progress = sse_decode_f_64(deserializer);
    var var_downloadSpeed = sse_decode_f_64(deserializer);
    var var_uploadSpeed = sse_decode_f_64(deserializer);
    var var_downloaded = sse_decode_u_64(deserializer);
    var var_totalSize = sse_decode_u_64(deserializer);
    var var_peers = sse_decode_u_32(deserializer);
    var var_seeders = sse_decode_u_32(deserializer);
    return TorrentStats(
      infoHash: var_infoHash,
      name: var_name,
      state: var_state,
      progress: var_progress,
      downloadSpeed: var_downloadSpeed,
      uploadSpeed: var_uploadSpeed,
      downloaded: var_downloaded,
      totalSize: var_totalSize,
      peers: var_peers,
      seeders: var_seeders,
    );
  }

  @protected
  TrackerInfo sse_decode_tracker_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_url = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_peers = sse_decode_u_32(deserializer);
    var var_lastAnnounce = sse_decode_String(deserializer);
    return TrackerInfo(
      url: var_url,
      status: var_status,
      peers: var_peers,
      lastAnnounce: var_lastAnnounce,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_search_play_result_Sse(
    RustStreamSink<SearchPlayResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_search_play_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_anime_info(AnimeInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.subTitle, serializer);
    sse_encode_opt_String(self.bangumiId, serializer);
    sse_encode_opt_String(self.mikanId, serializer);
    sse_encode_opt_String(self.coverUrl, serializer);
    sse_encode_opt_String(self.siteUrl, serializer);
    sse_encode_opt_String(self.broadcastDay, serializer);
    sse_encode_opt_String(self.broadcastTime, serializer);
    sse_encode_opt_box_autoadd_f_64(self.score, serializer);
    sse_encode_opt_box_autoadd_i_32(self.rank, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_opt_String(self.fullJson, serializer);
  }

  @protected
  void sse_encode_archive_quarter(
    ArchiveQuarter self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.year, serializer);
    sse_encode_String(self.quarter, serializer);
    sse_encode_String(self.title, serializer);
  }

  @protected
  void sse_encode_bangumi_actor(BangumiActor self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.name, serializer);
  }

  @protected
  void sse_encode_bangumi_character(
    BangumiCharacter self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.roleName, serializer);
    sse_encode_opt_box_autoadd_bangumi_images(self.images, serializer);
    sse_encode_list_bangumi_actor(self.actors, serializer);
  }

  @protected
  void sse_encode_bangumi_comment(
    BangumiComment self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.userName, serializer);
    sse_encode_opt_box_autoadd_i_32(self.rate, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_String(self.time, serializer);
    sse_encode_String(self.avatar, serializer);
  }

  @protected
  void sse_encode_bangumi_episode(
    BangumiEpisode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.nameCn, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_String(self.airdate, serializer);
    sse_encode_String(self.duration, serializer);
    sse_encode_f_64(self.sort, serializer);
  }

  @protected
  void sse_encode_bangumi_episode_comment(
    BangumiEpisodeComment self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.userName, serializer);
    sse_encode_String(self.userId, serializer);
    sse_encode_String(self.avatar, serializer);
    sse_encode_String(self.time, serializer);
    sse_encode_String(self.contentHtml, serializer);
    sse_encode_list_bangumi_episode_comment(self.replies, serializer);
  }

  @protected
  void sse_encode_bangumi_images(BangumiImages self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.small, serializer);
    sse_encode_String(self.grid, serializer);
    sse_encode_String(self.large, serializer);
    sse_encode_String(self.medium, serializer);
    sse_encode_String(self.common, serializer);
  }

  @protected
  void sse_encode_bangumi_related_subject(
    BangumiRelatedSubject self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.nameCn, serializer);
    sse_encode_String(self.relation, serializer);
    sse_encode_String(self.image, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bangumi_images(
    BangumiImages self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bangumi_images(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_mikan_search_result(
    MikanSearchResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_mikan_search_result(self, serializer);
  }

  @protected
  void sse_encode_dmhy_resource(DmhyResource self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.magnet, serializer);
    sse_encode_String(self.size, serializer);
    sse_encode_String(self.publishDate, serializer);
    sse_encode_opt_box_autoadd_i_32(self.episode, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_anime_info(
    List<AnimeInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_anime_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_archive_quarter(
    List<ArchiveQuarter> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_archive_quarter(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bangumi_actor(
    List<BangumiActor> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bangumi_actor(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bangumi_character(
    List<BangumiCharacter> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bangumi_character(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bangumi_comment(
    List<BangumiComment> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bangumi_comment(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bangumi_episode(
    List<BangumiEpisode> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bangumi_episode(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bangumi_episode_comment(
    List<BangumiEpisodeComment> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bangumi_episode_comment(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bangumi_related_subject(
    List<BangumiRelatedSubject> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bangumi_related_subject(item, serializer);
    }
  }

  @protected
  void sse_encode_list_dmhy_resource(
    List<DmhyResource> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_dmhy_resource(item, serializer);
    }
  }

  @protected
  void sse_encode_list_mikan_episode_resource(
    List<MikanEpisodeResource> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_mikan_episode_resource(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_ranking_anime(
    List<RankingAnime> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ranking_anime(item, serializer);
    }
  }

  @protected
  void sse_encode_list_search_play_result(
    List<SearchPlayResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_search_play_result(item, serializer);
    }
  }

  @protected
  void sse_encode_list_torrent_stats(
    List<TorrentStats> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_torrent_stats(item, serializer);
    }
  }

  @protected
  void sse_encode_list_tracker_info(
    List<TrackerInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_tracker_info(item, serializer);
    }
  }

  @protected
  void sse_encode_mikan_episode_resource(
    MikanEpisodeResource self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.magnet, serializer);
    sse_encode_String(self.size, serializer);
    sse_encode_String(self.updateTime, serializer);
    sse_encode_opt_box_autoadd_i_32(self.episode, serializer);
  }

  @protected
  void sse_encode_mikan_search_result(
    MikanSearchResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.imageUrl, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bangumi_images(
    BangumiImages? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bangumi_images(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_mikan_search_result(
    MikanSearchResult? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_mikan_search_result(self, serializer);
    }
  }

  @protected
  void sse_encode_ranking_anime(RankingAnime self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.bangumiId, serializer);
    sse_encode_String(self.coverUrl, serializer);
    sse_encode_opt_box_autoadd_f_64(self.score, serializer);
    sse_encode_opt_box_autoadd_i_32(self.rank, serializer);
    sse_encode_String(self.info, serializer);
    sse_encode_opt_String(self.originalTitle, serializer);
  }

  @protected
  void sse_encode_search_play_result(
    SearchPlayResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sourceName, serializer);
    sse_encode_String(self.playPageUrl, serializer);
    sse_encode_String(self.videoRegex, serializer);
    sse_encode_opt_String(self.directVideoUrl, serializer);
  }

  @protected
  void sse_encode_torrent_stats(TorrentStats self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.infoHash, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.state, serializer);
    sse_encode_f_64(self.progress, serializer);
    sse_encode_f_64(self.downloadSpeed, serializer);
    sse_encode_f_64(self.uploadSpeed, serializer);
    sse_encode_u_64(self.downloaded, serializer);
    sse_encode_u_64(self.totalSize, serializer);
    sse_encode_u_32(self.peers, serializer);
    sse_encode_u_32(self.seeders, serializer);
  }

  @protected
  void sse_encode_tracker_info(TrackerInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.url, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_u_32(self.peers, serializer);
    sse_encode_String(self.lastAnnounce, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
