// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class BangumiActor {
  final PlatformInt64 id;
  final String name;

  const BangumiActor({required this.id, required this.name});

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BangumiActor &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}

class BangumiBlogDetail {
  final PlatformInt64 id;
  final String title;
  final String summary;
  final String content;
  final String contentHtml;
  final String userId;
  final String userName;
  final String avatar;
  final String time;
  final int repliesCount;
  final List<String> tags;
  final List<BangumiCommentReaction> reactions;

  const BangumiBlogDetail({
    required this.id,
    required this.title,
    required this.summary,
    required this.content,
    required this.contentHtml,
    required this.userId,
    required this.userName,
    required this.avatar,
    required this.time,
    required this.repliesCount,
    required this.tags,
    required this.reactions,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      summary.hashCode ^
      content.hashCode ^
      contentHtml.hashCode ^
      userId.hashCode ^
      userName.hashCode ^
      avatar.hashCode ^
      time.hashCode ^
      repliesCount.hashCode ^
      tags.hashCode ^
      reactions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BangumiBlogDetail &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          summary == other.summary &&
          content == other.content &&
          contentHtml == other.contentHtml &&
          userId == other.userId &&
          userName == other.userName &&
          avatar == other.avatar &&
          time == other.time &&
          repliesCount == other.repliesCount &&
          tags == other.tags &&
          reactions == other.reactions;
}

class BangumiCharacter {
  final PlatformInt64 id;
  final String name;
  final String roleName;
  final BangumiImages? images;
  final List<BangumiActor> actors;

  const BangumiCharacter({
    required this.id,
    required this.name,
    required this.roleName,
    this.images,
    required this.actors,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      roleName.hashCode ^
      images.hashCode ^
      actors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BangumiCharacter &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          roleName == other.roleName &&
          images == other.images &&
          actors == other.actors;
}

class BangumiComment {
  final PlatformInt64 id;
  final String userId;
  final String userName;

  /// 1=想看, 2=看过, 3=在看, 4=搁置, 5=抛弃.
  final int? collectionType;
  final int? rate;
  final String content;
  final String contentHtml;
  final String time;
  final String avatar;
  final List<BangumiCommentReaction> reactions;

  const BangumiComment({
    required this.id,
    required this.userId,
    required this.userName,
    this.collectionType,
    this.rate,
    required this.content,
    required this.contentHtml,
    required this.time,
    required this.avatar,
    required this.reactions,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      userId.hashCode ^
      userName.hashCode ^
      collectionType.hashCode ^
      rate.hashCode ^
      content.hashCode ^
      contentHtml.hashCode ^
      time.hashCode ^
      avatar.hashCode ^
      reactions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BangumiComment &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          userId == other.userId &&
          userName == other.userName &&
          collectionType == other.collectionType &&
          rate == other.rate &&
          content == other.content &&
          contentHtml == other.contentHtml &&
          time == other.time &&
          avatar == other.avatar &&
          reactions == other.reactions;
}

class BangumiCommentReaction {
  final String name;
  final String imageUrl;
  final int count;
  final bool reacted;

  const BangumiCommentReaction({
    required this.name,
    required this.imageUrl,
    required this.count,
    required this.reacted,
  });

  @override
  int get hashCode =>
      name.hashCode ^ imageUrl.hashCode ^ count.hashCode ^ reacted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BangumiCommentReaction &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          imageUrl == other.imageUrl &&
          count == other.count &&
          reacted == other.reacted;
}

class BangumiCommentsPage {
  final List<BangumiComment> comments;
  final int? total;

  const BangumiCommentsPage({required this.comments, this.total});

  @override
  int get hashCode => comments.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BangumiCommentsPage &&
          runtimeType == other.runtimeType &&
          comments == other.comments &&
          total == other.total;
}

class BangumiEpisode {
  final PlatformInt64 id;
  final String name;
  final String nameCn;
  final String description;
  final String airdate;
  final String duration;
  final double sort;

  const BangumiEpisode({
    required this.id,
    required this.name,
    required this.nameCn,
    required this.description,
    required this.airdate,
    required this.duration,
    required this.sort,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      nameCn.hashCode ^
      description.hashCode ^
      airdate.hashCode ^
      duration.hashCode ^
      sort.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BangumiEpisode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          nameCn == other.nameCn &&
          description == other.description &&
          airdate == other.airdate &&
          duration == other.duration &&
          sort == other.sort;
}

class BangumiEpisodeComment {
  final PlatformInt64 id;
  final String userName;
  final String userId;
  final String avatar;
  final String time;
  final int state;
  final String contentHtml;
  final List<BangumiEpisodeComment> replies;
  final List<BangumiCommentReaction> reactions;

  const BangumiEpisodeComment({
    required this.id,
    required this.userName,
    required this.userId,
    required this.avatar,
    required this.time,
    required this.state,
    required this.contentHtml,
    required this.replies,
    required this.reactions,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      userName.hashCode ^
      userId.hashCode ^
      avatar.hashCode ^
      time.hashCode ^
      state.hashCode ^
      contentHtml.hashCode ^
      replies.hashCode ^
      reactions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BangumiEpisodeComment &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          userName == other.userName &&
          userId == other.userId &&
          avatar == other.avatar &&
          time == other.time &&
          state == other.state &&
          contentHtml == other.contentHtml &&
          replies == other.replies &&
          reactions == other.reactions;
}

class BangumiImages {
  final String small;
  final String grid;
  final String large;
  final String medium;
  final String common;

  const BangumiImages({
    required this.small,
    required this.grid,
    required this.large,
    required this.medium,
    required this.common,
  });

  @override
  int get hashCode =>
      small.hashCode ^
      grid.hashCode ^
      large.hashCode ^
      medium.hashCode ^
      common.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BangumiImages &&
          runtimeType == other.runtimeType &&
          small == other.small &&
          grid == other.grid &&
          large == other.large &&
          medium == other.medium &&
          common == other.common;
}

/// Result of an OAuth token exchange (authorization code → tokens) or a
/// refresh. Mirrors the JSON returned by `POST /oauth/access_token`.
class BangumiOAuthToken {
  final String accessToken;
  final String refreshToken;
  final PlatformInt64 expiresIn;
  final PlatformInt64 userId;

  const BangumiOAuthToken({
    required this.accessToken,
    required this.refreshToken,
    required this.expiresIn,
    required this.userId,
  });

  @override
  int get hashCode =>
      accessToken.hashCode ^
      refreshToken.hashCode ^
      expiresIn.hashCode ^
      userId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BangumiOAuthToken &&
          runtimeType == other.runtimeType &&
          accessToken == other.accessToken &&
          refreshToken == other.refreshToken &&
          expiresIn == other.expiresIn &&
          userId == other.userId;
}

class BangumiPerson {
  final PlatformInt64 id;
  final String name;
  final String relation;
  final List<String> career;
  final int personType;
  final BangumiImages? images;

  const BangumiPerson({
    required this.id,
    required this.name,
    required this.relation,
    required this.career,
    required this.personType,
    this.images,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      relation.hashCode ^
      career.hashCode ^
      personType.hashCode ^
      images.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BangumiPerson &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          relation == other.relation &&
          career == other.career &&
          personType == other.personType &&
          images == other.images;
}

class BangumiRelatedSubject {
  final PlatformInt64 id;
  final String name;
  final String nameCn;
  final String relation;
  final String image;

  const BangumiRelatedSubject({
    required this.id,
    required this.name,
    required this.nameCn,
    required this.relation,
    required this.image,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      nameCn.hashCode ^
      relation.hashCode ^
      image.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BangumiRelatedSubject &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          nameCn == other.nameCn &&
          relation == other.relation &&
          image == other.image;
}

class BangumiReview {
  final PlatformInt64 id;
  final PlatformInt64 entryId;
  final String userId;
  final String userName;
  final String avatar;
  final String title;
  final String summary;
  final String time;
  final int repliesCount;

  const BangumiReview({
    required this.id,
    required this.entryId,
    required this.userId,
    required this.userName,
    required this.avatar,
    required this.title,
    required this.summary,
    required this.time,
    required this.repliesCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      entryId.hashCode ^
      userId.hashCode ^
      userName.hashCode ^
      avatar.hashCode ^
      title.hashCode ^
      summary.hashCode ^
      time.hashCode ^
      repliesCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BangumiReview &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          entryId == other.entryId &&
          userId == other.userId &&
          userName == other.userName &&
          avatar == other.avatar &&
          title == other.title &&
          summary == other.summary &&
          time == other.time &&
          repliesCount == other.repliesCount;
}

class BangumiReviewsPage {
  final List<BangumiReview> reviews;
  final int? total;

  const BangumiReviewsPage({required this.reviews, this.total});

  @override
  int get hashCode => reviews.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BangumiReviewsPage &&
          runtimeType == other.runtimeType &&
          reviews == other.reviews &&
          total == other.total;
}

class BangumiTopic {
  final PlatformInt64 id;
  final String userId;
  final String userName;
  final String avatar;
  final String title;
  final String time;
  final String updatedAt;
  final int repliesCount;

  const BangumiTopic({
    required this.id,
    required this.userId,
    required this.userName,
    required this.avatar,
    required this.title,
    required this.time,
    required this.updatedAt,
    required this.repliesCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      userId.hashCode ^
      userName.hashCode ^
      avatar.hashCode ^
      title.hashCode ^
      time.hashCode ^
      updatedAt.hashCode ^
      repliesCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BangumiTopic &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          userId == other.userId &&
          userName == other.userName &&
          avatar == other.avatar &&
          title == other.title &&
          time == other.time &&
          updatedAt == other.updatedAt &&
          repliesCount == other.repliesCount;
}

class BangumiTopicDetail {
  final PlatformInt64 id;
  final String title;
  final String userId;
  final String userName;
  final String avatar;
  final String time;
  final String updatedAt;
  final int repliesCount;
  final String content;
  final String contentHtml;

  /// Moderation state of the opening post, using p1's *comment* state enum.
  /// Distinct from the topic's own state: an admin-closed topic (topic state
  /// `1`) still shows its body, while a deleted post (comment state `6`/`7`)
  /// must not.
  final int contentState;
  final List<BangumiCommentReaction> reactions;
  final List<BangumiEpisodeComment> replies;

  const BangumiTopicDetail({
    required this.id,
    required this.title,
    required this.userId,
    required this.userName,
    required this.avatar,
    required this.time,
    required this.updatedAt,
    required this.repliesCount,
    required this.content,
    required this.contentHtml,
    required this.contentState,
    required this.reactions,
    required this.replies,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      userId.hashCode ^
      userName.hashCode ^
      avatar.hashCode ^
      time.hashCode ^
      updatedAt.hashCode ^
      repliesCount.hashCode ^
      content.hashCode ^
      contentHtml.hashCode ^
      contentState.hashCode ^
      reactions.hashCode ^
      replies.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BangumiTopicDetail &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          userId == other.userId &&
          userName == other.userName &&
          avatar == other.avatar &&
          time == other.time &&
          updatedAt == other.updatedAt &&
          repliesCount == other.repliesCount &&
          content == other.content &&
          contentHtml == other.contentHtml &&
          contentState == other.contentState &&
          reactions == other.reactions &&
          replies == other.replies;
}

class BangumiTopicsPage {
  final List<BangumiTopic> topics;
  final int? total;

  /// Rows upstream actually returned for this page, before moderation
  /// filtering. Pagination must advance on this, not on `topics.len()`, or a
  /// page whose every row was filtered out would look like the end of the list.
  final int fetchedCount;

  const BangumiTopicsPage({
    required this.topics,
    this.total,
    required this.fetchedCount,
  });

  @override
  int get hashCode => topics.hashCode ^ total.hashCode ^ fetchedCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BangumiTopicsPage &&
          runtimeType == other.runtimeType &&
          topics == other.topics &&
          total == other.total &&
          fetchedCount == other.fetchedCount;
}

class BangumiUserCollectionEntry {
  final String updatedAt;
  final String comment;
  final List<String> tags;
  final PlatformInt64 subjectId;

  /// 1=想看, 2=看过, 3=在看, 4=搁置, 5=抛弃
  final int collectionType;
  final int rate;
  final bool private;
  final String subjectName;
  final String subjectNameCn;
  final String subjectShortSummary;
  final double subjectScore;
  final int subjectEps;
  final int subjectCollectionTotal;
  final String imageSmall;
  final String imageGrid;
  final String imageLarge;
  final String imageMedium;
  final String imageCommon;

  const BangumiUserCollectionEntry({
    required this.updatedAt,
    required this.comment,
    required this.tags,
    required this.subjectId,
    required this.collectionType,
    required this.rate,
    required this.private,
    required this.subjectName,
    required this.subjectNameCn,
    required this.subjectShortSummary,
    required this.subjectScore,
    required this.subjectEps,
    required this.subjectCollectionTotal,
    required this.imageSmall,
    required this.imageGrid,
    required this.imageLarge,
    required this.imageMedium,
    required this.imageCommon,
  });

  @override
  int get hashCode =>
      updatedAt.hashCode ^
      comment.hashCode ^
      tags.hashCode ^
      subjectId.hashCode ^
      collectionType.hashCode ^
      rate.hashCode ^
      private.hashCode ^
      subjectName.hashCode ^
      subjectNameCn.hashCode ^
      subjectShortSummary.hashCode ^
      subjectScore.hashCode ^
      subjectEps.hashCode ^
      subjectCollectionTotal.hashCode ^
      imageSmall.hashCode ^
      imageGrid.hashCode ^
      imageLarge.hashCode ^
      imageMedium.hashCode ^
      imageCommon.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BangumiUserCollectionEntry &&
          runtimeType == other.runtimeType &&
          updatedAt == other.updatedAt &&
          comment == other.comment &&
          tags == other.tags &&
          subjectId == other.subjectId &&
          collectionType == other.collectionType &&
          rate == other.rate &&
          private == other.private &&
          subjectName == other.subjectName &&
          subjectNameCn == other.subjectNameCn &&
          subjectShortSummary == other.subjectShortSummary &&
          subjectScore == other.subjectScore &&
          subjectEps == other.subjectEps &&
          subjectCollectionTotal == other.subjectCollectionTotal &&
          imageSmall == other.imageSmall &&
          imageGrid == other.imageGrid &&
          imageLarge == other.imageLarge &&
          imageMedium == other.imageMedium &&
          imageCommon == other.imageCommon;
}

class BangumiUserInfo {
  final PlatformInt64 id;
  final String username;
  final String nickname;
  final String? sign;
  final String? url;
  final String? avatarLarge;
  final String? avatarMedium;
  final String? avatarSmall;

  const BangumiUserInfo({
    required this.id,
    required this.username,
    required this.nickname,
    this.sign,
    this.url,
    this.avatarLarge,
    this.avatarMedium,
    this.avatarSmall,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      username.hashCode ^
      nickname.hashCode ^
      sign.hashCode ^
      url.hashCode ^
      avatarLarge.hashCode ^
      avatarMedium.hashCode ^
      avatarSmall.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BangumiUserInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          username == other.username &&
          nickname == other.nickname &&
          sign == other.sign &&
          url == other.url &&
          avatarLarge == other.avatarLarge &&
          avatarMedium == other.avatarMedium &&
          avatarSmall == other.avatarSmall;
}

/// Character details info from /v0/characters/{character_id}
class CharacterDetails {
  final PlatformInt64 id;
  final String name;
  final String summary;
  final BangumiImages? images;
  final String? gender;
  final int? birthYear;
  final int? birthMon;
  final int? birthDay;
  final String? bloodType;
  final CharacterStat stat;
  final List<InfoboxItem> infobox;

  const CharacterDetails({
    required this.id,
    required this.name,
    required this.summary,
    this.images,
    this.gender,
    this.birthYear,
    this.birthMon,
    this.birthDay,
    this.bloodType,
    required this.stat,
    required this.infobox,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      summary.hashCode ^
      images.hashCode ^
      gender.hashCode ^
      birthYear.hashCode ^
      birthMon.hashCode ^
      birthDay.hashCode ^
      bloodType.hashCode ^
      stat.hashCode ^
      infobox.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CharacterDetails &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          summary == other.summary &&
          images == other.images &&
          gender == other.gender &&
          birthYear == other.birthYear &&
          birthMon == other.birthMon &&
          birthDay == other.birthDay &&
          bloodType == other.bloodType &&
          stat == other.stat &&
          infobox == other.infobox;
}

class CharacterStat {
  final int comments;
  final int collects;

  const CharacterStat({required this.comments, required this.collects});

  @override
  int get hashCode => comments.hashCode ^ collects.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CharacterStat &&
          runtimeType == other.runtimeType &&
          comments == other.comments &&
          collects == other.collects;
}

/// Character subject info from /v0/characters/{character_id}/subjects
/// Only includes anime (type=2)
class CharacterSubject {
  final PlatformInt64 id;
  final String name;
  final String nameCn;
  final String image;
  final String staff;
  final List<CharacterSubjectPerson> persons;

  const CharacterSubject({
    required this.id,
    required this.name,
    required this.nameCn,
    required this.image,
    required this.staff,
    required this.persons,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      nameCn.hashCode ^
      image.hashCode ^
      staff.hashCode ^
      persons.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CharacterSubject &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          nameCn == other.nameCn &&
          image == other.image &&
          staff == other.staff &&
          persons == other.persons;
}

/// Voice actor info associated with a specific subject
class CharacterSubjectPerson {
  final PlatformInt64 id;
  final String name;
  final BangumiImages? images;

  const CharacterSubjectPerson({
    required this.id,
    required this.name,
    this.images,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ images.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CharacterSubjectPerson &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          images == other.images;
}

class InfoboxItem {
  final String key;
  final String value;

  const InfoboxItem({required this.key, required this.value});

  @override
  int get hashCode => key.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InfoboxItem &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value;
}

/// Character info from /v0/persons/{person_id}/characters (only subject_type=2)
class PersonCharacter {
  final PlatformInt64 id;
  final String name;
  final BangumiImages? images;
  final PlatformInt64 subjectId;
  final String subjectName;
  final String subjectNameCn;
  final String staff;

  const PersonCharacter({
    required this.id,
    required this.name,
    this.images,
    required this.subjectId,
    required this.subjectName,
    required this.subjectNameCn,
    required this.staff,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      images.hashCode ^
      subjectId.hashCode ^
      subjectName.hashCode ^
      subjectNameCn.hashCode ^
      staff.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PersonCharacter &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          images == other.images &&
          subjectId == other.subjectId &&
          subjectName == other.subjectName &&
          subjectNameCn == other.subjectNameCn &&
          staff == other.staff;
}

/// Person details from /v0/persons/{person_id}
class PersonDetails {
  final PlatformInt64 id;
  final String name;
  final String summary;
  final String img;
  final List<String> career;
  final int personType;
  final CharacterStat stat;
  final List<InfoboxItem> infobox;
  final bool locked;

  const PersonDetails({
    required this.id,
    required this.name,
    required this.summary,
    required this.img,
    required this.career,
    required this.personType,
    required this.stat,
    required this.infobox,
    required this.locked,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      summary.hashCode ^
      img.hashCode ^
      career.hashCode ^
      personType.hashCode ^
      stat.hashCode ^
      infobox.hashCode ^
      locked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PersonDetails &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          summary == other.summary &&
          img == other.img &&
          career == other.career &&
          personType == other.personType &&
          stat == other.stat &&
          infobox == other.infobox &&
          locked == other.locked;
}

/// Subject info from /v0/persons/{person_id}/subjects (only type=2 anime)
class PersonSubject {
  final PlatformInt64 id;
  final String name;
  final String nameCn;
  final String image;
  final String staff;
  final String eps;

  const PersonSubject({
    required this.id,
    required this.name,
    required this.nameCn,
    required this.image,
    required this.staff,
    required this.eps,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      nameCn.hashCode ^
      image.hashCode ^
      staff.hashCode ^
      eps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PersonSubject &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          nameCn == other.nameCn &&
          image == other.image &&
          staff == other.staff &&
          eps == other.eps;
}
