// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_subject_batch_graphql_query`

Future<Value> executeBangumiGraphql({
  required String actionName,
  required String query,
  required Value variables,
}) => RustLib.instance.api.crateApiBangumiGraphqlExecuteBangumiGraphql(
  actionName: actionName,
  query: query,
  variables: variables,
);

Future<Map<PlatformInt64, Value>> fetchSubjectDetailsGraphqlBatch({
  required Int64List ids,
}) => RustLib.instance.api
    .crateApiBangumiGraphqlFetchSubjectDetailsGraphqlBatch(ids: ids);

Future<Value> fetchLightSubjectDetailsGraphql({
  required PlatformInt64 subjectId,
}) =>
    RustLib.instance.api.crateApiBangumiGraphqlFetchLightSubjectDetailsGraphql(
      subjectId: subjectId,
    );

Future<Value> normalizeLightSubjectGraphqlJson({required Value subject}) =>
    RustLib.instance.api.crateApiBangumiGraphqlNormalizeLightSubjectGraphqlJson(
      subject: subject,
    );

Future<Value> normalizeGraphqlSubjectJson({required Value subject}) => RustLib
    .instance
    .api
    .crateApiBangumiGraphqlNormalizeGraphqlSubjectJson(subject: subject);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Value>>
abstract class Value implements RustOpaqueInterface {}
