// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `normalize_url`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CONFIG`, `RuntimeConfig`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

Future<void> updateConfig({
  required String bgm,
  required String bangumi,
  required String mikan,
  required String playbackSub,
}) => RustLib.instance.api.crateApiConfigUpdateConfig(
  bgm: bgm,
  bangumi: bangumi,
  mikan: mikan,
  playbackSub: playbackSub,
);

Future<String> getBgmlistUrl() =>
    RustLib.instance.api.crateApiConfigGetBgmlistUrl();

Future<String> getBangumiUrl() =>
    RustLib.instance.api.crateApiConfigGetBangumiUrl();

Future<String> getBangumiApiUrl() =>
    RustLib.instance.api.crateApiConfigGetBangumiApiUrl();

Future<String> getMikanUrl() =>
    RustLib.instance.api.crateApiConfigGetMikanUrl();

Future<String> getPlaybackSubUrl() =>
    RustLib.instance.api.crateApiConfigGetPlaybackSubUrl();

Future<void> setDisabledSources({required List<String> sources}) =>
    RustLib.instance.api.crateApiConfigSetDisabledSources(sources: sources);

Future<bool> isSourceEnabled({required String name}) =>
    RustLib.instance.api.crateApiConfigIsSourceEnabled(name: name);
