// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_reverse_proxy_settings`, `bangumi_url_for_proxy_mode`, `canonical_bangumi_host`, `mirror_for_host`, `normalize_url`, `rewrite_host_in_authority`, `split_scheme`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CONFIG`, `RuntimeConfig`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `deref`, `initialize`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `bangumi_canonical_hosts`, `get_bangumi_data_cdn_urls`, `get_bangumi_data_sha512_hex`

Future<void> initConfig({
  required String cacheDir,
  required String downloadDir,
}) => RustLib.instance.api.crateApiConfigInitConfig(
  cacheDir: cacheDir,
  downloadDir: downloadDir,
);

Future<void> updateConfig({
  required String bgm,
  required String bangumi,
  required String mikan,
  required String playbackSub,
  required bool useReverseProxy,
}) => RustLib.instance.api.crateApiConfigUpdateConfig(
  bgm: bgm,
  bangumi: bangumi,
  mikan: mikan,
  playbackSub: playbackSub,
  useReverseProxy: useReverseProxy,
);

Future<void> setBangumiReverseProxy({required bool enabled}) =>
    RustLib.instance.api.crateApiConfigSetBangumiReverseProxy(enabled: enabled);

Future<bool> getBangumiReverseProxy() =>
    RustLib.instance.api.crateApiConfigGetBangumiReverseProxy();

Future<void> setBangumiUseEch({required bool enabled}) =>
    RustLib.instance.api.crateApiConfigSetBangumiUseEch(enabled: enabled);

Future<bool> getBangumiUseEch() =>
    RustLib.instance.api.crateApiConfigGetBangumiUseEch();

/// Store the OAuth access token used to authenticate Bangumi write requests.
/// Called by Dart after a successful OAuth exchange and on app init from
/// secure storage. The token value is never logged.
Future<void> setBangumiAccessToken({required String token}) =>
    RustLib.instance.api.crateApiConfigSetBangumiAccessToken(token: token);

/// Clear the stored OAuth access token (on logout or when a refresh fails).
Future<void> clearBangumiAccessToken() =>
    RustLib.instance.api.crateApiConfigClearBangumiAccessToken();

/// Read the current OAuth access token, if any. Used by the authenticated
/// request helpers to attach the `Authorization: Bearer` header.
Future<String?> getBangumiAccessToken() =>
    RustLib.instance.api.crateApiConfigGetBangumiAccessToken();

Future<String> getBgmlistUrl() =>
    RustLib.instance.api.crateApiConfigGetBgmlistUrl();

Future<String> getBgmlistApiUrl() =>
    RustLib.instance.api.crateApiConfigGetBgmlistApiUrl();

Future<String> getBangumiUrl() =>
    RustLib.instance.api.crateApiConfigGetBangumiUrl();

Future<String> getBangumiApiUrl() =>
    RustLib.instance.api.crateApiConfigGetBangumiApiUrl();

Future<String> getBangumiNextUrl() =>
    RustLib.instance.api.crateApiConfigGetBangumiNextUrl();

/// The base URL for OAuth (`/oauth/authorize`, `/oauth/access_token`).
///
/// OAuth lives on the **main site** but *must* be `bgm.tv`, not the historical
/// `bangumi.tv` alias: a POST to `bangumi.tv/oauth/access_token` 301-redirects
/// to `bgm.tv`, and reqwest drops the form body across that redirect, so the
/// token exchange fails with a 400. We therefore force `bgm.tv` here (mirroring
/// the hard-coded `api.bgm.tv` mapping in [`get_bangumi_api_url`]) instead of
/// deriving it from the user-configured `bangumi_url`.
Future<String> getBangumiOauthUrl() =>
    RustLib.instance.api.crateApiConfigGetBangumiOauthUrl();

Future<String> getBangumiLainUrl() =>
    RustLib.instance.api.crateApiConfigGetBangumiLainUrl();

/// Rewrite a bangumi URL coming back from an API response (cover images, avatars,
/// share links, etc.) to its mirror host **only when the user has opted into the
/// reverse proxy**. When proxying is disabled the input is returned unchanged so
/// the canonical bangumi.tv / bgm.tv / lain.bgm.tv hosts are preserved.
///
/// Use this for any value derived from upstream data. The raw [`rewrite_bangumi_url`]
/// (which always rewrites when `to_mirror` is true) should be reserved for base-URL
/// construction and for converting mirror hosts back to their canonical form.
Future<String> rewriteBangumiUrlIfProxied({required String raw}) =>
    RustLib.instance.api.crateApiConfigRewriteBangumiUrlIfProxied(raw: raw);

Future<String> getMikanUrl() =>
    RustLib.instance.api.crateApiConfigGetMikanUrl();

Future<String> getPlaybackSubUrl() =>
    RustLib.instance.api.crateApiConfigGetPlaybackSubUrl();

Future<void> setBangumiRequestMode({required String mode}) =>
    RustLib.instance.api.crateApiConfigSetBangumiRequestMode(mode: mode);

Future<String> getBangumiRequestMode() =>
    RustLib.instance.api.crateApiConfigGetBangumiRequestMode();

Future<String> getCacheDir() =>
    RustLib.instance.api.crateApiConfigGetCacheDir();

Future<String> getDownloadDir() =>
    RustLib.instance.api.crateApiConfigGetDownloadDir();

Future<void> setDownloadDir({required String dir}) =>
    RustLib.instance.api.crateApiConfigSetDownloadDir(dir: dir);

Future<void> setDisabledSources({required List<String> sources}) =>
    RustLib.instance.api.crateApiConfigSetDisabledSources(sources: sources);

Future<bool> isSourceEnabled({required String name}) =>
    RustLib.instance.api.crateApiConfigIsSourceEnabled(name: name);

Future<void> setMaxConcurrentSearches({required int limit}) =>
    RustLib.instance.api.crateApiConfigSetMaxConcurrentSearches(limit: limit);

Future<int> getMaxConcurrentSearches() =>
    RustLib.instance.api.crateApiConfigGetMaxConcurrentSearches();

/// Returns the user-configured DoH endpoint list (ordered, first = highest
/// priority). Empty means "no user override — use the compiled-in defaults".
Future<List<String>> getBangumiDohEndpoints() =>
    RustLib.instance.api.crateApiConfigGetBangumiDohEndpoints();

/// Replace the user-configured DoH endpoint list. Invalid entries (empty,
/// non-https, not a valid URL) are filtered out so we don't store something
/// we know is unusable. Invalidates the ECH client so the next request
/// rebuilds its rustls config with the new DoH list.
Future<void> setBangumiDohEndpoints({required List<String> endpoints}) =>
    RustLib.instance.api.crateApiConfigSetBangumiDohEndpoints(
      endpoints: endpoints,
    );

/// Append `endpoint` to the end of the user DoH list. Returns the new
/// length of the list. Returns 0 (and does nothing) when the endpoint is
/// not a valid https URL.
Future<BigInt> addBangumiDohEndpoint({required String endpoint}) => RustLib
    .instance
    .api
    .crateApiConfigAddBangumiDohEndpoint(endpoint: endpoint);

/// Remove every occurrence of `endpoint` (exact match after normalisation)
/// from the user DoH list. Returns the new length of the list.
Future<BigInt> removeBangumiDohEndpoint({required String endpoint}) => RustLib
    .instance
    .api
    .crateApiConfigRemoveBangumiDohEndpoint(endpoint: endpoint);

/// Move the entry currently at `from` to position `to`. Out-of-range indices
/// are clamped silently. No-op when `from == to`. Returns the resulting list
/// so the caller can echo it back to the UI.
Future<List<String>> moveBangumiDohEndpoint({
  required BigInt from,
  required BigInt to,
}) => RustLib.instance.api.crateApiConfigMoveBangumiDohEndpoint(
  from: from,
  to: to,
);

/// Reset the user DoH list back to empty (= "use compiled-in defaults").
Future<void> resetBangumiDohEndpoints() =>
    RustLib.instance.api.crateApiConfigResetBangumiDohEndpoints();

/// Rewrite a bangumi host from its canonical real form to the mirror form (when reverse
/// proxying is enabled), or vice-versa. Returns `None` if the host is not a bangumi host
/// we know about.
Future<String?> remapBangumiHost({
  required String host,
  required bool toMirror,
}) => RustLib.instance.api.crateApiConfigRemapBangumiHost(
  host: host,
  toMirror: toMirror,
);

/// Rewrite all bangumi hosts inside a URL. If `to_mirror` is true the URL is rewritten to
/// use the reverse-proxy host; if false it is rewritten back to the canonical real host.
/// Returns the input unchanged when the URL is not parseable or has no known bangumi host.
Future<String> rewriteBangumiUrl({
  required String raw,
  required bool toMirror,
}) => RustLib.instance.api.crateApiConfigRewriteBangumiUrl(
  raw: raw,
  toMirror: toMirror,
);
