// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_subject_details`, `atomic_write_bytes`, `bangumi_data_failure_marker_path`, `bangumi_data_version_marker_path`, `bgmlist_item_to_anime_info`, `build_light_subject_from_json`, `clear_failure_marker`, `datetime_to_cst_day_time`, `download_bangumi_data_json`, `ensure_sites_index_built`, `extract_bangumi_data_version_from_url`, `fetch_archive_list_api`, `fetch_archive_list_html`, `fetch_extra_bangumi_subjects`, `fetch_schedule_basic_api_from_url`, `fetch_schedule_basic_api`, `fetch_schedule_basic_from_local_data_json`, `fetch_schedule_basic_html`, `fetch_subject_details_next_p1_json`, `fetch_subject_details_rest_json`, `filter_items_by_quarter`, `is_legacy_mode`, `last_failure_age_secs`, `load_data_json_and_filter`, `normalize_next_subject_json`, `parse_begin_utc`, `parse_broadcast_from_rfc`, `parse_broadcast_parts`, `quarter_to_title`, `read_bangumi_data_json_mmap`, `read_bangumi_data_version_from_json`, `read_version_marker`, `replace_atomic`, `sites_index_slot`, `verify_bangumi_data_payload`, `write_failure_marker`, `write_version_marker`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ArchiveResponse`, `BangumiDataJson`, `BangumiDataSiteMeta`, `BgmlistItem`, `BgmlistSite`, `BgmlistTitleTranslate`, `SeasonListResponse`, `SitesIndex`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`, `default`

Future<List<ArchiveQuarter>> fetchArchiveList() =>
    RustLib.instance.api.crateApiCrawlerFetchArchiveList();

Future<List<AnimeInfo>> fetchScheduleBasic({required String yearQuarter}) =>
    RustLib.instance.api.crateApiCrawlerFetchScheduleBasic(
      yearQuarter: yearQuarter,
    );

/// Build the sites index from the cached JSON. Called on app startup and
/// whenever the JSON cache is refreshed. Parsing happens on a blocking
/// thread (mmap + serde_json are synchronous).
Future<BigInt> buildSitesIndex() =>
    RustLib.instance.api.crateApiCrawlerBuildSitesIndex();

/// Drop the in-memory index. Used when `bangumi-data.json` is replaced so
/// the next `build_sites_index` call rebuilds against the new payload.
Future<void> invalidateSitesIndex() =>
    RustLib.instance.api.crateApiCrawlerInvalidateSitesIndex();

/// FRB-exposed lookup. Returns an empty list when the index has not been
/// built yet (cold start, before warmup finishes) or when the bangumi id
/// is not present in bangumi-data — the Dart side renders nothing in
/// either case so callers don't have to distinguish.
Future<List<BangumiDataSiteEntry>> fetchBangumiDataSites({
  required PlatformInt64 bangumiId,
}) => RustLib.instance.api.crateApiCrawlerFetchBangumiDataSites(
  bangumiId: bangumiId,
);

/// Optional helper for mikan-origin entries that don't carry a bangumi id.
Future<List<BangumiDataSiteEntry>> fetchBangumiDataSitesByMikan({
  required PlatformInt64 mikanId,
}) => RustLib.instance.api.crateApiCrawlerFetchBangumiDataSitesByMikan(
  mikanId: mikanId,
);

/// Look up the mikan id for a given bangumi.tv subject id from the
/// cached bangumi-data index. Returns `None` when the index has not been
/// built yet or when the bangumi id has no mikan mapping.
Future<PlatformInt64?> lookupMikanId({required PlatformInt64 bangumiId}) =>
    RustLib.instance.api.crateApiCrawlerLookupMikanId(bangumiId: bangumiId);

Future<List<AnimeInfo>> fillAnimeDetails({required List<AnimeInfo> animes}) =>
    RustLib.instance.api.crateApiCrawlerFillAnimeDetails(animes: animes);

Future<AnimeInfo> fetchLightSubjectDetails({
  required PlatformInt64 subjectId,
}) => RustLib.instance.api.crateApiCrawlerFetchLightSubjectDetails(
  subjectId: subjectId,
);

Future<List<AnimeInfo>> fetchExtraSubjects({
  required String yearQuarter,
  required List<String> existingIds,
}) => RustLib.instance.api.crateApiCrawlerFetchExtraSubjects(
  yearQuarter: yearQuarter,
  existingIds: existingIds,
);

Future<BangumiDataCacheStatus> getBangumiDataCacheStatus() =>
    RustLib.instance.api.crateApiCrawlerGetBangumiDataCacheStatus();

Future<bool> refreshBangumiDataCache() =>
    RustLib.instance.api.crateApiCrawlerRefreshBangumiDataCache();

/// Ensure the offline `bangumi-data.json` cache is present and fresh. Downloads
/// only when the file is missing or its mtime is older than `max_age_secs`, so
/// the ~7 MB payload is not re-fetched on every startup. Returns `true` when a
/// download actually happened. Safe to call from app startup.
///
/// Transient CDN failure handling: when the last warmup attempt failed we
/// drop a sidecar file with the failure timestamp. While that marker is
/// fresher than `BANGUMI_DATA_RETRY_AFTER_SECS` AND the on-disk cache still
/// exists (even if stale), we skip the download so we don't hammer the CDN
/// every startup. As soon as `BANGUMI_DATA_RETRY_AFTER_SECS` has elapsed
/// — *or* the cache is missing — the next call retries.
Future<bool> ensureBangumiDataCache({required BigInt maxAgeSecs}) => RustLib
    .instance
    .api
    .crateApiCrawlerEnsureBangumiDataCache(maxAgeSecs: maxAgeSecs);

class AnimeInfo {
  final String title;
  final String? subTitle;
  final String? bangumiId;
  final String? mikanId;
  final String? coverUrl;
  final String? siteUrl;
  final String? broadcastDay;
  final String? broadcastTime;
  final double? score;
  final int? rank;
  final List<String> tags;
  final String? fullJson;

  const AnimeInfo({
    required this.title,
    this.subTitle,
    this.bangumiId,
    this.mikanId,
    this.coverUrl,
    this.siteUrl,
    this.broadcastDay,
    this.broadcastTime,
    this.score,
    this.rank,
    required this.tags,
    this.fullJson,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      subTitle.hashCode ^
      bangumiId.hashCode ^
      mikanId.hashCode ^
      coverUrl.hashCode ^
      siteUrl.hashCode ^
      broadcastDay.hashCode ^
      broadcastTime.hashCode ^
      score.hashCode ^
      rank.hashCode ^
      tags.hashCode ^
      fullJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnimeInfo &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          subTitle == other.subTitle &&
          bangumiId == other.bangumiId &&
          mikanId == other.mikanId &&
          coverUrl == other.coverUrl &&
          siteUrl == other.siteUrl &&
          broadcastDay == other.broadcastDay &&
          broadcastTime == other.broadcastTime &&
          score == other.score &&
          rank == other.rank &&
          tags == other.tags &&
          fullJson == other.fullJson;
}

class ArchiveQuarter {
  final String year;
  final String quarter;
  final String title;

  const ArchiveQuarter({
    required this.year,
    required this.quarter,
    required this.title,
  });

  @override
  int get hashCode => year.hashCode ^ quarter.hashCode ^ title.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArchiveQuarter &&
          runtimeType == other.runtimeType &&
          year == other.year &&
          quarter == other.quarter &&
          title == other.title;
}

class BangumiDataCacheStatus {
  final bool cached;
  final BigInt fileSize;
  final BigInt? lastModifiedSecs;
  final String version;
  final BigInt? lastFailedSecs;

  const BangumiDataCacheStatus({
    required this.cached,
    required this.fileSize,
    this.lastModifiedSecs,
    required this.version,
    this.lastFailedSecs,
  });

  @override
  int get hashCode =>
      cached.hashCode ^
      fileSize.hashCode ^
      lastModifiedSecs.hashCode ^
      version.hashCode ^
      lastFailedSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BangumiDataCacheStatus &&
          runtimeType == other.runtimeType &&
          cached == other.cached &&
          fileSize == other.fileSize &&
          lastModifiedSecs == other.lastModifiedSecs &&
          version == other.version &&
          lastFailedSecs == other.lastFailedSecs;
}

/// One site of a bangumi-data entry, resolved (URL template filled in) and
/// safe to expose to Dart via flutter_rust_bridge.
class BangumiDataSiteEntry {
  final String site;
  final String title;
  final String url;
  final String kind;
  final String? comment;

  const BangumiDataSiteEntry({
    required this.site,
    required this.title,
    required this.url,
    required this.kind,
    this.comment,
  });

  @override
  int get hashCode =>
      site.hashCode ^
      title.hashCode ^
      url.hashCode ^
      kind.hashCode ^
      comment.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BangumiDataSiteEntry &&
          runtimeType == other.runtimeType &&
          site == other.site &&
          title == other.title &&
          url == other.url &&
          kind == other.kind &&
          comment == other.comment;
}
