// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_signed_headers`, `extract_url_path`, `generate_signature`, `parse_danmaku_comment`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BangumiDetail`, `BangumiResponse`, `BangumiTvDetail`, `BangumiTvEpisodeApi`, `BangumiTvResponse`, `DanmakuComment`, `DanmakuResponse`, `EpisodeApi`, `MatchResponse`, `MatchResultApi`, `SearchAnimeApi`, `SearchResponse`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// 搜索动画
///
/// # 参数
/// - `keyword`: 搜索关键词
///
/// # 返回
/// 匹配的动画列表
Future<List<DanmakuAnime>> danmakuSearchAnime({required String keyword}) =>
    RustLib.instance.api.crateApiDanmakuDanmakuSearchAnime(keyword: keyword);

/// 获取动画剧集列表
///
/// # 参数
/// - `anime_id`: 动画ID (从搜索结果获取)
///
/// # 返回
/// 剧集列表
Future<List<DanmakuEpisode>> danmakuGetEpisodes({
  required PlatformInt64 animeId,
}) => RustLib.instance.api.crateApiDanmakuDanmakuGetEpisodes(animeId: animeId);

/// 通过 Bangumi TV subject_id 获取剧集列表
///
/// # 参数
/// - `subject_id`: Bangumi TV 的 subject_id (例如: 517057)
///
/// # 返回
/// 剧集列表
Future<List<BangumiTvEpisode>> danmakuGetBangumiEpisodes({
  required PlatformInt64 subjectId,
}) => RustLib.instance.api.crateApiDanmakuDanmakuGetBangumiEpisodes(
  subjectId: subjectId,
);

/// 获取弹幕列表
///
/// # 参数
/// - `episode_id`: 剧集ID (从剧集列表或匹配结果获取)
///
/// # 返回
/// 弹幕列表，按时间排序
Future<List<Danmaku>> danmakuGetComments({required PlatformInt64 episodeId}) =>
    RustLib.instance.api.crateApiDanmakuDanmakuGetComments(
      episodeId: episodeId,
    );

/// 通过文件名匹配动画
///
/// # 参数
/// - `file_name`: 视频文件名
/// - `file_hash`: 可选的文件hash (前16MB的MD5)
///
/// # 返回
/// 匹配结果列表，可能为空
Future<List<DanmakuMatch>> danmakuMatchAnime({
  required String fileName,
  String? fileHash,
}) => RustLib.instance.api.crateApiDanmakuDanmakuMatchAnime(
  fileName: fileName,
  fileHash: fileHash,
);

/// 便捷方法：通过动画名称和集数获取弹幕
///
/// # 参数
/// - `anime_title`: 动画标题
/// - `episode_number`: 集数编号 (例如: "1", "2")
/// - `relative_episode`: 相对集号 (1-based 索引，作为回退)
///
/// # 返回
/// 弹幕列表，如果找不到则返回空列表
Future<List<Danmaku>> danmakuGetByTitle({
  required String animeTitle,
  required String episodeNumber,
  int? relativeEpisode,
}) => RustLib.instance.api.crateApiDanmakuDanmakuGetByTitle(
  animeTitle: animeTitle,
  episodeNumber: episodeNumber,
  relativeEpisode: relativeEpisode,
);

/// 便捷方法：通过 Bangumi TV subject_id 和集数获取弹幕
///
/// # 参数
/// - `subject_id`: Bangumi TV 的 subject_id
/// - `episode_number`: 集数编号 (例如: "1", "2", "SP1" 等)
/// - `relative_episode`: 相对集号 (1-based 索引，作为回退)
///
/// # 返回
/// 弹幕列表，如果找不到则返回空列表
Future<List<Danmaku>> danmakuGetByBangumiId({
  required PlatformInt64 subjectId,
  required String episodeNumber,
  int? relativeEpisode,
}) => RustLib.instance.api.crateApiDanmakuDanmakuGetByBangumiId(
  subjectId: subjectId,
  episodeNumber: episodeNumber,
  relativeEpisode: relativeEpisode,
);

/// Bangumi TV 剧集信息 (从 Dandanplay Bangumi API 获取)
class BangumiTvEpisode {
  /// 剧集ID (用于获取弹幕)
  final PlatformInt64 episodeId;

  /// 剧集标题
  final String episodeTitle;

  /// 剧集编号
  final String episodeNumber;

  /// 播放日期
  final String? airDate;

  const BangumiTvEpisode({
    required this.episodeId,
    required this.episodeTitle,
    required this.episodeNumber,
    this.airDate,
  });

  @override
  int get hashCode =>
      episodeId.hashCode ^
      episodeTitle.hashCode ^
      episodeNumber.hashCode ^
      airDate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BangumiTvEpisode &&
          runtimeType == other.runtimeType &&
          episodeId == other.episodeId &&
          episodeTitle == other.episodeTitle &&
          episodeNumber == other.episodeNumber &&
          airDate == other.airDate;
}

/// 弹幕数据
class Danmaku {
  /// 弹幕出现时间（秒）
  final double time;

  /// 弹幕类型: 1-3 滚动, 4 底部, 5 顶部
  final int danmakuType;

  /// 弹幕颜色 (RGB 整数值)
  final int color;

  /// 弹幕内容
  final String text;

  const Danmaku({
    required this.time,
    required this.danmakuType,
    required this.color,
    required this.text,
  });

  @override
  int get hashCode =>
      time.hashCode ^ danmakuType.hashCode ^ color.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Danmaku &&
          runtimeType == other.runtimeType &&
          time == other.time &&
          danmakuType == other.danmakuType &&
          color == other.color &&
          text == other.text;
}

/// 搜索结果中的动画
class DanmakuAnime {
  /// 动画ID
  final PlatformInt64 animeId;

  /// 动画标题
  final String animeTitle;

  /// 动画类型
  final String animeType;

  /// 类型描述
  final String? typeDescription;

  /// 封面图 URL
  final String? imageUrl;

  const DanmakuAnime({
    required this.animeId,
    required this.animeTitle,
    required this.animeType,
    this.typeDescription,
    this.imageUrl,
  });

  @override
  int get hashCode =>
      animeId.hashCode ^
      animeTitle.hashCode ^
      animeType.hashCode ^
      typeDescription.hashCode ^
      imageUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DanmakuAnime &&
          runtimeType == other.runtimeType &&
          animeId == other.animeId &&
          animeTitle == other.animeTitle &&
          animeType == other.animeType &&
          typeDescription == other.typeDescription &&
          imageUrl == other.imageUrl;
}

/// 剧集信息
class DanmakuEpisode {
  /// 剧集ID (用于获取弹幕)
  final PlatformInt64 episodeId;

  /// 剧集标题
  final String episodeTitle;

  /// 剧集编号
  final String? episodeNumber;

  const DanmakuEpisode({
    required this.episodeId,
    required this.episodeTitle,
    this.episodeNumber,
  });

  @override
  int get hashCode =>
      episodeId.hashCode ^ episodeTitle.hashCode ^ episodeNumber.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DanmakuEpisode &&
          runtimeType == other.runtimeType &&
          episodeId == other.episodeId &&
          episodeTitle == other.episodeTitle &&
          episodeNumber == other.episodeNumber;
}

/// 匹配结果
class DanmakuMatch {
  /// 剧集ID
  final PlatformInt64 episodeId;

  /// 动画ID
  final PlatformInt64 animeId;

  /// 动画标题
  final String animeTitle;

  /// 剧集标题
  final String episodeTitle;

  const DanmakuMatch({
    required this.episodeId,
    required this.animeId,
    required this.animeTitle,
    required this.episodeTitle,
  });

  @override
  int get hashCode =>
      episodeId.hashCode ^
      animeId.hashCode ^
      animeTitle.hashCode ^
      episodeTitle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DanmakuMatch &&
          runtimeType == other.runtimeType &&
          episodeId == other.episodeId &&
          animeId == other.animeId &&
          animeTitle == other.animeTitle &&
          episodeTitle == other.episodeTitle;
}
