// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_ech_config`, `current_ech_config`, `doh_endpoints`, `ensure_fresh_ech_config`, `extract_ech_param`, `fetch_from_single_doh`, `has_ech_config`, `is_cache_entry_fresh`, `mark_failed`, `parse_echconfig_from_https_svcb`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CachedEch`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Fetch (or return cached) Cloudflare ECHConfig bytes.
///
/// Returns `None` on any failure (all DoH endpoints unreachable, no HTTPS RR,
/// parse error). Backed off after a failure to avoid hammering the DoH
/// endpoints.
Future<Uint8List> fetchCloudflareEchBytes() =>
    RustLib.instance.api.crateApiEchFetchCloudflareEchBytes();

/// Force-refresh the cached ECHConfig (e.g. from the settings UI).
Future<BigInt> refreshBangumiEchConfig() =>
    RustLib.instance.api.crateApiEchRefreshBangumiEchConfig();
