// Hand-written barrel that keeps the historical Dart import path
// `package:mikan_player/src/rust/api/generic_scraper.dart` stable even though
// the underlying FRB bindings now live under `lib/src/rust/frb_api/`.
//
// The generic_scraper implementation domain is no longer scanned directly,
// so this file is NOT regenerated by `flutter_rust_bridge_codegen`. Do not
// replace it with auto-generated boilerplate; update it only when the barrel
// changes.

export '../frb_api/generic_scraper.dart';
export 'generic_scraper/types.dart';
