// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `absolutize_url`, `apply_browser_page_headers`, `apply_cookie_header`, `build_episode_table_cache`, `build_search_candidates`, `calculate_match_score`, `current_region_option`, `current_timestamp_ms`, `detect_and_filter_root`, `detect_current_region_once`, `detect_current_region_with_retry`, `detect_current_region`, `extract_channel_name`, `extract_core_name`, `extract_episode_number_from_text`, `filter_restricted_sources`, `filter_root_by_region`, `generic_search_and_play_internal`, `get_cache_file_path`, `get_episode_cache_dir`, `get_episode_cache_path`, `hash_str`, `is_expired`, `load_enabled_sources`, `load_episode_table_cache`, `load_from_cache`, `load_playback_source_config`, `log_subject_selection`, `merge_cookie_strings`, `normalize_region`, `parse_chinese_number`, `parse_episode_table_from_detail`, `preprocess_search_term`, `save_episode_table_cache`, `save_to_cache`, `search_single_source_with_channels`, `search_single_source_with_progress`, `search_single_source`, `select_best_subject_candidate`, `select_episode_by_number`, `select_episode_from_table`, `source_config_hash`, `source_is_restricted`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CACHED_SOURCE_CONFIG`, `CURRENT_REGION`, `CachedEpisodeTable`, `CachedSourceConfig`, `CaptchaConfig`, `ExportedMediaSourceDataList`, `MatchVideo`, `MediaSource`, `OcrConstraints`, `REGION_DETECTION_ATTEMPTED`, `REGION_DETECTION_MUTEX`, `SEASON_RE`, `SampleRoot`, `SearchConfig`, `SelectorChannelFormatFlattened`, `SelectorChannelFormatNoChannel`, `SelectorSubjectFormatA`, `SelectorSubjectFormatIndexed`, `SourceArguments`, `SubjectCandidate`, `SubjectSelectionResult`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `deref`, `deref`, `deref`, `deref`, `deref`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `initialize`, `initialize`, `initialize`, `initialize`, `initialize`

/// Invalidate the in-memory source config cache so the next
/// `load_enabled_sources` call will re-read from disk.
Future<void> invalidateSourceConfigCache() =>
    RustLib.instance.api.crateApiGenericScraperInvalidateSourceConfigCache();

/// 从订阅地址刷新播放源配置并保存到本地缓存
Future<String> refreshPlaybackSourceConfig() =>
    RustLib.instance.api.crateApiGenericScraperRefreshPlaybackSourceConfig();

/// 预加载播放源配置（应用启动时调用）
/// 尝试从本地缓存加载配置，如果缓存不存在则从订阅地址拉取
Future<void> preloadPlaybackSources() =>
    RustLib.instance.api.crateApiGenericScraperPreloadPlaybackSources();

/// 获取所有播放源的状态
Future<List<SourceState>> getPlaybackSources() =>
    RustLib.instance.api.crateApiGenericScraperGetPlaybackSources();

/// 更新单个源的配置
Future<void> updateSingleSourceConfig({required SourceConfigUpdate update}) =>
    RustLib.instance.api.crateApiGenericScraperUpdateSingleSourceConfig(
      update: update,
    );

/// 添加新的源配置
Future<void> addSourceConfig({required SourceConfigUpdate newConfig}) => RustLib
    .instance
    .api
    .crateApiGenericScraperAddSourceConfig(newConfig: newConfig);

/// 搜索所有源，返回所有找到的播放页面URL列表
/// Flutter 端可以使用 WebView 加载这些 URL 来拦截视频请求
///
/// # 参数
/// * `anime_name` - 动画名称
/// * `absolute_episode` - 绝对集号（如第15集），优先匹配
/// * `relative_episode` - 相对集号（如当季第3集），绝对集号找不到时回退使用
Future<List<SearchPlayResult>> genericSearchPlayPages({
  required String animeName,
  int? absoluteEpisode,
  int? relativeEpisode,
}) => RustLib.instance.api.crateApiGenericScraperGenericSearchPlayPages(
  animeName: animeName,
  absoluteEpisode: absoluteEpisode,
  relativeEpisode: relativeEpisode,
);

/// 搜索所有源，以流的形式返回结果（每个源搜索完成后立即返回）
/// 这样可以让UI实时显示搜索结果，而不是等所有源都搜索完毕
Stream<SearchPlayResult> genericSearchPlayPagesStream({
  required String animeName,
  int? absoluteEpisode,
  int? relativeEpisode,
}) => RustLib.instance.api.crateApiGenericScraperGenericSearchPlayPagesStream(
  animeName: animeName,
  absoluteEpisode: absoluteEpisode,
  relativeEpisode: relativeEpisode,
);

/// 获取所有已启用源的列表（用于初始化UI显示）
Future<List<String>> getEnabledSourceNames() =>
    RustLib.instance.api.crateApiGenericScraperGetEnabledSourceNames();

/// 搜索所有源，以流的形式返回详细进度（包含搜索步骤和错误信息）
Stream<SourceSearchProgress> genericSearchWithProgress({
  required String animeName,
  int? absoluteEpisode,
  int? relativeEpisode,
}) => RustLib.instance.api.crateApiGenericScraperGenericSearchWithProgress(
  animeName: animeName,
  absoluteEpisode: absoluteEpisode,
  relativeEpisode: relativeEpisode,
);

/// 搜索指定源，以流的形式返回详细进度
///
/// # 参数
/// * `target_source_names` - 目标源名称列表。为 None 或空时搜索所有已启用源；
///   非空时只搜索列表中列出的源，跳过不在列表中的源（不创建 skip 异步任务）。
/// * `runtime_overrides` - 运行时覆盖，仅对列表中的源生效。
Stream<SourceSearchProgress> genericSearchWithProgressRuntime({
  required String animeName,
  int? absoluteEpisode,
  int? relativeEpisode,
  List<String>? targetSourceNames,
  required List<SourceRuntimeOverride> runtimeOverrides,
}) =>
    RustLib.instance.api.crateApiGenericScraperGenericSearchWithProgressRuntime(
      animeName: animeName,
      absoluteEpisode: absoluteEpisode,
      relativeEpisode: relativeEpisode,
      targetSourceNames: targetSourceNames,
      runtimeOverrides: runtimeOverrides,
    );

/// 调试用途：从本地 JSON 文件加载播放源配置并执行搜索
///
/// 说明：
/// - 只读取指定本地 JSON 文件，不读取也不写入缓存文件
/// - 不修改订阅设置，不影响正式播放流程
/// - 可选按源名称过滤（大小写不敏感，包含匹配）
Stream<SourceSearchProgress> debugSearchWithLocalJson({
  required String jsonPath,
  required String animeName,
  int? absoluteEpisode,
  int? relativeEpisode,
  String? sourceNameFilter,
}) => RustLib.instance.api.crateApiGenericScraperDebugSearchWithLocalJson(
  jsonPath: jsonPath,
  animeName: animeName,
  absoluteEpisode: absoluteEpisode,
  relativeEpisode: relativeEpisode,
  sourceNameFilter: sourceNameFilter,
);

Stream<SourceSearchProgress> debugSearchWithLocalJsonRuntime({
  required String jsonPath,
  required String animeName,
  int? absoluteEpisode,
  int? relativeEpisode,
  String? sourceNameFilter,
  required List<SourceRuntimeOverride> runtimeOverrides,
}) =>
    RustLib.instance.api.crateApiGenericScraperDebugSearchWithLocalJsonRuntime(
      jsonPath: jsonPath,
      animeName: animeName,
      absoluteEpisode: absoluteEpisode,
      relativeEpisode: relativeEpisode,
      sourceNameFilter: sourceNameFilter,
      runtimeOverrides: runtimeOverrides,
    );

/// 搜索并播放动画（支持集号选择）
///
/// # 参数
/// * `anime_name` - 动画名称
/// * `absolute_episode` - 绝对集号（如第15集），优先匹配
/// * `relative_episode` - 相对集号（如当季第3集），绝对集号找不到时回退使用
Future<String> genericSearchAndPlayWithEpisode({
  required String animeName,
  int? absoluteEpisode,
  int? relativeEpisode,
}) =>
    RustLib.instance.api.crateApiGenericScraperGenericSearchAndPlayWithEpisode(
      animeName: animeName,
      absoluteEpisode: absoluteEpisode,
      relativeEpisode: relativeEpisode,
    );

/// 搜索并播放动画（默认第一集，保持向后兼容）
Future<String> genericSearchAndPlay({required String animeName}) => RustLib
    .instance
    .api
    .crateApiGenericScraperGenericSearchAndPlay(animeName: animeName);

/// 搜索所有源，返回包含多channel信息的完整结果
/// 此API用于UI展示所有可用的线路和剧集供用户选择
Future<List<SearchResultWithChannels>> genericSearchWithChannels({
  required String animeName,
}) => RustLib.instance.api.crateApiGenericScraperGenericSearchWithChannels(
  animeName: animeName,
);

/// 搜索所有源，以流的形式返回包含多channel信息的结果
Stream<SearchResultWithChannels> genericSearchWithChannelsStream({
  required String animeName,
}) =>
    RustLib.instance.api.crateApiGenericScraperGenericSearchWithChannelsStream(
      animeName: animeName,
    );

/// 根据指定的channel和集号获取播放页面URL
/// 此API用于在用户选择了具体的线路和集数后获取播放页面
Future<SearchPlayResult> getEpisodePlayUrl({
  required String sourceName,
  required String animeName,
  required BigInt channelIndex,
  int? episodeNumber,
  SourceRuntimeOverride? runtimeOverride,
}) => RustLib.instance.api.crateApiGenericScraperGetEpisodePlayUrl(
  sourceName: sourceName,
  animeName: animeName,
  channelIndex: channelIndex,
  episodeNumber: episodeNumber,
  runtimeOverride: runtimeOverride,
);

/// 修复被混淆的视频URL
/// 某些网站会对URL做简单的字符替换混淆：n->o, l->m, 域名中的.->/
/// 尝试从页面中解析 player_aaaa 变量并提取视频 URL
/// 这是很多视频网站使用的通用模式，视频URL存储在一个JS变量中
/// Channel（线路）信息
class ChannelInfo {
  /// Channel 名称（如"线路A"、"简中"、"繁中"等）
  final String name;

  /// Channel 索引
  final BigInt index;

  const ChannelInfo({required this.name, required this.index});

  @override
  int get hashCode => name.hashCode ^ index.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChannelInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          index == other.index;
}

/// 剧集信息
class EpisodeInfo {
  /// 剧集名称/标题
  final String name;

  /// 剧集URL
  final String url;

  /// 剧集号（如果能解析出来）
  final int? episodeNumber;

  /// 所属channel索引
  final BigInt channelIndex;

  const EpisodeInfo({
    required this.name,
    required this.url,
    this.episodeNumber,
    required this.channelIndex,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      url.hashCode ^
      episodeNumber.hashCode ^
      channelIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EpisodeInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          url == other.url &&
          episodeNumber == other.episodeNumber &&
          channelIndex == other.channelIndex;
}

/// 搜索结果：包含播放页面URL和视频URL匹配正则
class SearchPlayResult {
  /// 源名称
  final String sourceName;

  /// 播放页面 URL
  final String playPageUrl;

  /// 用于匹配视频URL的正则表达式
  final String videoRegex;

  /// 直接解析得到的视频URL（如果有）
  final String? directVideoUrl;

  /// 播放所需的 Cookie
  final String? cookies;

  /// 播放所需的 Headers (Referer, User-Agent etc)
  final Map<String, String>? headers;

  /// Channel 名称（如果有多channel）
  final String? channelName;

  /// Channel 索引
  final BigInt? channelIndex;

  /// 验证码配置JSON（如果该源启用了captcha绕过）
  final String? captchaConfigJson;

  /// 是否启用嵌套URL匹配
  final bool enableNestedUrl;

  /// 嵌套URL匹配正则
  final String? matchNestedUrl;

  const SearchPlayResult({
    required this.sourceName,
    required this.playPageUrl,
    required this.videoRegex,
    this.directVideoUrl,
    this.cookies,
    this.headers,
    this.channelName,
    this.channelIndex,
    this.captchaConfigJson,
    required this.enableNestedUrl,
    this.matchNestedUrl,
  });

  @override
  int get hashCode =>
      sourceName.hashCode ^
      playPageUrl.hashCode ^
      videoRegex.hashCode ^
      directVideoUrl.hashCode ^
      cookies.hashCode ^
      headers.hashCode ^
      channelName.hashCode ^
      channelIndex.hashCode ^
      captchaConfigJson.hashCode ^
      enableNestedUrl.hashCode ^
      matchNestedUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchPlayResult &&
          runtimeType == other.runtimeType &&
          sourceName == other.sourceName &&
          playPageUrl == other.playPageUrl &&
          videoRegex == other.videoRegex &&
          directVideoUrl == other.directVideoUrl &&
          cookies == other.cookies &&
          headers == other.headers &&
          channelName == other.channelName &&
          channelIndex == other.channelIndex &&
          captchaConfigJson == other.captchaConfigJson &&
          enableNestedUrl == other.enableNestedUrl &&
          matchNestedUrl == other.matchNestedUrl;
}

/// 包含多channel信息的搜索结果
class SearchResultWithChannels {
  /// 源名称
  final String sourceName;

  /// 动画详情页URL
  final String detailUrl;

  /// 匹配到的动画名称
  final String matchedTitle;

  /// 所有可用的channels（线路）
  final List<ChannelInfo> channels;

  /// 所有剧集列表（按channel分组）
  final List<EpisodeInfo> episodes;

  /// 用于匹配视频URL的正则表达式
  final String videoRegex;

  /// 播放所需的 Cookie
  final String? cookies;

  /// 播放所需的 Headers
  final Map<String, String>? headers;

  /// 默认字幕语言
  final String? defaultSubtitleLanguage;

  /// 默认分辨率
  final String? defaultResolution;

  const SearchResultWithChannels({
    required this.sourceName,
    required this.detailUrl,
    required this.matchedTitle,
    required this.channels,
    required this.episodes,
    required this.videoRegex,
    this.cookies,
    this.headers,
    this.defaultSubtitleLanguage,
    this.defaultResolution,
  });

  @override
  int get hashCode =>
      sourceName.hashCode ^
      detailUrl.hashCode ^
      matchedTitle.hashCode ^
      channels.hashCode ^
      episodes.hashCode ^
      videoRegex.hashCode ^
      cookies.hashCode ^
      headers.hashCode ^
      defaultSubtitleLanguage.hashCode ^
      defaultResolution.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchResultWithChannels &&
          runtimeType == other.runtimeType &&
          sourceName == other.sourceName &&
          detailUrl == other.detailUrl &&
          matchedTitle == other.matchedTitle &&
          channels == other.channels &&
          episodes == other.episodes &&
          videoRegex == other.videoRegex &&
          cookies == other.cookies &&
          headers == other.headers &&
          defaultSubtitleLanguage == other.defaultSubtitleLanguage &&
          defaultResolution == other.defaultResolution;
}

/// 搜索进度状态
enum SearchStep {
  /// 等待中
  pending,

  /// 正在搜索
  searching,

  /// 正在获取详情页
  fetchingDetail,

  /// 正在获取剧集列表
  fetchingEpisodes,

  /// 正在提取视频URL
  extractingVideo,

  /// 搜索成功
  success,

  /// 搜索失败
  failed,
}

class SourceConfigUpdate {
  final String name;
  final String? newName;
  final int? tier;
  final String? defaultSubtitleLanguage;
  final String? defaultResolution;
  final String? searchUrl;
  final String? iconUrl;
  final String? description;
  final String? searchConfigJson;
  final String? captchaConfigJson;

  const SourceConfigUpdate({
    required this.name,
    this.newName,
    this.tier,
    this.defaultSubtitleLanguage,
    this.defaultResolution,
    this.searchUrl,
    this.iconUrl,
    this.description,
    this.searchConfigJson,
    this.captchaConfigJson,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      newName.hashCode ^
      tier.hashCode ^
      defaultSubtitleLanguage.hashCode ^
      defaultResolution.hashCode ^
      searchUrl.hashCode ^
      iconUrl.hashCode ^
      description.hashCode ^
      searchConfigJson.hashCode ^
      captchaConfigJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceConfigUpdate &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          newName == other.newName &&
          tier == other.tier &&
          defaultSubtitleLanguage == other.defaultSubtitleLanguage &&
          defaultResolution == other.defaultResolution &&
          searchUrl == other.searchUrl &&
          iconUrl == other.iconUrl &&
          description == other.description &&
          searchConfigJson == other.searchConfigJson &&
          captchaConfigJson == other.captchaConfigJson;
}

class SourceRuntimeOverride {
  final String sourceName;
  final String? cookies;
  final String? searchPageHtml;
  final String? searchPageUrl;
  final String? detailPageHtml;
  final String? detailPageUrl;
  final String? skipSearchError;

  const SourceRuntimeOverride({
    required this.sourceName,
    this.cookies,
    this.searchPageHtml,
    this.searchPageUrl,
    this.detailPageHtml,
    this.detailPageUrl,
    this.skipSearchError,
  });

  @override
  int get hashCode =>
      sourceName.hashCode ^
      cookies.hashCode ^
      searchPageHtml.hashCode ^
      searchPageUrl.hashCode ^
      detailPageHtml.hashCode ^
      detailPageUrl.hashCode ^
      skipSearchError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceRuntimeOverride &&
          runtimeType == other.runtimeType &&
          sourceName == other.sourceName &&
          cookies == other.cookies &&
          searchPageHtml == other.searchPageHtml &&
          searchPageUrl == other.searchPageUrl &&
          detailPageHtml == other.detailPageHtml &&
          detailPageUrl == other.detailPageUrl &&
          skipSearchError == other.skipSearchError;
}

/// 带状态的搜索进度
class SourceSearchProgress {
  /// 源名称
  final String sourceName;

  /// 当前搜索步骤
  final SearchStep step;

  /// 错误信息（如果有）
  final String? error;

  /// 播放页面 URL（如果找到）
  final String? playPageUrl;

  /// 用于匹配视频URL的正则表达式
  final String? videoRegex;

  /// 直接解析得到的视频URL（如果有）
  final String? directVideoUrl;

  /// 播放所需的 Cookie
  final String? cookies;

  /// 播放所需的 Headers
  final Map<String, String>? headers;

  /// Channel 名称（如果有多channel）
  final String? channelName;

  /// Channel 索引
  final BigInt? channelIndex;

  /// 所有可用的channels（搜索成功时填充）
  final List<ChannelInfo>? allChannels;

  /// 验证码配置JSON（如果该源启用了captcha绕过）
  final String? captchaConfigJson;

  /// 是否启用嵌套URL匹配
  final bool enableNestedUrl;

  /// 嵌套URL匹配正则
  final String? matchNestedUrl;

  const SourceSearchProgress({
    required this.sourceName,
    required this.step,
    this.error,
    this.playPageUrl,
    this.videoRegex,
    this.directVideoUrl,
    this.cookies,
    this.headers,
    this.channelName,
    this.channelIndex,
    this.allChannels,
    this.captchaConfigJson,
    required this.enableNestedUrl,
    this.matchNestedUrl,
  });

  @override
  int get hashCode =>
      sourceName.hashCode ^
      step.hashCode ^
      error.hashCode ^
      playPageUrl.hashCode ^
      videoRegex.hashCode ^
      directVideoUrl.hashCode ^
      cookies.hashCode ^
      headers.hashCode ^
      channelName.hashCode ^
      channelIndex.hashCode ^
      allChannels.hashCode ^
      captchaConfigJson.hashCode ^
      enableNestedUrl.hashCode ^
      matchNestedUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceSearchProgress &&
          runtimeType == other.runtimeType &&
          sourceName == other.sourceName &&
          step == other.step &&
          error == other.error &&
          playPageUrl == other.playPageUrl &&
          videoRegex == other.videoRegex &&
          directVideoUrl == other.directVideoUrl &&
          cookies == other.cookies &&
          headers == other.headers &&
          channelName == other.channelName &&
          channelIndex == other.channelIndex &&
          allChannels == other.allChannels &&
          captchaConfigJson == other.captchaConfigJson &&
          enableNestedUrl == other.enableNestedUrl &&
          matchNestedUrl == other.matchNestedUrl;
}

class SourceState {
  final String name;
  final String description;
  final String iconUrl;
  final int tier;
  final String defaultSubtitleLanguage;
  final String defaultResolution;
  final String searchUrl;
  final String searchConfigJson;
  final String? captchaConfigJson;
  final bool enabled;

  const SourceState({
    required this.name,
    required this.description,
    required this.iconUrl,
    required this.tier,
    required this.defaultSubtitleLanguage,
    required this.defaultResolution,
    required this.searchUrl,
    required this.searchConfigJson,
    this.captchaConfigJson,
    required this.enabled,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      description.hashCode ^
      iconUrl.hashCode ^
      tier.hashCode ^
      defaultSubtitleLanguage.hashCode ^
      defaultResolution.hashCode ^
      searchUrl.hashCode ^
      searchConfigJson.hashCode ^
      captchaConfigJson.hashCode ^
      enabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceState &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          iconUrl == other.iconUrl &&
          tier == other.tier &&
          defaultSubtitleLanguage == other.defaultSubtitleLanguage &&
          defaultResolution == other.defaultResolution &&
          searchUrl == other.searchUrl &&
          searchConfigJson == other.searchConfigJson &&
          captchaConfigJson == other.captchaConfigJson &&
          enabled == other.enabled;
}
