// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `extract_episode`, `get_mikan_expand_urls`, `levenshtein`, `parse_mikan_resources_from_html`, `similarity`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SEASON_RE`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `deref`, `fmt`, `fmt`, `initialize`

Future<MikanSearchResult?> searchMikanAnime({required String nameCn}) =>
    RustLib.instance.api.crateApiMikanSearchMikanAnime(nameCn: nameCn);

Future<List<MikanEpisodeResource>> getMikanResources({
  required String mikanId,
  required int currentEpisodeSort,
}) => RustLib.instance.api.crateApiMikanGetMikanResources(
  mikanId: mikanId,
  currentEpisodeSort: currentEpisodeSort,
);

class MikanEpisodeResource {
  final String title;
  final String magnet;
  final String size;
  final String updateTime;
  final int? episode;

  const MikanEpisodeResource({
    required this.title,
    required this.magnet,
    required this.size,
    required this.updateTime,
    this.episode,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      magnet.hashCode ^
      size.hashCode ^
      updateTime.hashCode ^
      episode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MikanEpisodeResource &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          magnet == other.magnet &&
          size == other.size &&
          updateTime == other.updateTime &&
          episode == other.episode;
}

class MikanSearchResult {
  final String id;
  final String name;
  final String imageUrl;

  const MikanSearchResult({
    required this.id,
    required this.name,
    required this.imageUrl,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ imageUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MikanSearchResult &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          imageUrl == other.imageUrl;
}
