// Hand-written barrel that keeps the historical Dart import path
// `package:mikan_player/src/rust/api/network.dart` stable even though
// the underlying FRB bindings now live under `lib/src/rust/frb_api/`.
//
// Only `get_system_proxy` is exported to Dart. The old FRB-generated file
// also exposed internal network helpers (`getSharedClient`,
// `invalidateEchClient`, `getEchClient`, `clientForBangumi`,
// `selectClient`) whose `&'static Client` returns were mistranslated to
// `Future<void>`. They are deliberately NOT re-exported here.
//
// The network implementation domain is no longer scanned directly, so this
// file is NOT regenerated by `flutter_rust_bridge_codegen`. Do not replace it
// with auto-generated boilerplate; update it only when the barrel changes.

export '../frb_api/network.dart';
