// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bangumi_id_from_href`, `build_air_date_filter`, `build_api_subject_filter`, `build_subject_info`, `deduplicate_ranking_results`, `extract_air_date`, `extract_episode_count`, `extract_infobox_value`, `fetch_bangumi_browser_api`, `fetch_bangumi_browser_html`, `fetch_bangumi_search_api`, `fetch_bangumi_subjects_v0`, `fetch_bangumi_trending_next`, `format_bangumi_date`, `next_year_month`, `normalize_api_sort_type`, `parse_bangumi_list`, `parse_bangumi_next_trending_results`, `parse_bangumi_search_item`, `parse_bangumi_search_results`, `parse_search_tags`, `parse_year_month`, `search_bangumi_subject_html`, `search_bangumi_tag_html`, `stringify_infobox_value`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `YearMonth`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `cmp`, `eq`, `fmt`, `fmt`, `partial_cmp`

Future<List<RankingAnime>> fetchBangumiRanking({
  required String sortType,
  required int page,
}) => RustLib.instance.api.crateApiRankingFetchBangumiRanking(
  sortType: sortType,
  page: page,
);

Future<List<RankingAnime>> fetchBangumiBrowser({
  required String sortType,
  required String year,
  required List<String> tags,
  required int page,
}) => RustLib.instance.api.crateApiRankingFetchBangumiBrowser(
  sortType: sortType,
  year: year,
  tags: tags,
  page: page,
);

Future<List<RankingAnime>> searchBangumiSubject({
  required String keyword,
  required String sortType,
  required int page,
}) => RustLib.instance.api.crateApiRankingSearchBangumiSubject(
  keyword: keyword,
  sortType: sortType,
  page: page,
);

Future<List<RankingAnime>> searchBangumiTag({
  required String tag,
  required String sortType,
  required int page,
}) => RustLib.instance.api.crateApiRankingSearchBangumiTag(
  tag: tag,
  sortType: sortType,
  page: page,
);

class RankingAnime {
  final String title;
  final String bangumiId;
  final String coverUrl;
  final double? score;
  final int? rank;
  final String info;
  final String? originalTitle;

  const RankingAnime({
    required this.title,
    required this.bangumiId,
    required this.coverUrl,
    this.score,
    this.rank,
    required this.info,
    this.originalTitle,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      bangumiId.hashCode ^
      coverUrl.hashCode ^
      score.hashCode ^
      rank.hashCode ^
      info.hashCode ^
      originalTitle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RankingAnime &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          bangumiId == other.bangumiId &&
          coverUrl == other.coverUrl &&
          score == other.score &&
          rank == other.rank &&
          info == other.info &&
          originalTitle == other.originalTitle;
}
