// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_bangumi_list`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<List<RankingAnime>> fetchBangumiRanking({
  required String sortType,
  required int page,
}) => RustLib.instance.api.crateApiRankingFetchBangumiRanking(
  sortType: sortType,
  page: page,
);

Future<List<RankingAnime>> fetchBangumiBrowser({
  required String sortType,
  required String year,
  required List<String> tags,
  required int page,
}) => RustLib.instance.api.crateApiRankingFetchBangumiBrowser(
  sortType: sortType,
  year: year,
  tags: tags,
  page: page,
);

Future<List<RankingAnime>> searchBangumiSubject({
  required String keyword,
  required int page,
}) => RustLib.instance.api.crateApiRankingSearchBangumiSubject(
  keyword: keyword,
  page: page,
);

class RankingAnime {
  final String title;
  final String bangumiId;
  final String coverUrl;
  final double? score;
  final int? rank;
  final String info;
  final String? originalTitle;

  const RankingAnime({
    required this.title,
    required this.bangumiId,
    required this.coverUrl,
    this.score,
    this.rank,
    required this.info,
    this.originalTitle,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      bangumiId.hashCode ^
      coverUrl.hashCode ^
      score.hashCode ^
      rank.hashCode ^
      info.hashCode ^
      originalTitle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RankingAnime &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          bangumiId == other.bangumiId &&
          coverUrl == other.coverUrl &&
          score == other.score &&
          rank == other.rank &&
          info == other.info &&
          originalTitle == other.originalTitle;
}
