// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AnimeInfo {
  final String title;
  final String? subTitle;
  final String? bangumiId;
  final String? mikanId;
  final String? coverUrl;
  final String? siteUrl;
  final String? broadcastDay;
  final String? broadcastTime;
  final double? score;
  final int? rank;
  final List<String> tags;
  final String? fullJson;

  const AnimeInfo({
    required this.title,
    this.subTitle,
    this.bangumiId,
    this.mikanId,
    this.coverUrl,
    this.siteUrl,
    this.broadcastDay,
    this.broadcastTime,
    this.score,
    this.rank,
    required this.tags,
    this.fullJson,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      subTitle.hashCode ^
      bangumiId.hashCode ^
      mikanId.hashCode ^
      coverUrl.hashCode ^
      siteUrl.hashCode ^
      broadcastDay.hashCode ^
      broadcastTime.hashCode ^
      score.hashCode ^
      rank.hashCode ^
      tags.hashCode ^
      fullJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnimeInfo &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          subTitle == other.subTitle &&
          bangumiId == other.bangumiId &&
          mikanId == other.mikanId &&
          coverUrl == other.coverUrl &&
          siteUrl == other.siteUrl &&
          broadcastDay == other.broadcastDay &&
          broadcastTime == other.broadcastTime &&
          score == other.score &&
          rank == other.rank &&
          tags == other.tags &&
          fullJson == other.fullJson;
}

class ArchiveQuarter {
  final String year;
  final String quarter;
  final String title;

  const ArchiveQuarter({
    required this.year,
    required this.quarter,
    required this.title,
  });

  @override
  int get hashCode => year.hashCode ^ quarter.hashCode ^ title.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArchiveQuarter &&
          runtimeType == other.runtimeType &&
          year == other.year &&
          quarter == other.quarter &&
          title == other.title;
}

class BangumiDataCacheStatus {
  final bool cached;
  final BigInt fileSize;
  final BigInt? lastModifiedSecs;
  final String version;
  final BigInt? lastFailedSecs;

  const BangumiDataCacheStatus({
    required this.cached,
    required this.fileSize,
    this.lastModifiedSecs,
    required this.version,
    this.lastFailedSecs,
  });

  @override
  int get hashCode =>
      cached.hashCode ^
      fileSize.hashCode ^
      lastModifiedSecs.hashCode ^
      version.hashCode ^
      lastFailedSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BangumiDataCacheStatus &&
          runtimeType == other.runtimeType &&
          cached == other.cached &&
          fileSize == other.fileSize &&
          lastModifiedSecs == other.lastModifiedSecs &&
          version == other.version &&
          lastFailedSecs == other.lastFailedSecs;
}

/// One site of a bangumi-data entry, resolved (URL template filled in) and
/// safe to expose to Dart via flutter_rust_bridge.
class BangumiDataSiteEntry {
  final String site;
  final String title;
  final String url;
  final String kind;
  final String? comment;

  const BangumiDataSiteEntry({
    required this.site,
    required this.title,
    required this.url,
    required this.kind,
    this.comment,
  });

  @override
  int get hashCode =>
      site.hashCode ^
      title.hashCode ^
      url.hashCode ^
      kind.hashCode ^
      comment.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BangumiDataSiteEntry &&
          runtimeType == other.runtimeType &&
          site == other.site &&
          title == other.title &&
          url == other.url &&
          kind == other.kind &&
          comment == other.comment;
}
