// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Channel（线路）信息
class ChannelInfo {
  /// Channel 名称（如"线路A"、"简中"、"繁中"等）
  final String name;

  /// Channel 索引
  final BigInt index;

  const ChannelInfo({required this.name, required this.index});

  @override
  int get hashCode => name.hashCode ^ index.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChannelInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          index == other.index;
}

/// 剧集信息
class EpisodeInfo {
  /// 剧集名称/标题
  final String name;

  /// 剧集URL
  final String url;

  /// 剧集号（如果能解析出来）
  final int? episodeNumber;

  /// 所属channel索引
  final BigInt channelIndex;

  const EpisodeInfo({
    required this.name,
    required this.url,
    this.episodeNumber,
    required this.channelIndex,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      url.hashCode ^
      episodeNumber.hashCode ^
      channelIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EpisodeInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          url == other.url &&
          episodeNumber == other.episodeNumber &&
          channelIndex == other.channelIndex;
}

/// 搜索结果：包含播放页面URL和视频URL匹配正则
class SearchPlayResult {
  /// 源名称
  final String sourceName;

  /// 播放页面 URL
  final String playPageUrl;

  /// 用于匹配视频URL的正则表达式
  final String videoRegex;

  /// 直接解析得到的视频URL（如果有）
  final String? directVideoUrl;

  /// 播放所需的 Cookie
  final String? cookies;

  /// 播放所需的 Headers (Referer, User-Agent etc)
  final Map<String, String>? headers;

  /// Channel 名称（如果有多channel）
  final String? channelName;

  /// Channel 索引
  final BigInt? channelIndex;

  /// 验证码配置JSON（如果该源启用了captcha绕过）
  final String? captchaConfigJson;

  /// 是否启用嵌套URL匹配
  final bool enableNestedUrl;

  /// 嵌套URL匹配正则
  final String? matchNestedUrl;

  const SearchPlayResult({
    required this.sourceName,
    required this.playPageUrl,
    required this.videoRegex,
    this.directVideoUrl,
    this.cookies,
    this.headers,
    this.channelName,
    this.channelIndex,
    this.captchaConfigJson,
    required this.enableNestedUrl,
    this.matchNestedUrl,
  });

  @override
  int get hashCode =>
      sourceName.hashCode ^
      playPageUrl.hashCode ^
      videoRegex.hashCode ^
      directVideoUrl.hashCode ^
      cookies.hashCode ^
      headers.hashCode ^
      channelName.hashCode ^
      channelIndex.hashCode ^
      captchaConfigJson.hashCode ^
      enableNestedUrl.hashCode ^
      matchNestedUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchPlayResult &&
          runtimeType == other.runtimeType &&
          sourceName == other.sourceName &&
          playPageUrl == other.playPageUrl &&
          videoRegex == other.videoRegex &&
          directVideoUrl == other.directVideoUrl &&
          cookies == other.cookies &&
          headers == other.headers &&
          channelName == other.channelName &&
          channelIndex == other.channelIndex &&
          captchaConfigJson == other.captchaConfigJson &&
          enableNestedUrl == other.enableNestedUrl &&
          matchNestedUrl == other.matchNestedUrl;
}

/// 包含多channel信息的搜索结果
class SearchResultWithChannels {
  /// 源名称
  final String sourceName;

  /// 动画详情页URL
  final String detailUrl;

  /// 匹配到的动画名称
  final String matchedTitle;

  /// 所有可用的channels（线路）
  final List<ChannelInfo> channels;

  /// 所有剧集列表（按channel分组）
  final List<EpisodeInfo> episodes;

  /// 用于匹配视频URL的正则表达式
  final String videoRegex;

  /// 播放所需的 Cookie
  final String? cookies;

  /// 播放所需的 Headers
  final Map<String, String>? headers;

  /// 默认字幕语言
  final String? defaultSubtitleLanguage;

  /// 默认分辨率
  final String? defaultResolution;

  const SearchResultWithChannels({
    required this.sourceName,
    required this.detailUrl,
    required this.matchedTitle,
    required this.channels,
    required this.episodes,
    required this.videoRegex,
    this.cookies,
    this.headers,
    this.defaultSubtitleLanguage,
    this.defaultResolution,
  });

  @override
  int get hashCode =>
      sourceName.hashCode ^
      detailUrl.hashCode ^
      matchedTitle.hashCode ^
      channels.hashCode ^
      episodes.hashCode ^
      videoRegex.hashCode ^
      cookies.hashCode ^
      headers.hashCode ^
      defaultSubtitleLanguage.hashCode ^
      defaultResolution.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchResultWithChannels &&
          runtimeType == other.runtimeType &&
          sourceName == other.sourceName &&
          detailUrl == other.detailUrl &&
          matchedTitle == other.matchedTitle &&
          channels == other.channels &&
          episodes == other.episodes &&
          videoRegex == other.videoRegex &&
          cookies == other.cookies &&
          headers == other.headers &&
          defaultSubtitleLanguage == other.defaultSubtitleLanguage &&
          defaultResolution == other.defaultResolution;
}

/// 搜索进度状态
enum SearchStep {
  /// 等待中
  pending,

  /// 正在搜索
  searching,

  /// 正在获取详情页
  fetchingDetail,

  /// 正在获取剧集列表
  fetchingEpisodes,

  /// 正在提取视频URL
  extractingVideo,

  /// 搜索成功
  success,

  /// 搜索失败
  failed,
}

class SourceConfigUpdate {
  final String name;
  final String? newName;
  final int? tier;
  final String? defaultSubtitleLanguage;
  final String? defaultResolution;
  final String? searchUrl;
  final String? iconUrl;
  final String? description;
  final String? searchConfigJson;
  final String? captchaConfigJson;

  const SourceConfigUpdate({
    required this.name,
    this.newName,
    this.tier,
    this.defaultSubtitleLanguage,
    this.defaultResolution,
    this.searchUrl,
    this.iconUrl,
    this.description,
    this.searchConfigJson,
    this.captchaConfigJson,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      newName.hashCode ^
      tier.hashCode ^
      defaultSubtitleLanguage.hashCode ^
      defaultResolution.hashCode ^
      searchUrl.hashCode ^
      iconUrl.hashCode ^
      description.hashCode ^
      searchConfigJson.hashCode ^
      captchaConfigJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceConfigUpdate &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          newName == other.newName &&
          tier == other.tier &&
          defaultSubtitleLanguage == other.defaultSubtitleLanguage &&
          defaultResolution == other.defaultResolution &&
          searchUrl == other.searchUrl &&
          iconUrl == other.iconUrl &&
          description == other.description &&
          searchConfigJson == other.searchConfigJson &&
          captchaConfigJson == other.captchaConfigJson;
}

class SourceRuntimeOverride {
  final String sourceName;
  final String? cookies;
  final String? searchPageHtml;
  final String? searchPageUrl;
  final String? detailPageHtml;
  final String? detailPageUrl;
  final String? skipSearchError;

  const SourceRuntimeOverride({
    required this.sourceName,
    this.cookies,
    this.searchPageHtml,
    this.searchPageUrl,
    this.detailPageHtml,
    this.detailPageUrl,
    this.skipSearchError,
  });

  @override
  int get hashCode =>
      sourceName.hashCode ^
      cookies.hashCode ^
      searchPageHtml.hashCode ^
      searchPageUrl.hashCode ^
      detailPageHtml.hashCode ^
      detailPageUrl.hashCode ^
      skipSearchError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceRuntimeOverride &&
          runtimeType == other.runtimeType &&
          sourceName == other.sourceName &&
          cookies == other.cookies &&
          searchPageHtml == other.searchPageHtml &&
          searchPageUrl == other.searchPageUrl &&
          detailPageHtml == other.detailPageHtml &&
          detailPageUrl == other.detailPageUrl &&
          skipSearchError == other.skipSearchError;
}

/// 带状态的搜索进度
class SourceSearchProgress {
  /// 源名称
  final String sourceName;

  /// 当前搜索步骤
  final SearchStep step;

  /// 错误信息（如果有）
  final String? error;

  /// 播放页面 URL（如果找到）
  final String? playPageUrl;

  /// 用于匹配视频URL的正则表达式
  final String? videoRegex;

  /// 直接解析得到的视频URL（如果有）
  final String? directVideoUrl;

  /// 播放所需的 Cookie
  final String? cookies;

  /// 播放所需的 Headers
  final Map<String, String>? headers;

  /// Channel 名称（如果有多channel）
  final String? channelName;

  /// Channel 索引
  final BigInt? channelIndex;

  /// 所有可用的channels（搜索成功时填充）
  final List<ChannelInfo>? allChannels;

  /// 验证码配置JSON（如果该源启用了captcha绕过）
  final String? captchaConfigJson;

  /// 是否启用嵌套URL匹配
  final bool enableNestedUrl;

  /// 嵌套URL匹配正则
  final String? matchNestedUrl;

  const SourceSearchProgress({
    required this.sourceName,
    required this.step,
    this.error,
    this.playPageUrl,
    this.videoRegex,
    this.directVideoUrl,
    this.cookies,
    this.headers,
    this.channelName,
    this.channelIndex,
    this.allChannels,
    this.captchaConfigJson,
    required this.enableNestedUrl,
    this.matchNestedUrl,
  });

  @override
  int get hashCode =>
      sourceName.hashCode ^
      step.hashCode ^
      error.hashCode ^
      playPageUrl.hashCode ^
      videoRegex.hashCode ^
      directVideoUrl.hashCode ^
      cookies.hashCode ^
      headers.hashCode ^
      channelName.hashCode ^
      channelIndex.hashCode ^
      allChannels.hashCode ^
      captchaConfigJson.hashCode ^
      enableNestedUrl.hashCode ^
      matchNestedUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceSearchProgress &&
          runtimeType == other.runtimeType &&
          sourceName == other.sourceName &&
          step == other.step &&
          error == other.error &&
          playPageUrl == other.playPageUrl &&
          videoRegex == other.videoRegex &&
          directVideoUrl == other.directVideoUrl &&
          cookies == other.cookies &&
          headers == other.headers &&
          channelName == other.channelName &&
          channelIndex == other.channelIndex &&
          allChannels == other.allChannels &&
          captchaConfigJson == other.captchaConfigJson &&
          enableNestedUrl == other.enableNestedUrl &&
          matchNestedUrl == other.matchNestedUrl;
}

class SourceState {
  final String name;
  final String description;
  final String iconUrl;
  final int tier;
  final String defaultSubtitleLanguage;
  final String defaultResolution;
  final String searchUrl;
  final String searchConfigJson;
  final String? captchaConfigJson;
  final bool enabled;

  const SourceState({
    required this.name,
    required this.description,
    required this.iconUrl,
    required this.tier,
    required this.defaultSubtitleLanguage,
    required this.defaultResolution,
    required this.searchUrl,
    required this.searchConfigJson,
    this.captchaConfigJson,
    required this.enabled,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      description.hashCode ^
      iconUrl.hashCode ^
      tier.hashCode ^
      defaultSubtitleLanguage.hashCode ^
      defaultResolution.hashCode ^
      searchUrl.hashCode ^
      searchConfigJson.hashCode ^
      captchaConfigJson.hashCode ^
      enabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceState &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          iconUrl == other.iconUrl &&
          tier == other.tier &&
          defaultSubtitleLanguage == other.defaultSubtitleLanguage &&
          defaultResolution == other.defaultResolution &&
          searchUrl == other.searchUrl &&
          searchConfigJson == other.searchConfigJson &&
          captchaConfigJson == other.captchaConfigJson &&
          enabled == other.enabled;
}
